### ISSUE TITLE
Can't import a model 

### ISSUE THREAD

**Issue by LuxrayTheWolf** [powroupi/blender_mmd_tools#100]
I can't import a model even though im using the newest version of mmd_tools

**Comment by powroupi** [comment]
Please show me the error messages or the link of the sample model, thank you. :smile:

**Comment by powroupi** [comment]
You might try to update your mmd_tools using my [dev_test](https://github.com/powroupi/blender_mmd_tools/tree/dev_test) branch. Directly download [here](https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip). If you still get errors, please let me know. Thank you. :smile:

**Comment by Selfdefends** [comment]
Me too,i cant import as well,tried dev_test,but it doesn't work.

**Comment by powroupi** [comment]
Is there any error? What model do you want to import, any download link? :confused:

**Comment by Selfdefends** [comment]
Thank you for reply,I have already fixed it somehow.mmd_tools just can't import by blender,i need copy that by myself.I don't know why.

**Comment by powroupi** [comment]
@Selfdefends So, you can install and enable mmd_tools successfully, just can't import a model, right? I guess the model's file path might contain some invalid characters, this can be solved by renaming the file or moving it to another directory, or select a correct encoding when extracting files.  :wink:

**Comment by Selfdefends** [comment]
I'll try it,thank you.

**Comment by powroupi** [comment]
Please open a new issue if you still can't import some models when using latest `mmd_tools`([dev_test](https://github.com/powroupi/blender_mmd_tools/tree/dev_test) branch, directly download https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip). Thank you. :smile:
