### ISSUE TITLE
physics dancing from mid-animation

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#102]
I must begin playing a dance animation at the beginning of the dance animation (first frame of the imported VMD animation). If I begin playing the dance animation in the middle of the dance animation, the physics are a complete mess. Many bones and their vertex groups are frozen in one place.

Is there no possibility that someone can begin playing a dance animation in the middle of the dance animation with correct physics?

At first, I did not understand why this was happening and this was a big waste of time for me trying to understand why this was happening. This issue may waste time and cause frustration for people who are trying to use mmd_tools.

**Comment by powroupi** [comment]
Maybe similar issue to #49 , #95. It is not a feature of mmd_tools, you need to learn Blender's [Rigid Body World](https://docs.blender.org/manual/en/dev/physics/rigid_body/world.html) stuff. :smile: 

To solve it, the simplest way is [Bake Physics]. :sunglasses:
