### ISSUE TITLE
vertices not moving

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#103]
![ab7 vertices issue](https://user-images.githubusercontent.com/10057979/35210567-c035f722-ff20-11e7-8de5-ecedecb2575e.jpg)

3 vertices of Kakomiki AB Chan 7 imported by mmd_tools are not moving. This problem does not happen in MMD. Clean or not clean model makes no difference. Remove doubles makes problems worse. Physics or not physics build makes no difference. Presumably this issue may happen with other models. AB7 is just a test example for this issue.

**Comment by ptrthomas** [comment]
I've noticed this. I think this has something to do with shape keys and perhaps these vertices are hidden by default when the model loads. I think you can fix this by adding these vertices to the right "vertex group" for e.g. waist. I agree that this is a possible bug in mmd_tools

**Comment by powroupi** [comment]
The vertices seems have a very low weight on lower body bone (`下半身`), normalize weights on import should fix this bug. :)

**Comment by ptrthomas** [comment]
@powroupi thanks for the tip ! it works :)

**Comment by powroupi** [comment]
It is fixed now, I mainly changed ```type='REPLACE'``` to ```type='ADD'```, see commit ce13c72. :smile:

**Comment by Hogarth-MMD** [comment]
Excellent bug fix. Thanks!
