### ISSUE TITLE
export VMD from python

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#104]
``` python
import bpy

bpy.ops.mmd_tools.export_vmd()
```

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\mmd_tools\operators\fileio.py", line 623, in execute
    vmd_exporter.VMDExporter().export(**params)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\mmd_tools\core\vmd\exporter.py", line 390, in export
    vmdFile.save(filepath=filepath)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\mmd_tools\core\vmd\__init__.py", line 272, in save
    with open(path, 'wb') as fin:
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by Hogarth-MMD** [comment]
I am trying to do a mass export of VMD animations from Sintel scene files, by python script. When I run the script above, the file manager does not open and there is no opportunity to designate the file path where the files should be saved. The above error results. Please tell me how do I fix this?

**Comment by powroupi** [comment]
When you type the command in Blender Python Console, you should get this
```
>>> bpy.ops.mmd_tools.export_vmd(
export_vmd()
bpy.ops.mmd_tools.export_vmd(filepath="", check_existing=True, filter_glob="*.vmd", scale=1, use_pose_mode=False, use_frame_range=False)
>>> bpy.ops.mmd_tools.export_vmd(
```
If you want to export vmd via script, you should assign a valid filepath like this
```
bpy.ops.mmd_tools.export_vmd(filepath='C:\\test.vmd')
```

**Comment by Hogarth-MMD** [comment]
Thank you @powroupi for this excellent help and for the generous giving of your time. :smile: This python script seems to be successful in mass exporting VMD character animations from a Sintel scene file. The next challenge is the exporting of the camera animation.

```python
import bpy

print('\n\n')
for o in bpy.context.scene.objects:
	if o.type == 'ARMATURE':
		bpy.context.scene.objects.active = o
		filename = bpy.data.filepath.replace("C:\\d\\pro\\scenes\\", "").replace(".blend", "").replace("\\", "") + " " + o.name + " " + o.animation_data.action.name + ".vmd"
		begin = filename.find("_") + 1
		filename = filename[begin:]
		print(filename)
		bpy.ops.mmd_tools.export_vmd(filepath="C:\\Sintel_VMD\\" + filename, check_existing=True, filter_glob="*.vmd", scale=1, use_pose_mode=False, use_frame_range=False)
```

**Comment by Hogarth-MMD** [comment]
Is mmd_tools able to export a camera animation from Blender, just by selecting the camera and exporting to vmd? 

In the Sintel files, there may be more than one camera being animated, whose animations need to be moved onto one camera before being exported. But I guess that mmd_tools cannot deal with exporting the animations of several cameras in a scene(?).

**Comment by powroupi** [comment]
Export Blender general camera's animation would not look right in MMD, you need to convert it to MMD Camera (enable "Bake Animation" as need) in Blender. And mmd_tools cannot combine multiple cameras' animation, it can be done manually in Blender though.

**Comment by powroupi** [comment]
>But I guess that mmd_tools cannot deal with exporting the animations of several cameras in a scene(?).

You can export scene camera animation now, just enable "Bake Animation" and change `Camera Source` from `Current` to `Scene`. :smile: 

Simple script example:
```python
import bpy
from mmd_tools.core.camera import MMDCamera
scene_camera_rig = MMDCamera.newMMDCameraAnimation(None) # bake scene camera
normal_camera_rig = MMDCamera.newMMDCameraAnimation(bpy.context.active_object) # bake active camera
```

**Comment by Hogarth-MMD** [comment]
The latest commit by @powroupi  :smile: 

https://github.com/powroupi/blender_mmd_tools/commit/5aeb4c62062ffa6ce568e76f3dfb4b06b6bec535

Update "Convert Camera/Model", "MMDBonePanel", and some minor changes

Showing  8 changed files  with 53 additions and 53 deletions.

Thanks, I just downloaded it, but I haven't tried it yet.

**Comment by Hogarth-MMD** [comment]
Can you please provide some additional instructions? I am not seeing any new options and I am not able to export a Blender camera animation.

**Comment by Hogarth-MMD** [comment]
Okay, I found it. With the camera selected to be the active object, under the object tab of the Properties window, there is a panel called MMD Camera Tools, which has a button labeled "Convert". Click this button and the popup dialog box which appears has these new options.

**Comment by Hogarth-MMD** [comment]
The mmd_tools panel would be a more convenient, user-friendly location for this, by the way.

**Comment by Hogarth-MMD** [comment]
Hello @powroupi! The export of VMD camera animation does not work. When I try to import the camera animation into MMD, I get this message: This motion file has not camera, light shadow data.

**Comment by Hogarth-MMD** [comment]
Hello @powroupi ! Please excuse me, the export of camera animation is successful, including the baking of animation from 2 cameras. But I needed to find and select the MMD camera in the Outliner  window. I could not see the MMD camera empty object in the 3D view, so I mistakenly exported a VMD animation from a character, instead of from the MMD camera empty object. To fix this problem, I recommend increasing the size and visibility of the MMD camera empty object, or better, to allow export to VMD when the camera is the active object.

**Comment by Hogarth-MMD** [comment]
This is excellent work @powroupi , and I thank you for this excellent work. Baking animation causes a key frame for every single frame. It would be better if the original keyframe frames are preserved. 
If a Blender camera is constrained to point at an empty object, will your python code successfully deal with this situation and make a correct camera conversion? Constraining a camera to point at an empty object is quite common in Blender 3D camera animation.

**Comment by Hogarth-MMD** [comment]
I am trying to understand how we can export the shape key animations of Sintel. In Sintel, the facial animations are shape key animations which are controlled by a combination of pose bone animations and slider controls of custom properties of pose bones.
So, for every key frame of these bones and custom properties, a python script can copy the value of each shape key of 60 shape keys. If the value of this shape key has changed since the last key frame, then this value is stored in a shape key animation.
I have not tested this idea. If @powroupi or anyone else has any better idea, please tell me what idea you have.

**Comment by powroupi** [comment]
>If a Blender camera is constrained to point at an empty object, will your python code successfully deal with this situation and make a correct camera conversion?

Select the empty object, shift select the camera, then bake current camera animation. It is not supported when baking scene camera animation. I can't find a way to detect camera target yet. :cry:
