### ISSUE TITLE
Leg Animations Not Working

### ISSUE THREAD

**Issue by vranimeted** [powroupi/blender_mmd_tools#105]
I'm trying to import and play an animation, but when I do the legs are stiff and just swinging to the sides.  I'm thinking it might be that the leg IKs are not being registered into the animation, but when I tested the model and animation in MMD with the leg and toe IKS off the behavior is a little different.  The legs are still stiff, but they are not swinging as wildly as in Blender.  I've tried multiple models, tda and non tda based as well as multiple motions with the same results.  When importing models in I use the default settings aside from rescaling to .2

Confirmed that same model and motion work fully in master build of mmd tools.

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: 

I guess the motion's scale you set was wrong. If you imported a model with scale 0.2, you need to import a motion with scale 0.2 too. Please note, all scale values of mmd_tools import/export options are default 1.0 now. :)

You may test this by using default settings when import models and motions.

**Comment by vranimeted** [comment]
That totally was the issue.  Well I feel ridiculous lol.  Thanks for the quick response and the hard work on the tool!
