### ISSUE TITLE
Can't import model. "NoneType" has no attribute "tail".

### ISSUE THREAD

**Issue by chrispyni** [powroupi/blender_mmd_tools#106]
Can't import normaly. Imports only bones and vertices.

Here's screenshot: [LINK](https://image.ibb.co/fpDuRw/34.jpg)

**Comment by powroupi** [comment]
Looks like you are using master branch (old version) of mmd_tools, try to update your mmd_tools using my [dev_test](https://github.com/powroupi/blender_mmd_tools/tree/dev_test) branch. Directly download [here](https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip). If you still get errors, please let me know. Thank you. :smile:

**Comment by chrispyni** [comment]
This version is working, thx. I've download from link at DeviantArt. Maybe link was old.

**Comment by powroupi** [comment]
You're welcome. I'm glad that helps. :smile:
