### ISSUE TITLE
Configuring Add-Ons HELP!

### ISSUE THREAD

**Issue by Oapira** [powroupi/blender_mmd_tools#107]
I followed the Install, and Loading Add-On steps. But Configuring Add-On steps not sure what do to here.  How do i navigate to this mmd_tools Addon Preferences? Then the following steps may be more clear. Shared Toon Texture Folder
The Data directory within of your MikuMikuDance directory for toon textures (toon01.bmp ~ toon10.bmp).
Base Texture Folder
Path for textures shared between models. In order to copy textures properly while exporting to pmx file.
Dictionary Folder
Path for searching custom csv dictionaries. You can create your own dictionary or download from Hogarth-MMD/mmd_tools_translation.

**Comment by nathanvasil** [comment]
You might want to check out the documentation on the wiki at https://github.com/powroupi/blender_mmd_tools/wiki/Documentation .  That should give you more info than the mouseover tooltips, IIRC.  Although I don't think there's a dictionary folder section yet.  (Anyone?  I haven't used this feature myself.)

When you're on the Add-ons tab of the user preferences, there's a little triangle to the left of the "Object: mmd_tools" addon.  Click that triangle to expand the panel to allow configuration of the add-on.

**Comment by powroupi** [comment]
>Although I don't think there's a dictionary folder section yet. (Anyone? I haven't used this feature myself.)

Default `Dictionary Folder` will be the /mmd_tools/ folder. However, you can change it as you like. :smile: 

And as @nathanvasil said, **Click that triangle to expand the panel to allow configuration of the add-on.** :)
