### ISSUE TITLE
Convert Model materials conversion

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#111]
This is how the ambient color is implemented in the Convert Model operator now:
```python
mmd_material.ambient_color = [0.5*c for c in diffuse]
```

Blender's obj exporter and importer are using the mirror color to store the ambient color.
XNALaraMesh importer and exporter for XNALara models is also using the mirror color to store the ambient color. Pymeshio does this also. DAZ/Poser models use .obj files, so presumably whatever Blender add-ons exist or will exist for DAZ/Poser models will also be using mirror color to store tha ambient color data. The mirror color is not being used to render the ambient color. The mirror color is just being used to store the ambient color data for later export. Blender's default value for mirror color is (1,1,1).

A fix for this can be implemented in the Convert Model operator:
```python
if m.raytrace_mirror.use == False:
	if m.mirror_color != (1,1,1):
		mmd_material.ambient_color = m.mirror_color
	else:
		mmd_material.ambient_color = [0.5*c for c in diffuse]

**Comment by Hogarth-MMD** [comment]
mmd_tools exporter has a disable sph/spa option, but this is inadequate when converting a model from other software. When sphere textures are disabled, the PMX error checker flags this as an error. The user then needs to use Google translate to translate this error information. Then the user needs to manually correct all of the materials. This can be a big waste of time for the user of mmd_tools.

If I understand correctly, there is no mmd_tools custom property for sphere texture, but the sphere texture is mapped onto normal co-ordinates. So a bug fix for this could be implemented in the mmd_tools pmx exporter, something like this:

```python
if m.texture_slots[2].texture_coords != 'NORMAL':
	#no export sphere texture
```

**Comment by Hogarth-MMD** [comment]
```python
# Add diffuse, toon, sphere, custom properties to mmd_tools imported textures

import bpy

for o in bpy.context.scene.objects:
	if o.type == 'MESH':
		if o.mmd_type != 'RIGID_BODY':
			if o.data.materials is not None:
				for m in o.data.materials:
					if m.texture_slots is not None:
						for t in range(len(m.texture_slots)):
							if m.texture_slots[t] is not None:
								texture_name = m.texture_slots[t].texture.name
								if t == 0:
									bpy.data.textures[texture_name]["mmd_texture_type"] = "MMD_DIFFUSE"
								if t == 1:
									bpy.data.textures[texture_name]["mmd_texture_type"] = "MMD_TOON"
								if t == 2:
									bpy.data.textures[texture_name]["mmd_texture_type"] = "MMD_SPHERE"
```

**Comment by Hogarth-MMD** [comment]
Hello @powroupi! What do you think? Possibly mmd_tools should have custom properties to identify  diffuse, toon and sphere textures. This can avoid confusion in Python script writing, if someone might be using a model converted from other software. For, example, when I made my toon textures node editor script, I just identified these 3 textures by the order in which they appear in the texture slots (0,1,2).

**Comment by powroupi** [comment]
>The mirror color is just being used to store the ambient color data for later export.

Maybe I'll add an option for that, so we can use default conversion or use mirror color. :smile: 

>What do you think? Possibly mmd_tools should have custom properties to identify diffuse, toon and sphere textures.

I don't like to implement another rule to identify textures at the moment, it may be confusing. And currently we don't detect toon texture which is defined in [MMDMaterial](https://github.com/powroupi/blender_mmd_tools/blob/5aeb4c62062ffa6ce568e76f3dfb4b06b6bec535/mmd_tools/properties/material.py#L227-L249).
