### ISSUE TITLE
automatically add physics to a model

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#114]
```
import bpy
from mmd_tools.operators.rigid_body import AddRigidBody

AddRigidBody(bpy.types.Operator)
```
Traceback (most recent call last):
  File "\automatically_add_physics.py", line 9, in <module>
TypeError: bpy_struct.__new__(type): type 'AddRigidBody' is not a subtype of bpy_struct
Error: Python script fail, look in the console for now.

**Comment by Hogarth-MMD** [comment]
Hello @powroupi! I found this operator in mmd_tools and I thought that I can use this operator to automatically add physics to a model, but it just gives me an error message. What am I doing wrong and how can I succeed in making this work?

**Comment by powroupi** [comment]
Because it is an operator, you should use `bpy.ops.mmd_tools.add_rigid_body()` to call this function. This operator adds MMD rigid bodies to selected pose bones. :smile:

**Comment by Hogarth-MMD** [comment]
Excellent, this was successful. Thanks! :smile:
