### ISSUE TITLE
VMD interpolation data?

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#117]
Hello @powroupi ! What does mmd_tools do with VMD interpolation curve data? Is it just ignored when importing a VMD animation? Is it stored for later export? Is it converted to Blender data?

**Comment by powroupi** [comment]
It is converted to Blender Fcurve handles. (see [vmd.importer](https://github.com/powroupi/blender_mmd_tools/blob/89b850e9db5bfe1460e2fd650de4704ec3a004e7/mmd_tools/core/vmd/importer.py#L116-L126) and [vmd.exporter](https://github.com/powroupi/blender_mmd_tools/blob/89b850e9db5bfe1460e2fd650de4704ec3a004e7/mmd_tools/core/vmd/exporter.py#L30-L45)) And some interpolation may be lost (converted to linear) in some cases on exporting.
