### ISSUE TITLE
Model exports as one single mesh

### ISSUE THREAD

**Issue by Masamiki0218** [powroupi/blender_mmd_tools#119]
Hello. I'm trying to export a FBX file converted to a PMX model.
I imported the original model, a FBX file, into blender and I converted it into a MMD model with the mmd_tools option.
However, when I export it into a PMX file and I open it in PMX Editor, the model appears as a single mesh.
**Is there a way to export it conserving every separated part (head, body, eyes...) instead of having them merged?** Here's also a visual aid of what I mean.

Blender:
![blender](https://user-images.githubusercontent.com/13398181/37247082-2a87e51c-24b6-11e8-8a01-a02349981d0a.jpg)
PMX Editor:
![mmd](https://user-images.githubusercontent.com/13398181/37247087-37b2a5c4-24b6-11e8-9e02-10523fd7cf6b.jpg)

**Comment by powroupi** [comment]
Looks like your FBX model only use one combined material. Maybe try to give every mesh an individual material in Blender (click the number near material name to make a material copy for each mesh objects, then rename the material name as you like).  :smiley:

**Comment by Masamiki0218** [comment]
Yup, that was the problem. Doing that, I was able to solve it. Thank you so much!

**Comment by powroupi** [comment]
You're welcome, I'm glad that helps. :smile:
