### ISSUE TITLE
Failed import/export test.

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#12]
It was recommended that I try this fork.  I tried a simple import/export test.  I imported a model, and without even separating the materials, exported it.  I think success in this test would mean getting the same model out as I put in, but I haven't found an MMD importer for which this is true yet.

In this case, the export gave me a model with all my vertices, but without any materials, bones, bodies, or joints.  The older version of MMDTools that I have been using would have choked on the textures, but once those were removed, would have given me a valid .pmx.  In fact, it has been, that's how I have been editing.  Interestingly, deleting all textures from the model, and some materials, led to a valid export from your plugin.

Before and after files are in http://www.mediafire.com/download/y3na5z1eo52oe3g/beforeandafter.zip  It's a pornographic model, so don't look if you find that offensive.  I'm not attaching peripheral files like textures.  I don't think you need them.

Blender 2.77.  Not sure which MMDTools I'm using.  Changelog suggest 0.4.5, but it looks like that's not updated with the code.

Thanks for the hard work, good luck with the fork.

**Comment by powroupi** [comment]
Thank you for reporting this issue.

> In this case, the export gave me a model with all my vertices, but without any materials, bones, bodies, or joints.

I don't understand this, how did you import/export the model?

For some reason, this addon does not export model identically, such as vertice order, bone order, vertex count, etc. But most of other data will not be changed, that is the **test_pmx_exporter.py** currently test for.

I tested your model, and i found it failed at **line 257**, this is an issue of IK target:

``` python
self.assertEqual(target0, target1, msg)
```

If you comment out line 257, it will fail at **line 452**:

``` python
self.assertLess(self.__vector_error(s0.rotation_offset, s1.rotation_offset), 1e-5, msg)
```

It's an issue of precision, it is acceptable in your case, and you can change **1e-5** to **1e-3**, then it will pass the test. So, your model should be exported mostly correct except the bone issues.

And the bone property `transform_order` is another issue, if you uncomment **line 227**, the test will fail.

``` python
#self.assertEqual(bone0.transform_order, bone1.transform_order, msg) #TODO
```

So, currently i use **test_pmx_exporter.py** to test out some issues which i pointed out above of this addon, and welcome developers for imporving this addon.

**Comment by lordscales91** [comment]
@powroupi 

> For some reason, this addon does not export model identically, such as vertice order, bone order, vertex count, etc.

The vertex order is different because we calculate the tesselation faces and that operation doesn't respect the vertex order, but the order should be irrelevant. In fact, except for the materials, the order is irrelevant.

@nathanvasil
I tested it and it seems to export correctly. Are you sure you are using the **latest** version? The master branch is outdated, you should use the [dev_test](https://github.com/powroupi/blender_mmd_tools/tree/dev_test)

Indeed there is a problem with the IK targets, but that probably is already an issue of the model itself. Apart from that the model preserves all data (morphs, materials, physics)

**Comment by nathanvasil** [comment]
I retested using the link provided by lordscales91, using the "clone or download"->"download zip" buttons.  I got the same issue: no materials, no morphs, no bones.  This looks like exactly how I tested before, so I'm not creating a new before-and-after.pmx; let me know if you'd like me to.

I imported the model via the "import model" button on the toolbar, and exported the model via the "export model" button on the toolbar.

But if lordscales got a successful export, why didn't I?  Did you look at it?  It has empty morph, material, bones panels in PMXE 0.2.2.2 (Eos3d's English translation).  Does it in your verson of PMXE?  I'm using default Blender settings.  The only remaining issues I can think of could be OS (I'm using Windows 10) or file paths.

Vertex order should be irrelevant, but bone order is very important, more important than material order, and one of the reasons why post-export prep is necessary-- which is a pain in the ass, but of course, I've learned to live with that.  However, I know that there are fields available for arbitrary data, and ideally, an import/export script should use this to regenerate export fields in lieu of using the translated Blender version when no relevant changes have been made.

The model's IK bones work perfectly in MMD.  Indeed, this is the right way to handle IK bones, and it took me many hours to figure it out-- you can get some interesting issues handling it differently than this, some bugs that are difficult to track down.  I'm doing some complicated stuff, IK bones that don't break x-bones, moveable IK targets, linked IK bones, IK cancel bones.  I'm not surprised that a script doesn't handle it correctly, even though I would prefer otherwise.

If you want me to retest under different circumstances, I'm willing.  I'm not going to learn python though, not right now.  I've got more than enough work improving my skills with Blender, PMXE, and MMD.

Edit: Lordscales, if you see some issues with the model in MMD, please let me know.  I'm eager to fix any problems.  But when you say that IK issues are probably issues "of the model itself," I find that as insulting as if I was to tell you that your work was mistaken without even testing it.  I've put a lot of work into the bone system, experienced a lot of frustration trying to get things right.  Please do me the favor of verifying your suspicions before voicing them.

Edit2: I wondered about something else.  I loaded the after.pmx that I sent into MMD.  Other than issues probably caused by reordering of bones, it loaded.  Trying again in PMXE, I saw that there was an unusual message in Japanese; I was unable to select the text for copy/pasting, so I'm not sure what it said.  Clicking "No" on the dialog led to no load; clicking "yes" on the dialog led to the model as I described, without any materials etc.

So I think what the real issue here is (besides some bone reordering that requires post-export correction), is that your fork is creating some sort of issue in the .pmx files that it exports that leads to at least some versions of the editor being unable to properly read it.  This was never an issue for me with the unforked version, so it's something introduced in the fork, or it's something hidden by the fact that I always deleted my textures pre-import when using the pre-fork.  Since editing is necessary to correct bone issues introduced by the export, it would be a deal-breaker for me.

Edit 3: I suspect this is a texture issue.  Unchecking "copy textures" on the export window leads to an editable .pmx.  Bone order is broken; deform tier is rewritten; IK angle and loop settings are lost (frankly I don't understand IK angle/loop, not sure if it matters).  The bone morph (morph 81 in before.pmx) has been rewritten to be useless, which was a problem existing in the pre-fork.  Vertices laying on UV seams or on material borders have been ripped on import (like the Blender "rip" tool), which was a problem also existing in the pre-fork.  That might be an issue with MMD's implementation.  It's been a long time since I tested, but I thought I saw it handling seams surprisingly well.  (The good news: no alteration of my material recolor morphs, which was an intermittent problem with the version I was using.  Intermittent, so time will tell.)

Okay!  Didn't want to get suckered into wasting a lot of time on this, but the workaround is simple, and so far, it looks like your fork would save me the trouble of deleting and restoring my textures every import/export cycle.  So thanks for that, I'll probably replace what I was using.  Other issues were already present in the version I was using.  Hopefully you can figure out what actual code issue is; in my wildest dreams, you can also fix the other problems I listed :)  Of those issues, any morph issues are the most troublesome.  Bone issues can be solved by importing the new model onto the old bone system, but when you join morphs, the new morphs contaminate the old.  Issues caused by unwarranted vertex rips can be solved fairly simply with average near normals, assuming you're not mixing soft and hard edges.

**Comment by powroupi** [comment]
@nathanvasil

> In this case, the export gave me a model with all my vertices, but without any materials, bones, bodies, or joints.

Well, i confirmed your issue using the PMXE [here](http://eoscustom3d.deviantart.com/art/English-Pmx-Editor-v1-1-542100208).

> Edit 3: I suspect this is a texture issue. Unchecking "copy textures" on the export window leads to an editable .pmx.

Confirmed as well. (interesting, i didn't expect that could cause any problem...)
But I might need more time to debug it. :)

**Comment by lordscales91** [comment]
I think I have found the root of the bone sorting problem. When exporting the bones are sorted by [bone depth](https://github.com/powroupi/blender_mmd_tools/blob/7d7a7a974a0d20812f7d7915a9f14b3659245d14/mmd_tools/core/pmx/exporter.py#L247) if the bone order is so important we should implement another panel in `mmd_utils` to sort the bones. The problem is how to keep the original order, I have observed that the bones are imported in the same order, the code is [this](https://github.com/powroupi/blender_mmd_tools/blob/7d7a7a974a0d20812f7d7915a9f14b3659245d14/mmd_tools/core/pmx/importer.py#L161-L166). However for some reason the order is not preserved by Blender. So maybe we need to store the original order in the `mmd_root` object, and then use that order when exporting. There is still a problem, sync the order with the armature changes (bone creation/deletion). Maybe it is better to assign the index directly to the `PoseBone`.

**Comment by nathanvasil** [comment]
You may be able to work around some bone order issues through careful use of deformation tier.  I'm not sure exactly what deformation tier does, but it's related to bone order issues.  I can't find documentation regarding it.

If you do end up dealing with any bone order issues, I want to warn you to be careful in your testing of your fixes.  Some problems related to bones can manifest on only the first _render_ frame of every _animation_ frame.  If you're playing at 30 fps, that's every frame, but if you're stepping through an animation, particularly at a high frames-per-second, it's easy to miss problems.

**Comment by powroupi** [comment]
@nathanvasil
I have updated my branch [dev_test](https://github.com/powroupi/blender_mmd_tools/tree/dev_test), you can test it to see if it will solve your original issue (empty materials, morphs, bones, etc)?!

@lordscales91
You might also test it, i'm not sure if my changes will break your usage of addon property `base_texture_folder`?!

Please let me know if you found any issues. Thank you. :smile:

**Comment by lordscales91** [comment]
I will test it to ensure, but probably there will be no problem. The idea of the `base_texture_folder` is allow to have the textures that are used for different models in a single location (such a Toon folder inside your Pictures folder) without having to manually copy them to the target model filepath. That feature will be specially useful when creating models from scratch, if you are starting from an imported model the correct approach is what you have done, using the original filepath. 

The only problem that I see at first glance is that it is not possible to combine existing textures from the model with new ones from the defined base texture folder (but I think that problem was already there before). I will check it when I have time, I'm a little busy right now

**Comment by powroupi** [comment]
I think the bone order issue is solved now, you can get the same order with PMDE/PMXE, and you can reorder it by reordering the vertex groups of mesh object in blender. (I think this solution is simpler than adding a bone index property to `PoseBone` or  `MMDBone`)

But note, there need a name called `'mmd_bone_order_override'` in modifiers of the mesh object (which is the default behavior on importing), and need only one if you have multiple mesh objects attached to a MMD model in blender. And If a bone name is not in the vertex groups, then it will be ordered last.  :sweat_smile:

**Comment by nathanvasil** [comment]
Sorry, haven't been using your version.  Saw the commit, decided I could spend some time on testing.

Look at http://www.mediafire.com/download/8cbt1xc9j4s2i9a/sugianytoolstest.zip ; I added toolstest.pmx to the zip, which is just the pmx imported, separated, rejoined, and exported.  (Ooops!  I named it sugiany, but it really is powroupi.)

No longer seeing the no materials issue in PMXE.  Thanks.

Bone order looks fantastic, and it's no longer rewriting deform, angle, etc, and no longer mutilating bone morphs.  Only one problem.  Check out bone 103 ( 頭IK, headIK).  It's rewriting the target from the original IK target to the head's end bone.  The IK target is its own bone in order to take a movement append so that I can "grab" the body from any point.  I could work around that, probably, but it's weird, and probably shouldn't be happening.

There are some morph issues with the same test.  I'll begin a new issue for those.

edit: "And If a bone name is not in the vertex groups, then it will be ordered last."  Don't really understand, because IK bones shouldn't be in any vertex groups, right?  But you're maintaining their order correctly.

The modifier implementation is probably fine; the only thing that I notice is that there's no longer an armature modifer?  I don't need the armature in Blender personally, but isn't that important to anybody that wants to use PMX models in a Blender render?

**Comment by powroupi** [comment]
> Ooops! I named it sugiany, but it really is powroupi

That's fine, i don't mind. :smile: 

> Only one problem. Check out bone 103 ( 頭IK, headIK). It's rewriting the target from the original IK target to the head's end bone.

The IK target is still an issue. The way we export the IK target is just to find the closest child bone of the "IK constraint" bone in blender, and the connected child bone is preferred. So the wrong IK target may be chosen when there are multiple choices. I'm still finding a way to solve it. >_<

> edit: "And If a bone name is not in the vertex groups, then it will be ordered last." Don't really understand, because IK bones shouldn't be in any vertex groups, right?

If you want to get the bone order you want, it's necessary to add the vertex group and reorder it yourself even if the bone does not affect the mesh. But the order has no effect in blender, it is just for the exporter and it's possible that your armature works fine in blender and does not in MMD when the bone order is incorrect.

> The modifier implementation is probably fine; the only thing that I notice is that there's no longer an armature modifer? I don't need the armature in Blender personally, but isn't that important to anybody that wants to use PMX models in a Blender render?

Anybody that wants to use PMX models in a Blender render can completely ignore the bone order issue which is relevant to the exporter, not the importer.

Sorry for my english, hopefully i answered your questions. :smile:

**Comment by nathanvasil** [comment]
Your English is beautiful.  I didn't even realize you weren't a native speaker.  And since I'm not a Blender renderer myself, those aren't issues that directly concern me, or that I could even test (I wouldn't know how).  Thanks for the work you've put in.

**Comment by powroupi** [comment]
> Your English is beautiful. I didn't even realize you weren't a native speaker.

Really? Thank you. :smile: I use google translator and some experiences by reading some english conversations from internet. :)

**Comment by lordscales91** [comment]
> Really? Thank you. :smile: I use google translator and some experiences by reading some english conversations from internet. :)

That's impressive! It really looks like you have a good level of English.

Sorry, I didn't had time to test the `base_texture_folder` property and then I forgot it :sweat: . I hope I will be able to test it by this weekend. Unless I forget it again :smile:

**Comment by powroupi** [comment]
The ik target issue should be solved now. :smile: 
Here is a simple bone structure, say the armature object named **Test_arm**:
- **Root**
  - **link1**
    - **link0** <- add IK constraint, Bone=_**IK bone**_ , Chain Length=2 in this case.
      - **IK target** <- add constraint, named _**'mmd_ik_target_override'**_, Bone=_**link0**_
- **IK bone**

If you want to assign the IK target in blender, you can add a 'Damped Track' constraint to the pose bone ('IK target' in this case) and rename the constraint to 'mmd_ik_target_override', and set Target to the armature object ('Test_arm' in this case) and set Bone to the "ik constraint" bone ('link0' in this case). It is just a pointer for the exporter and does not behave like MMD, so you should mute the constraint.

In general, the IK target should be a child bone of 'link0'. Please correct me if it is not true. 
Thank you. :smile: 

Ps.
- To add IK constraint in 2 ways:
  - Bone constraints -> Add Bone Constraint -> Tracking -> Inverse Kinematics
  - RMB select **IK bone** , then RMB Shift select **link0** , hit `Ctrl+Shift+c`, choose 'Inverse Kinematics'
- To add 'Damped Track' constraint in 2 ways:
  - Bone constraints -> Add Bone Constraint -> Tracking -> Damped Track
  - RMB select **link0** , then RMB Shift select **IK target** , hit `Ctrl+Shift+c`, choose 'Damped Track'
