### ISSUE TITLE
using csv file in a python script

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#120]
Hello @powroupi ! Can you please help me with this? I am trying to understand how to use a csv file in a python script.

The name of this python script is import_csv.py
 In the same directory of import_csv.py is a csv fils named import_csv.csv
 The result of trying to run this python script is a "file not found" error.
 How do I correct this script to find the csv file?

```python
import bpy
import csv


def default_csv_filepath():
	return __file__[:-3]+'.csv'

print(default_csv_filepath())

csv_filepath = default_csv_filepath()
with open(csv_filepath, newline='') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',')
    __jp_to_en_tuples = [tuple(x[:2]) for x in spamreader]

print(__jp_to_en_tuples)
```

**Comment by Hogarth-MMD** [comment]
Hello @powroupi! How are you doing?
Based on my many time-wasting tests, it looks to me that 
```python
__file__
```
  does not work if I am running a script from the Blender text editor. So, do I need to use the os module and tell my script exactly where the .csv file is located? There is no simpler method?

**Comment by powroupi** [comment]
@Hogarth-MMD I'm fine, thank you. If you already know the csv file name, it is recommended to use it directly, like this:
```python
def default_csv_filepath():
    return 'C:\\test_csv\\import_csv.csv'
```
There is a filepath value of [bpy.types.Text](https://docs.blender.org/api/blender_python_api_current/bpy.types.Text.html#bpy.types.Text.filepath), but it is hard to know which text you are running.
```python
import bpy
for txt in bpy.data.texts:
    print(txt.name, txt.filepath)
```

**Comment by Hogarth-MMD** [comment]
This works fine, thank you @powroupi . Closing this issue.
