### ISSUE TITLE
Are bone morphs supported for animation imported into Blender?

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#125]
http://www.mediafire.com/file/8znui1gm3d7n3xv/bonemorphtest.zip has a very boring test model and a copy of the motion for hibikase.  If you load it into MMD, it will bob up and down, interpreting blinks via a bone morph, but not doing anything else.  If you import it into Blender, via current dev_test MMD Tools, then import the motion onto it, it doesn't do anything (doesn't even register any frames).  Is this something unsupported by MMD tools?

The reason I was experimenting with this is because I'm copying transforms from an MMD skeleton (no mesh) onto a dissimilar rig in order to apply MMD animations onto a Blender model and wanted to figure out how I can copy the morph data.  I was expecting these to use drivers, but it doesn't appear that they do.  Are these just naked registrations of the shapekeys?  I would like to use this information with Blender's drivers to drive shapekeys (or other properties) on a different mesh.  Do you have any recommendations on a smart way to go about doing that?  Will it be necessary to create a simple mesh just to get the morph data imported by MMD Tools?

**Comment by powroupi** [comment]
>Is this something unsupported by MMD tools?

Currently, mmd_tools only support vertex morph animation (shape key animation), material/UV/bone/group morphs are supported for editing only.

It is possible to import all key frames of morph animation to shape keys, then use the shape key value to drive other things (ex: #82 bone morphs slider controls).

You can add a new/empty shape key `MyBoneMorph` to import the key frames of bone morph `MyBoneMorph`. To use it, in [driver-variables](https://docs.blender.org/manual/en/dev/animation/drivers/drivers_panel.html#driver-variables), add **[Single Property]**, **[ID-Type]** Key, **[ID]** select your mesh's shape key data, **[RNA Path]** copy data path of the shape key value, ex: key_blocks["MyBoneMorph"].value.

**Comment by nathanvasil** [comment]
Thank you, good to know.  I've created a weird MMD model (another bobbing cube, lol) to hold all morph data as shapekeys and they're transferring just fine ( https://blender.stackexchange.com/questions/42390/how-can-i-set-a-shape-key-value-to-be-a-drivers-variable was useful for this.)

Just as a thought, it might be nice to create placeholder shapekeys on importing a model, perhaps on a dummy placeholder mesh, to simplify creating drivers for any and all morphs.  A single triangle, set not to render, could be used to hold all morph data, regardless of type of morph.  People could then use things like material morphs to drive mix with transparency shaders, for example.

I'll update the wiki regarding this (and other morph types.)
