### ISSUE TITLE
Does not work with blender 2.8

### ISSUE THREAD

**Issue by xxprototypexx32** [powroupi/blender_mmd_tools#127]
Just try, you'll see

**Comment by Hogarth-MMD** [comment]
The most recent version of Blender is 2.79a. The only versions of Blender 2.8 are just WIP experimental/ development builds.
https://www.blender.org/download/

**Comment by powroupi** [comment]
@xxprototypexx32 Thank you for reporting this issue. :smile: I can expect the errors since Blender 2.8 has a lot of changes. I'll make updates after Blender 2.8 stable being released. :yum:

**Comment by xxprototypexx32** [comment]
oh cool, alright then
