### ISSUE TITLE
How does the Bone Morph work？

### ISSUE THREAD

**Issue by lwp513202035** [powroupi/blender_mmd_tools#129]
I use a pmx mmd model transformed from XNALaraXPS, and it is imported into blender(ver.2.79) well , but the character has no facial expression after import a vmd.  And in the Bone Morph I can see some tags like にやり左、真面目, so how do those bone morphs work? If I want to use these bone morph as facial expression, what should i do ?
@powroupi Sorry for my poor English but I really need help.

**Comment by powroupi** [comment]
In `Morph Tools` panel of `mmd_tools` tool shelf, hit the menu->`Bind`, then import vmd with root empty object selected. The bone morph animation should be played. :smile: 

If you want to convert bone morphs to shape keys, you may do the following steps for each bone morph:
1. [View] the bone morph (without binding) or set morph slider value to 1.0 (with binding).
2. Select the mesh object, add new Armature Modifier with the same settings of default Armature Modifier (`mmd_bone_order_override`), mute default Armature Modifier, hit [Apply as Shape Key] of the new Armature Modifier you added. Then new shape key will be created to the mesh object, rename it as you want.
3. remove the bone morph, un-mute default Armature Modifier.

Hope this helps. :smiley: 

PS. my english is bad. :cry:

**Comment by lwp513202035** [comment]
Thanks so much for your help, but where the bind is ? Is it in the Morph Tools panel? I cannot find it. Or in the default Armature Modifier with the bone envelopes checked?@powroupi

**Comment by powroupi** [comment]
>where the bind is ?

You may update your mmd_tools, it is a recently updated feature in the Morph Tools panel. (download [latest dev_test.zip](https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip)) :)

**Comment by lwp513202035** [comment]
https://images2.imgbox.com/54/2c/7XEppGMK_o.png
This picture is what it look like in my blender _(:з」∠)_
Actually I have updated the plugin but i really don't konw where it is _(:з」∠)_
Sorry for bothering you again . @powroupi

**Comment by powroupi** [comment]
It is a menu item of Morph Tools panel, middle of add/remove/up/down buttons. :)

**Comment by lwp513202035** [comment]
What A Fool I am！
But it still doesn't work .Maybe I should  try to convert bone morphs to shape keys.
Thanks  all the time !

**Comment by powroupi** [comment]
You're welcome. :smile: 

>But it still doesn't work

I forgot to say that you may need to enable [Auto Run Python Scripts](https://docs.blender.org/manual/en/dev/preferences/file.html) to use `Bind` feature of Morph Tools. :)

**Comment by lwp513202035** [comment]
>  enable Auto Run Python Scripts 

That is exactlly the reason _(:з」∠)_
Finally it worked.
Thank you so much !

**Comment by DoroMan233** [comment]
when I click the bind button, all my material settings will change：(  
![QQ截图20200103002904](https://user-images.githubusercontent.com/57245933/71678675-ac8b4300-2dc0-11ea-918d-c34b9ff13cd5.png)
![QQ截图20200103002930](https://user-images.githubusercontent.com/57245933/71679084-b497b280-2dc1-11ea-99f3-a701b10d2aca.png)


, how show I deal with this situation？I don't want set the materials once again, it takes me much time

**Comment by HentaiTree** [comment]
![QQ截图20200103002930](https://user-images.githubusercontent.com/57245933/71679056-a053b580-2dc1-11ea-8597-dd7f716f2645.png)
