### ISSUE TITLE
MMD_tools Wont Install

### ISSUE THREAD

**Issue by JEBDevOps** [powroupi/blender_mmd_tools#130]
Each time I try to import it, it wont import or i cant detect the file

**Comment by powroupi** [comment]
Well, here is a summary of similar issues #91, #92, #98, #112:

Make sure you remove old `mmd_tools` folders in [Blender Add-on Directory](https://docs.blender.org/manual/en/dev/getting_started/installing/configuration/directories.html).

To install `mmd_tools` to Blender, you may [unblock your downloaded zip file](https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/) before extracting it.:

1. Extract the zip file you downloaded, copy the **mmd_tools** folder (which is inside `blender_mmd_tools-dev_test` folder) to `[Blender folder][Blender version]\scripts\addons\` (for example, `blender-2.79-windows64\2.79\scripts\addons\mmd_tools\` ).
2. Enable `mmd_tools` in Blender from the [Add-ons tab of the User Preferences](https://docs.blender.org/manual/en/dev/preferences/addons.html) dialog, `mmd_tools` should be in Categories "Object". If you are using search box, make sure Supported Level "Community" and Categories "All" are selected, you can also try [Refresh] button.

If you want to use [Install from File] button to install `mmd_tools`:

1. Extract the zip file you downloaded, zip the **mmd_tools** folder, then install `mmd_tools.zip` you created using [Install from File] button. This way `mmd_tools` will be installed to Blender's user config folder of your system which is not inside your Blender.exe folder, so it is not easy to find.
2. Enable `mmd_tools` as above step 2.

Either way should work fine I think, but first method (copy `mmd_tools` folder) is recommended. :)

**Comment by LuckyMe3124** [comment]
I've tried both. Neither work. NONE of it works. when @powroupi said: Enable mmd_tools as above step 2, it did not show up.

**Comment by powroupi** [comment]
@LuckyMe3124 which blender version are you using? Did you try [unblock your downloaded zip file](https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/) before extracting it? Have you ever successfully install other blender addons? :confused: 

[EDIT] Please check out the [console messages](https://docs.blender.org/manual/en/dev/advanced/command_line/introduction.html#microsoft-windows), and please let me know if there is any error message. Thank you. :)

**Comment by LuckyMe3124** [comment]
Im using 2.79 AND the console said "Modules installed () 'then the destination is here.'."
![capture](https://user-images.githubusercontent.com/25356726/38246067-86352fcc-370e-11e8-8187-ac450ff83cee.PNG)

**Comment by powroupi** [comment]
Could you try the following commands in [Blender Python Console](https://docs.blender.org/manual/en/dev/editors/python_console.html) and show me the messages? :thinking: 
```python
>>> import addon_utils

>>> addon_utils.check('mmd_tools')

>>> addon_utils.enable('mmd_tools')

```
If addon_utils.enable('mmd_tools') success, go to User Preferences to see if `mmd_tools` shows up or not.

**Comment by LuckyMe3124** [comment]
Ok, one sec
I was Busy

**Comment by LuckyMe3124** [comment]
addon not found: 'mmd_tools'

**Comment by LuckyMe3124** [comment]
![capture](https://user-images.githubusercontent.com/25356726/38271667-0c299d5c-3755-11e8-85a2-c2c1c4e33be5.PNG)

**Comment by LuckyMe3124** [comment]
![test](https://user-images.githubusercontent.com/25356726/38271782-5ef447d0-3755-11e8-9f69-f48dfdf2837f.PNG)

**Comment by LuckyMe3124** [comment]
- [ ] Cl

**Comment by LuckyMe3124** [comment]
(This Image Is on My Gaming Pc) ![capture](https://user-images.githubusercontent.com/25356726/38280267-756cf7ec-3772-11e8-990e-36a55b91af4b.PNG)

**Comment by powroupi** [comment]
@LuckyMe3124 What 3rd party addons did you installed? (What addons in the folder `%USERPROFILE%\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\`?)

If you installed `mmd_tools` via `mmd_tools.zip`, you should be able to find the file `%USERPROFILE%\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mmd_tools\__init__.py`

You could try copying `mmd_tools` folder to the addon folder inside blender.exe folder (so you can find the file `[blender.exe folder]\2.79\scripts\addons\mmd_tools\__init__.py`), then start blender and test above commands.

You may also rename (or remove) the folder `%USERPROFILE%\AppData\Roaming\Blender Foundation\Blender\2.79\` or uninstall & reinstall Blender to make sure you have fresh Blender configuration. (or maybe downgrade to old versions, Blender 2.77 for example)

If it still doesn't work, I have no idea what to do. :sob: If it works, you can share how you did. :smile:

**Comment by LuckyMe3124** [comment]
THX SO MUCH! It worked! Thank you for helping me with this.

**Comment by LuckyMe3124** [comment]
![capture](https://user-images.githubusercontent.com/25356726/38305191-f32b7a84-37d9-11e8-9c85-787c75eb5db1.PNG)
