### ISSUE TITLE
A sugestion on handling UV morphs

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#131]
I've talked with powroupi before regarding UV morphs.  UV morphs are one of the few remaining ways that mmd_tools doesn't support clean import/export passes.  Previously, I felt that the proper way to handle this was via add UV maps.  Powroupi's problems with this were that, a) add UV couldn't cleanly represent z or w components of UV morphs; b) slots for add UV were limited and could be exhausted by a model with a large number of UV morphs.

A different way of handling this would be via the automatic generation of modifiers and vertex groups on imported models.  For every UV morph, four non-deforming vertex groups could be generated automatically: [morphName].mmdUVmorph.x, .y, .z, and .w, the strength of each equal to the .pmx strength of the UV morph.  Two UV warp modifiers could be generated, each of which used the relative position of a single empty to the base MMD model empty, limited by the appropriate X and Y vertex groups, mapping to XZ and ZY respectively.  When the empty controlling the morph was moved to (1,1),  it would apply 1,1 * morph strength.xy to the UV of each vertex.

For clarity, convenience, and exports, it would be best if it used a new modifier type, something like MMD UV Morph, which would just be the combination of two UV warp modifiers.  That would reduce the potential size of the modifier stack and give the export script a name for export of .z and .w vertex groups to export with any given UV morph.

.pmx UV morphs aren't actually clamped to the 0,1 range, although Blender's vertex groups are.  If a solution to this is desired, the MMD UV Morph modifier could include a scaling value that transformed the 0,1 range of the empty determining the morph strength to a different range.  You could determine this scale on a per-morph basis for full compatibility, but using a -2.0 to +2.0 range instead of a 0 to 1 range would handle all reasonably conceivable use cases.

For editing purposes, it would probably be best to leave all morphs on all objects even through a separate-by-materials action-- otherwise, people separating and rejoining materials would probably become frustrated by the loss of UV morphs though their editing passes.

The actual automatic generation of the empty to control the morph wouldn't be necessary for improving the import/export functions, but would provide a way to keyframe UV morphs from .vmd imports for those animating in Blender.

I'm no longer working with MMD, and this isn't necessary to anything I'm doing-- I'm just offering it in case this has been a problem that's been bugging anyone :)  I'm closing this issue as soon as I open it.

**Comment by powroupi** [comment]
Thanks for the sugestion. :smile:

UV warp modifier is a good way to animate UV morphs in Blender, but currently I'm not sure if I can handle UV morphs correctly with UV warp modifier, the conversion could be more complex than I thought. :thinking: 

Recently, morph sliders have been implemented, all morph keyframes can be imported, you could use morph slider value to drive UV/Material morph by your way. (bone morph is supported already) :)

**Comment by nathanvasil** [comment]
Would you like for me to make a demo file demonstrating what I'm recommending?  I could do that, for a simple UV morph.  Part of what would be nice about getting this implemented via mmd_tools would be that, for complicated UV morphs, creating them could involve complicated vertex group assignments that would be hard to generate manually.  But I could rig up a simple 4-way texture morph (since it's just flat vertex group assignments, generally on a per-material basis.)

**Comment by nathanvasil** [comment]
@powroupi Okay, here's a demo: http://www.mediafire.com/file/q3s30f43rf51uj3/uvmorphdemo.blend

I think I have this right, but maybe I screwed something up-- it's a little complicated to set up manually, one of the reasons it would be a good thing to automate.

Linked file has two UV morphs.  To run the morphs, grab the control bones off to the side and move them in the global Z axis.  0-1 Z corresponds to anticipated 0-1 morph value.  Haven't checked out the latest build and how you're handling morph sliders (cool though!), but this should be easily driven by however you're handling that.

Drivers translate the positions of these control bones into movement of empties along the X axis, which is then used to drive a series of UV warp modifiers.  This doesn't have to be done with empties, it could be done with bones or whatever you want.  Each UV morph is associated with 3 empties: one to measure base position, one to drive positive U/V, and one to drive negative U/V.

Each UV morph gets turned into 4 modifiers and 8 vertex groups.  Vertex groups are positiveU, negativeU, positiveV, negativeV, positiveW, negativeW, positiveZ, negativeZ.  Z and W components are ignored by Blender and used only for export to .pmx.  The values of these vertex groups are just the UV morphs' component values; negative values clamped to (-1,0) and positive values clamped to (0,1).  (Hence, (-1,1) range in total.)

4 modifiers translate position of empties, modulated by vertex groups, into U and V translation.  Modifiers' names are appended with the interpreted domain of the UV morph for export.  In attached, that's just -1,1.

To allow for further scaling of UV morphs to accommodate values outside of that range, you divide the vertex group weights and multiply the driven position of the empties, and then change the name of the modifiers so that your export function can correct for this.  You could scale all UV morphs by something uniform to allow for a large range, or you could scale on the basis of the largest translation of that particular morph for improved precision.

Ideally, such a system would collapse the four modifiers into a single modifier, with domain information contained in something other than that modifier's name.  Even more ideally, this modifier would allow export to / import from addUV for more intuitive editing of UV morphs.

Z and W are basically never going to be used, and negative values used only rarely.  For reduced clutter, it might be preferable to only generate meaningful vertex groups.

**Comment by Hogarth-MMD** [comment]
Here is my incompleted code for implementing UV morph slider controls:
https://github.com/powroupi/blender_mmd_tools/issues/108

With my method, possibly 16,000 drivers would be needed for 11 UV morphs. With the method suggested my @nathanvasil , I guess that you would need 44 UV warp modifiers, 44 drivers, and 44 vertex groups for 11 UV morphs.

**Comment by nathanvasil** [comment]
@Hogarth-MMD Well, it depends.  While I don't know enough about coding for Blender to say with any certainty, I figured that a single new modifier that's just 4 existing modifiers bundled together wouldn't be too hard to create.

If I'm wrong about that, it would be possible to be "smart" about the creation of modifiers.  Nearly all actual UV morphs for MMD models are simple texture switches, shifts in a single cardinal axis and in a single direction.  It would only take a single modifier to represent that, even for export, even in this framework that would support any arbitrary UV morph.

But I'm still talking about at least one modifier per UV morph, no matter how it might get handled.

**Comment by powroupi** [comment]
@nathanvasil Thanks for your demo file, I'll try to see if I can make any automation. :smile:

**Comment by Hogarth-MMD** [comment]
"Nearly all actual UV morphs for MMD models are simple texture switches, shifts in a single cardinal axis and in a single direction. "

In that case, I think it could be implemented simply as a driven texture animation.

**Comment by Hogarth-MMD** [comment]
Implementing UV morphs in Blender can be difficult without cluttering up the interface. To avoid that problem, maybe bpy.app.handlers (Blender event handlers) could be used instead of drivers. The animation nodes add-on uses bpy.app.handlers.  I'm not volunteering to do that programming though. I think that it ends up being powroupi's choice how to do the implementation.

**Comment by Hogarth-MMD** [comment]
Maybe UV morphs could be best implemented by a blending of 2 UV maps and using bpy.app.handlers . No drivers or UV warp modifiers or vertex groups would be needed.

**Comment by powroupi** [comment]
Okay, now vertex groups are used to store UV morph offset data, I think this way is more reliable, you can edit UV morphs via Morph Tools panel as usual (click [View] to create temporary UV map, [Edit] temporary UV map via Blender UV Editor, then [Apply] selected vertices' UV offset, [Clear] temporary UV map). And I also use @nathanvasil's trick to support UV morph sliders, that's the best (easiest) way to support PMX UV morphs I think. :smile: 

PS. UV morph vertex group name is in the form of **UV_[morph name][axis]**, _axis_ is one of {'+X', '-X', '+Y', '-Y', '+Z', '-Z', '+W', '-W'}

**Comment by nathanvasil** [comment]
Thanks, that's cool.  Tested out import/export on a simple morph, working great (which is pretty nice, I ended up remaking that morph a hundred times with a bunch of last-minute changes to the model).

Doesn't look like it's set up for animation in Blender.  Is that intentional?  I think the way you have it set up now is wise, since anybody can create the UV warp modifiers for anything they need, pretty brainlessly and without too much trouble, and that way you don't have tons of modifier stack spam.  If this is how you want it working, I'll adjust the wiki to explain how to get UV morphs for Blender rendering.

Speaking of the wiki, is there some way I can see a recent change log?  I have a feeling that there are some other issues that have been resolved where I ought to update the wiki to reflect the current version.

**Comment by powroupi** [comment]
>Doesn't look like it's set up for animation in Blender.

It is animatable after binding to morph sliders (Morph Tools panel->Menu item->[Bind] or [Unbind]). The buttons (View/Edit/Apply/Clear) are just for editing vertex groups of UV morph data. When binding, it will set up UV Warp modifiers and control bones so that you can animate it by morph sliders. :)

You can animate UV morph (as well as Bone/Vertex/Group morphs) now, they are driven by morph sliders which are the shape keys of `.placeholder` mesh object, and you can import/export shape key animation of `.placeholder` mesh object. :smile: 

>Speaking of the wiki, is there some way I can see a recent change log?

Yes, currently there is `nathanvasil edited this page on 20 Mar · 15 revisions` on `Documentation` page, click [15 revisions](https://github.com/powroupi/blender_mmd_tools/wiki/Documentation/_history) to see the change log, and here is full change log [https://github.com/powroupi/blender_mmd_tools/wiki/_history](https://github.com/powroupi/blender_mmd_tools/wiki/_history). :smile:

**Comment by Hogarth-MMD** [comment]
I am not succeeding in finding this new feature yet. I don't see any morph slider controls. I don't see any bind/unbind button. This is a nice little treasure hunt sent to me by @powroupi . Maybe I need to have the instructions which were written for small children, with lots of pictures.

**Comment by powroupi** [comment]
@Hogarth-MMD It is below [add][remove] buttons and above [up][down] buttons in Morph Tools panel, there is a [Specials Menu](https://docs.blender.org/manual/en/dev/interface/controls/buttons/menus.html#specials-menu), left mouse click to show a list of menu functions. I've added some functions into menu items just like [List View](https://docs.blender.org/manual/en/dev/interface/controls/templates/list_presets.html#ui-list-view). :smile:

**Comment by Hogarth-MMD** [comment]
Hello @powroupi ! I have not finished testing this new feature, but it seems to be an excellent and successful implementation of bone, UV and group morphs in Blender. Congratulations! How are you able to implement group morphs? Previously I was thinking about the problem of group morphs and it seemed to me that this is impossible. I thought that the individual morphs which are controlled by the group morphs slider controls cannot also be moved independently of the group morph slider controls. How were you able to solve this programming challenge?

**Comment by powroupi** [comment]
>How are you able to implement group morphs?

I simply add the influence of group morph to the individual morphs. If a vertex morph `V` which is also in a group morph `G` with factor 0.5, the final influence of vertex morph `V` will be **V.value + G.value*0.5**, that is the Driver expression of the value of shape key `V`. :smile:

**Comment by Hogarth-MMD** [comment]
Hello @powroupi! I cannot fully test UV morphs without material morphs. In some models, a material needs to be made visible using a material morph before its UV morph will be visible. Are you feeling ambitious and energetic enough to implement material alpha morphs in mmd_tools? This would be an excellent feature.

**Comment by powroupi** [comment]
@Hogarth-MMD  I believe there are several ways to implement PMX material morphs in Blender using material nodes of Blender Internal Renderer. (I haven't found a good way yet, though) For now, you could just change material alpha manually to test those UV morphs you mentioned. :smiley:
