### ISSUE TITLE
Suggestion: Compress the two sidebar panels into one

### ISSUE THREAD

**Issue by Darkblader24** [powroupi/blender_mmd_tools#132]
If you have a lot of addons installed like me, mmd_tools is taking a lot of that sidebar space: https://i.imgur.com/00ArqaP.png

So it would be nice if you could combine both panels "mmd_tools" and "mmd_utils" into one "mmd_tools" panel. Calling it "MMD" would preserve even more space.

Thanks for your awesome work!

**Comment by powroupi** [comment]
Thanks for your suggestion, I've made the updates. :smile:
