### ISSUE TITLE
Kaito model who does not dance correctly in Blender

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#133]
Here is a Kaito model who does not dance correctly in Blender:

 PDAFT Half Spats Kaito
https://sta.sh/013lox9q5nyc

The problem may be caused by the presence of several extra leg/foot bones which are not normally part of an MMD armature. This Kaito model does seem to dance fine in MMD though.  A few deviantart users have reported this issue to me, and so I am passing this on as a bug report.

**Comment by Hogarth-MMD** [comment]
This Kaito model has some clever rigging on its legs. It has both leg IK and leg FK at the same time. I don't understand why this rig works in MMD, but not in Blender. To me it looks like this is happening because the rigger was too clever, not because he was an incompetent rigger.

**Comment by powroupi** [comment]
The model has 4 center bone, remove redundant bones (センター.001, センター.002, センター.003) should solve some motion issues. :)

The leg IK looks fine to me, I don't see any problem. :confused: 

[EDIT] Note that, in some cases, you may need to disable IK manually in Blender, VMD importer does not support MMD's property animation yet.

**Comment by Hogarth-MMD** [comment]
"VMD importer does not support MMD's property animation yet."

Sorry, I don't understand what this means, "property animation".

"Note that, in some cases, you may need to disable IK manually in Blender,"

Sorry, I don't understand this, either. Normally, VMD files animate leg and foot IK bones, so the animation won't work with IK disabled.

**Comment by nagadomi** [comment]
>Sorry, I don't understand this, either. Normally, VMD files animate leg and foot IK bones, so the animation won't work with IK disabled.

MMD can register IK ON/OFF state on keyframe. Several motions use that function.
e.g. http://www.nicovideo.jp/watch/sm27162069, motion from the video: http://t.co/mfgUWJOPji
The above motion does not work properly with mmd_tools. Registering the mute state of bone constraints may work.

**Comment by Hogarth-MMD** [comment]
Thank you for the model fix bug fix @powroupi . I have passed that information on to the deviantart users who were asking me for help. And thank you for that information @nagadomi .

**Comment by powroupi** [comment]
VMD importer/exporter support MMD's property animation now. You might try latest `mmd_tools`. :)

Model display is controlled by root object's `mmd_root.show_meshes` property.
IK ON/OFF state is controlled by IK bone's `pose_bone.mmd_ik_toggle`. It will update influence of IK constraint which is using the IK bone when the IK bone's `pose_bone.mmd_ik_toggle` being changed.

**Comment by nagadomi** [comment]
gj!

>VMD importer/exporter support MMD's property animation now.

The following topic is about extensions, so this is just a report.

I sometimes scale motion to 60fps. It can be applied by `s, x, 2`  key on Dope Sheet. This may cause problems with camera motion.
In MMD, when switching the location of the camera (like Constant Interpolation in Blender), register keyframes to contiguous frames.
With simple keyframe scaling, a breakdown frame is generated and the movement path of the camera is interpolated with bezier. So, the motion switching the camera location will be unintended.

The idea I'm currently thinking is to use Constant Interpolation for the previous keyframe if keyframes for the location are contiguous. 
I think it is useful to have this option.

**Comment by powroupi** [comment]
@nagadomi, thank you for the report, you can modify [vmd.importer#L331](https://github.com/powroupi/blender_mmd_tools/blob/8750b647814a916bd49b7840165f564fdc020229/mmd_tools/core/vmd/importer.py#L331) locally for now. :smile: ([vmd/importer.py#L316](https://github.com/powroupi/blender_mmd_tools/blob/8750b647814a916bd49b7840165f564fdc020229/mmd_tools/core/vmd/importer.py#L316) might be a better place to detect camera switching :thinking: ) 
```python
        for fcurve in fcurves:
            self.__fixFcurveHandles(fcurve)
            if fcurve.data_path == 'rotation_euler':
                self.detectCameraChange(fcurve)
            elif fcurve.data_path == 'location': # add code here
                self.detectCameraChange(fcurve, threshold=0)
```

**Comment by nagadomi** [comment]
@powroupi oh, I did not realize that the function exists. I will check it. Thanks. :smile:
