### ISSUE TITLE
Bug: Error when importing second model while in edit mode

### ISSUE THREAD

**Issue by Darkblader24** [powroupi/blender_mmd_tools#135]
You get this error when you import a model while in edit mode: https://i.imgur.com/w5FvFdr.png

How to recreate:
- Import a model
- Select the armature
- Go into edit mode and select a random bone
- Import a second model

Thank you!

**Comment by powroupi** [comment]
Thank you for reporting this issue, I've fixed it. :smile:

If no further issues, it can be closed now. :)

**Comment by Darkblader24** [comment]
Thanks, it works! :)
