### ISSUE TITLE
Physics isn't work after importing PMX file.

### ISSUE THREAD

**Issue by marty1885** [powroupi/blender_mmd_tools#136]
Hi! 
I found that physics simulation seems isn't working on the `dev_test` branch. For example, the model hair is floating in mid air at frame 0 and doesn't seem to drop down in later frames.
![Physics not working](https://i.imgur.com/MMLDNJF.png)

Where the hair should drop down like so. (Imported using `mmd_tools` from the master branch)
![Physics working](https://i.imgur.com/RIq0BId.png)

This happens to all PMX model I have (PMD not tested, I don't have one), and I sure that I turned physics on when I imported the models - as physics is on by default and I double checked the button is pressied.
Is this a bug or its my stupidity?

Tested on Blender 2.79.

**Comment by powroupi** [comment]
Thank you for reporting this issue. It looks like you didn't build the model's physics when using `dev_test` branch.

In `mmd_tools` Tool Shelf Panel (`MMD` panel now), press `[Build]/[Clean]` button under `Physics` label to build/clean the model's physics. When importing a model, it is not built by default.

And you may want to change import option `Scale` from `1.0` to `0.2` to get the same model size as usual. If you import a model with scale `1.0`, you may adjust Blender's [gravity](https://docs.blender.org/manual/en/dev/physics/gravity.html) to get better physics result. :smiley:
