### ISSUE TITLE
Readme.md links

### ISSUE THREAD

**Issue by stefnotch** [powroupi/blender_mmd_tools#14]
The links in the readme file still point to the abandoned project.

Also, amazing project! +1

**Comment by powroupi** [comment]
Sorry for not updating readme file and documents!

I update the branch [dev_test](https://github.com/powroupi/blender_mmd_tools/tree/dev_test) that is more like for sharing my changes which may be useful for other developers (even users). So i just changed the code and keep other files as usual. :)

Thank you, and thanks @sugiany for creating this amazing project! :smile:

**Comment by stefnotch** [comment]
https://github.com/powroupi/blender_mmd_tools/pull/15

**Comment by stefnotch** [comment]
Apparently there are already some translations for the readme file out there: https://github.com/powroupi/blender_mmd_tools/network

e.g.
https://github.com/nakata0705/blender_mmd_tools/commit/01842ade81f1e07adaa4ef11e2565b7a25da9427

**Comment by powroupi** [comment]
Yeah, so you could merge it and make some proper modifications. (nakata0705@01842ad, pikangie@0c310f5) And we can add new stuff from now on. :)
