### ISSUE TITLE
python wildcard pattern matching with lists?

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#141]
Python question:

How to do python wildcard pattern-matching with lists?
With strings, there is regular expressions for this, but how to do it with lists?

This is what I am trying to do, for example:

[arm_L, elbow_L, wrist_L]
Arm bones matching this parent-child pattern are identified as standard MMD arm bones.
[arm_L, *, elbow_L, *, wrist_L]
Arm bones matching this parent-child pattern are identified as MMD arm bones with arm twist bones.

**Comment by powroupi** [comment]
I think Python doesn't have built-in package to do that, however, you could join bone names and use [regular expressions](https://docs.python.org/3/library/re.html) to identify it. For example: :smiley: 
```python
import re
import bpy

list_names = ','.join(b.name for b in bpy.context.active_object.pose.bones)
re.search('arm_L.*elbow_L.*wrist_L', list_names)
```

**Comment by Hogarth-MMD** [comment]
Thank you for sharing that interesting technique, @powroupi . I'm not sure if that would work as a general technique. If a bone chain has names like upper_body, and upper_body2, or wrist and wrist_sleeve and b_wrist, for example, It seems like that technique would get fouled up, because it doesn't adequately detect where each bone name begins and ends.

**Comment by Hogarth-MMD** [comment]
Maybe a technique based on iterating through possible list slices?

**Comment by Hogarth-MMD** [comment]
Using bpy.context.active_object.pose.bones.keys() wouldn't work adequately, I don't think, because of situations in which a bone has more than one child bone, splitting a bone chain into more than one bone chain.

**Comment by Hogarth-MMD** [comment]
Okay, I'll just use a less sophisticated method, then.
