### ISSUE TITLE
Convert Model material alpha

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#143]
This issue happens frequently when converting models to MMD with the Convert Model operator. A material's alpha value is set to zero, but the alpha value of its texture image is set to 1.0. When the model is exported from Blender to .pmx with mmd_tools, these materials and their textures are invisible. The makers of these models apparently have the idea that they want the material colors to be invisible and to have no influence, and they want all of the rendering colors to be coming from the texture images.

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: Because the Convert Model operator simply copy material's alpha to mmd_material.alpha, it may have this issue. I need some samples to find a way to fix this issue, I'm not sure if those materials have something in common. :cry:

**Comment by Hogarth-MMD** [comment]
The Makehuman model uploaded by s-a has this issue:
https://drive.google.com/drive/folders/13z4wpSKMEfvN8a2RjGTCAHvrkNYZBQOr?usp=sharing

**Comment by Hogarth-MMD** [comment]
On second thought, this may be more an issue of pmx export, rather than a "Convert Model" issue. This is a simple issue. Just set a material's alpha value to zero and its diffuse texture alpha enabled and value 1.0.
The material will be visible in Blender, invisible in MMD.

**Comment by powroupi** [comment]
Okay, I've fix some material issues in commit af673da, I guess #139 is also related to these problems.

You can close the issue if you don't find any further issues, or provide samples to help me fix it. Thank you. :smile:

**Comment by Hogarth-MMD** [comment]
Thanks! When testing this bug fix, I tried to edit the alpha value in the normal Blender way, but that was ineffective. The mmd_tools custom property alpha slider must be used.
