### ISSUE TITLE
editing the mmd_tools wiki?

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#144]
I just made a short tutorial with a tutorial image. mmd_tools needs better tutorial information, including tutorial images. How can I add this tutorial information and tutorial image into the mmd_tools wiki, or how can I otherwise share it with other people?

https://sta.sh/02bu5tp894ll

Mmd Tools Shared Toon Texture Folder

When you install mmd_tools (powroupi fork) Blender add-on, you need to set the "Shared Toon Texture Folder" to the Data folder of MikuMikuDance, where the default 10 MMD toon texture images are located. Then click "Save User Settings" If you don't do that, an imported MMD model may appear purple in Blender.

![mmd_tools shared toon texture folder](https://user-images.githubusercontent.com/10057979/40235773-491f8040-5a79-11e8-9308-76ffae514e90.jpg)

**Comment by Hogarth-MMD** [comment]
I can see new page buttons and edit buttons in the wiki. I don't see any tutorials pages or any page with links to tutorials.

**Comment by nagadomi** [comment]
Github wiki does not support image uploading, but you can post images in the following steps.

1. Open the github issue and drag and drop the image. (You do not need to post the issue)
2. Then you can get the URL of the uploaded image. (e.g. `https://user-images.githubusercontent.com/*.png`)
3. Click the image icon in edit mode of wiki and input that URL.

>I can see new page buttons and edit buttons in the wiki. I don't see any tutorials pages or any page with links to tutorials.

All wiki pages are available from the right sidebar.
![ef402eb30fa3b7e3352d96968339d64c](https://user-images.githubusercontent.com/287255/40240579-c918ff40-5af3-11e8-9f20-a936339f7bf4.png)

About Github wiki and Markdown, the following pages should be helpful.
[About Github Wiki](https://help.github.com/articles/about-github-wikis/)
[Mastering Markdown](https://guides.github.com/features/mastering-markdown/)

**Comment by Hogarth-MMD** [comment]
Thank you this excellent workaround information about adding images into the Wiki, @nagadomi .    If @powroupi will create the basic Wiki organization for adding tutorials, I will go ahead and submit the first Wiki tutorial with an image.

**Comment by powroupi** [comment]
@Hogarth-MMD Feel free to create **[New Page]**, we can edit [Home] page or [Add a custom sidebar] in the future. :smile:

**Comment by Hogarth-MMD** [comment]
Okay, done!  :+1:  I don't know how to edit the sidebar, so I did nothing with the sidebar.

**Comment by Hogarth-MMD** [comment]
If I edit the Wiki does @powroupi receive automatic notification of this? Or do I need to announce this in a comment?  "Hello @powroupi , I just made a wiki edit!"

Is there any protection against someone making a malicious wiki edit? This malicious edit can be reversed, I hope?

**Comment by powroupi** [comment]
@Hogarth-MMD  Nice job, it's a good start. :+1:

>If I edit the Wiki does @powroupi receive automatic notification of this?

Yes, I receive automatic notification of wiki changes/activities.

>Is there any protection against someone making a malicious wiki edit?

I guess I can clone wiki locally, revert changes, and push back to online wiki. (never tried) :yum:

**Comment by Hogarth-MMD** [comment]
For making a tutorial, it would be convenient to make an image screen capture of only one Blender  panel, or only one small rectangle area of Blender. Does anyone know how to do that?

**Comment by Darkblader24** [comment]
@Hogarth-MMD Yup, take a look at ShareX in Steam, it's an awesome piece of software!

**Comment by Darkblader24** [comment]
But only if you want to do short gifs or videos. Full lenght tutorials are better made with some recording software.

**Comment by Hogarth-MMD** [comment]
Hello @powroupi ! I want to update my tutorial about mmd_tools translation and add it into the mmd_tools wiki. Previously I told people that the translations.csv file must not be renamed. 
How should this instruction be amended?
Previously I told people that they should copy the translations.csv file into the same folder with translations.py
How should this instruction be amended?

**Comment by powroupi** [comment]
>Previously I told people that the translations.csv file must not be renamed. How should this instruction be amended?

I'm not sure. User can rename it as he/she want if using latest `mmd_tools` (`dev_test` branch), he/she can also create multiple CSV files for different model types.

>Previously I told people that they should copy the translations.csv file into the same folder with translations.py. How should this instruction be amended?

It is the default folder, they have to configure `mmd_tools` addon preferences to change the folder.

**Comment by Hogarth-MMD** [comment]
Is mmd_tools able to translate more than one model at a time, or only the active model?
What about loading .csv dictionaries into Blender's text editor? Is that still an option?

**Comment by Hogarth-MMD** [comment]
Wow @powroupi has been making major changes to the translation feature! Now I need to do a complete re-write of my instructions.

What are MMD names? What are Blender names?
What about support for text encodings of the dictionary .csv file?
utf-8, utf-16 (aka UCS-2), Shift-JIS, euc-jp ?

**Comment by powroupi** [comment]
@Hogarth-MMD `mmd_tools` will only translate the active model. Loading .csv dictionaries into Blender's text editor is still an option just in case `mmd_tools` fails to read the files.

>What are MMD names? What are Blender names?

MMD names => translate MMD `name_j` to MMD `name_e`
Blender names => translate Blender name to Blender name
I'm still thinking of this feature, I think it might be better to be able to select source and target. :thinking: 

>What about support for text encodings of the dictionary .csv file?

I'm not sure if there is any other encodings supported by Blender's text editor, so currently UTF-8 only.

**Comment by Hogarth-MMD** [comment]
Several mmd_tools tutorials are now in the mmd_tools wiki.

Links to mmd_tools Tutorials

How to install the mmd_tools Blender add-on
https://github.com/powroupi/blender_mmd_tools/wiki/How-to-install-the-mmd_tools-Blender-add-on

MMD Tools Shared Toon Texture Folder
https://github.com/powroupi/blender_mmd_tools/wiki/Mmd-Tools-Shared-Toon-Texture-Folder

MMD Tools List of Features (with brief tutorial information for each feature)
https://github.com/powroupi/blender_mmd_tools/wiki/MMD_TOOLS-LIST-OF-FEATURES-AND-BRIEF-TUTORIAL-INFORMATION-FOR-FEATURES

Tutorial: How to convert BVH to VMD
https://github.com/powroupi/blender_mmd_tools/wiki/Tutorial:-How-to-convert-BVH-to-VMD

1 MMD unit in real world units
https://github.com/powroupi/blender_mmd_tools/wiki/1-MMD-unit-in-real-world-units

Tutorial: How to convert a 3D character model to MMD (using mmd_tools (powroupi fork) Blender add-on and mmd_tools_helper Blender add-on)
https://github.com/powroupi/blender_mmd_tools/wiki/Tutorial:-How-to-convert-a-3D-character-model-to-MMD

Tutorial: mmd_tools model translation feature https://github.com/powroupi/blender_mmd_tools/wiki/Tutorial-mmd_tools-model-translation-feature

**Comment by Hogarth-MMD** [comment]
https://github.com/powroupi/blender_mmd_tools/wiki/Guide-to-the-mmd_tools-Interface

My new wiki guide to the mmd_tools interface. So far it is images only, no text added to it yet.

**Comment by Hogarth-MMD** [comment]
Guide to the mmd_tools Interface
https://github.com/powroupi/blender_mmd_tools/wiki/Guide-to-the-mmd_tools-Interface

Okay, I just added a few more images to this mmd_tools Interface guide and text captions for all the images.

**Comment by nathanvasil** [comment]
You're awesome, thanks Hogarth.

**Comment by Hogarth-MMD** [comment]
New Wiki tutorial:

How to create and edit Material morphs, Group morphs, Bone morphs, UV morphs
https://github.com/powroupi/blender_mmd_tools/wiki/How-to-create-and-edit-Material-morphs,-Group-morphs,-Bone-morphs,-UV-morphs

(The tutorial information about editing UV morphs is not finished yet.  
Also to do: Adding images to this tutorial.)

**Comment by Hogarth-MMD** [comment]
Okay, this tutorial is finished, except for the text only aspect.

How to create and edit Material morphs, Group morphs, Bone morphs, UV morphs
https://github.com/powroupi/blender_mmd_tools/wiki/How-to-create-and-edit-Material-morphs,-Group-morphs,-Bone-morphs,-UV-morphs
