### ISSUE TITLE
mmd_tools list of features

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#145]
mmd_tools Blender add-on (powroupi fork) list of features:

CATEGORIES OF FEATURES OF MMD_TOOLS (POWROUPI FORK):

1. WHICH FILE FORMATS CAN BE IMPORTED AND EXPORTED BY NND_TOOLS
2. MMD_TOOLS PRESERVATION OF MODEL DATA WHEN IMPORTING AND EXPORTING
3. MMD_TOOLS MODEL EDITING FEATURES
4. MMD_TOOLS MODEL SCALING/RESIZING FEATURES
5. MMD_TOOLS MODEL DISPLAY AND RENDERING FEATURES
6. MMD_TOOLS MODEL ANIMATION FEATURES
7. MMD_TOOLS MODEL CREATION AND CONVERSION FEATURES
8. MMD_TOOLS MODEL AUTOMATIC ERROR CORRECTION FEATURES
9. MMD_TOOLS CAMERA FEATURES
10. MMD_TOOLS SUPPORT FOR EDITING, POSING OR ANIMATING ADVANCED MORPHS (MATERIAL MORPHS, BONE POSE MORPHS, UV MORPHS, GROUP MORPHS)
11. MMD_TOOLS MODEL JAPANESE TO ENGLISH TRANSLATION FEATURES

1. WHICH FILE FORMATS CAN BE IMPORTED AND EXPORTED BY NND_TOOLS

imports: pmx, pmd, vmd, vpd - Yes
exports: pmx, vmd, vpd - Yes
imports, exports mqo - No
exports pmd - No

Ability to import .vmd morphs animation. Yes.
Ability to import .vmd bones animation. Yes.
Ability to import .vmd camera animation. Yes.
Ability to import .vmd lamp animation. Yes.
(To import a .vmd animation onto the active object, select File, Import, MikuMikuDance Motion(.vmd). If the the root/empty object of an MMD model is selected to be the active object, the .vmd animation will be imported onto all objects of the MMD model.  When importing a .vmd camera animation, the active object can be either the Blender camera or its "MMD camera" empty object. If the Blender camera has no "MMD camera" empty object, an "MMD camera" empty object will automatically be created when you import the .vmd animation onto it.)

Ability to export .vmd morphs animation. Yes.
Ability to export .vmd bones animation. Yes.
Ability to export .vmd camera animation. Yes.
Ability to export .vmd lamp animation. Yes.
(To export a .vmd animation from the active model, select File, Export, MikuMikuDance Motion(.vmd). If the root/empty object of an MMD model is selected to be the active object, all animations of the MMD model, both bones animation and morphs animation, will be exported to .vmd. When exporting a .vmd camera animation, the active object can be either the Blender camera or its "MMD camera" empty object.)

Import of VMD interpolation curves. Yes.
Export of VMD interpolation curves. No.

Import of .vpd files Yes.
Export of .vpd files Yes.

2. MMD_TOOLS PRESERVATION OF MODEL DATA WHEN IMPORTING AND EXPORTING

Dual/bilingual naming of PMD and PMX bones and PMX materials is preserved and will be re-exported when a previously imported PMX or PMD model is exported from Blender - Yes

Dual/bilingual naming of shape keys(morphs) is preserved and will be re-exported when a previously imported PMX or PMD model is exported from Blender - Yes (with "Morph Tools" panel)

Ability to import SDEF to, and export SDEF from, Blender. Blender does not support SDEF, but an imported pmx model's SDEF data is stored in 3 shape keys.

Ability to import and re-export physics objects correctly. Yes.

3. MMD_TOOLS MODEL EDITING FEATURES

Imported shape keys can be edited, renamed, re-ordered and then re-exported from Blender with their data intact - Yes (with "Morph Tools" panel)

New shape keys can be added onto an MMD model - Yes
(After you create a new shape key for a mesh object, you need to add its name to the list of Vertex Morphs in the "Morph Tools" panel, if you want to export it from Blender.)

Separate a model's mesh into multiple meshes, one mesh for each material - Yes
([Separate by Materials] button. The [Join Meshes] button reverses the [Separate by Materials] operation. The Meshes Sorter panel keeps track of the order of the  Materials/Meshes during these operations. You can however edit the order of Materials of a mesh object in the normal Blender way. The Materials Sorter is only needed when using older versions of Blender.)

Editing materials of a model for export to PMX - Yes
(You cannot do the material editing in the usual Blender way, though. You need to edit the mmd_tools custom properties of a material, which are located under the Material tab of Blender's Properties Window (MMD Material panel and MMD Texture panel). When you edit the mmd_tools custom properties, the related Blender properties will automatically be updated. When you edit the Blender properties, however, the related mmd_tools PMX custom properties will NOT be automatically updated.)

Viewing and editing of the PMX MMD properties of a bone - Yes
(MMD bone properties of the active bone can be viewed and edited under the Bone tab of the Properties Window in the MMD Bone Tools panel. When you edit the mmd_tools custom properties, the related Blender properties will automatically be updated. When you edit the Blender properties, however, the related mmd_tools PMX custom properties will NOT be automatically updated.)

Viewing and editing of the MMD properties of a Rigid Body or a Constraint - Yes
(Select the name of a Rigid Body or a Joint in the Rigid Body or Constraint panel of the mmd_tools panel. The MMD properties of that Rigid Body or Joint will then appear under the Object tab of the Properties Window. When you edit the mmd_tools custom properties, the related Blender properties will automatically be updated. When you edit the Blender properties, however, the related mmd_tools PMX custom properties will NOT be automatically updated.)

Adding and editing physics rigid bodies and joints - Yes
(Using the Rigid Bodies panel and Joints panel of mmd_tools. With a Rigid Body selected, its settings can be viewed and edited under the Object tab of Blender's Properties Window, in the [MMD Rigid Body] panel. With a Joint selected, its settings can be viewed and edited under the Object tab of Blender's Properties Window, in the [MMD Joint] panel.)

4. MMD_TOOLS MODEL SCALING/RESIZING FEATURES

Resizing a pmd or pmx model after importing it into Blender:
You need to do that manually. Scale the root empty object, with "Individual Origins" as the center of scaling. Then apply the scale: Select Object, Apply, Scale.

Resizing a model when converting it to MMD:
You need to do that manually. Before clicking on the Convert Model button scale the armature, in Object mode, with "Individual Origins" as the center of scaling. Then apply the scale: Select Object, Apply, Scale.

Resizing a model when exporting it to PMX:
(You can set a value for the Scale export option.)

Resizing a pmd or pmx model when importing it into Blender:
(You can set a value for the Scale import option.)

You can choose a model's scale when creating it:
(Click [Create Model] button. You can set a Scale value in the dialog box which appears.)

5. MMD_TOOLS MODEL DISPLAY AND RENDERING FEATURES

Correct display of an MMD model's ambient color in Blender - No (crudely approximate)
Correct display of an MMD model's toon textures in Blender - No
Correct display of an MMD model's sphere textures in Blender - Yes (except "subtract blend" type)
Ability to use .fx effects in Blender. No.
Cloning of the MMD render engine into Blender's node editors. No.

Use MMD's 10 default toon texture images after importing an MMD model into Blender - Yes
(But you need to set MikuMikuDance's Data directory as the "Shared Toon Texture Folder" for mmd_tools in Blender's User Preferences. Then click "Save User Settings". Otherwise the imported model may appear purple in Blender.)

Convert materials for Blender's Cycles render engine - Yes
("Convert Materials for Cycles" button.)

Toggle the visibility on and off of Mesh, Armature, Rigid Bodies, Joints, Rigid Body names, Joint names, Toon Textures, Sphere Textures - Yes.
(Using the MMD Display panel, which is located on the bottom right side of the 3D View in the 3D View Properties panel)

6. MMD_TOOLS MODEL ANIMATION FEATURES

Physics animation in Blender. Yes 
(Click on the Physics [Build] button, before rendering a physics animation of the MMD model in Blender. The Physics [Clean] button reverses the Physics [Build] operation. If you want to edit the MMD model in Blender and then export it from Blender, you should not [Build] its Physics or you should [Clean] the Physics from it before exporting it.)

Editing and animating of PMX append Rotation and append Movement constraints in Blender - Yes
(Click on Bone Constraints [Apply] to create the Blender constraints which are needed to animate these append Rotation and append Movement constraints. When you import a PMX model into Blender with mmd_tools, these constraints are automatically created, so you only need to use the Bone Constraints [Apply] button if you have edited these appends in Blender. Bone Constraints [Clean] reverses this operation and removes the Blender constraints for the PMX append Rotation and append Movement properties.)

7. MMD_TOOLS MODEL CREATION AND CONVERSION FEATURES

Convert a model to an MMD model. Yes. 
([Convert Model] button, with armature object selected to be the active object)

Option to use either diffuse color or mirror color as the source of the ambient color when converting a model to MMD. - Yes
(Blender materials do not have any ambient color. Blender's .obj importer and .obj exporter, and a few other add-ons store an imported object's ambient color in its mirror color.)

Create an MMD model - Yes. ([Create Model] button)

Add one or more mesh objects to the (created) MMD model - Yes
([Attach Meshes to Model] button, with the MMD model as the active object. Adds all mesh objects in the scene to the MMD model.
If you want to convert a model to MMD which has no armature:
1. Click on the mmd_tools [Create Model] button.
2. Click on the mmd_tools [Attach Meshes to Model] button.)

8. MMD_TOOLS MODEL AUTOMATIC ERROR CORRECTION FEATURES

Automatic correction of PMX model errors - Yes, but not all errors.
(When you import a pmd or pmx model into Blender, you can choose these import options: "Clean Model", "Fix IK Links", "Remove Doubles". These import options can automatically fix some, but not all, model errors of the imported model.)

9. MMD_TOOLS CAMERA FEATURES

Converting a Blender Camera to an MMD camera - Yes
(At the bottom of the Camera's Object tab in the Properties Windows is an "MMD Camera Tools" panel with a "Convert" button. What is an "MMD camera"? An MMD camera is an empty object which is parent of a Blender camera. When importing or exporting VMD camera animations, this "MMD camera" empty object is animated, instead of a Blender camera.)

Transferring a Blender Camera's animation onto an MMD camera - Yes
(After clicking on the Convert button, enable the Bake Animation option.)

Transfer the Blender camera animations of the entire scene onto an MMD camera, including the animations of more than one camera. - Yes
(After clicking on the Convert button, enable the Bake Animation option, and select "Scene" as the Camera Source.)

Control the MMD camera with controls similar the camera controls of MikuMikuDance. Yes.
(After clicking on the Convert button, click OK and these camera controls will appear in this same "MMD Camera Tools" panel, under the camera's object tab in Blender's Properties window.)

10. MMD_TOOLS SUPPORT FOR EDITING, POSING OR ANIMATING ADVANCED MORPHS (MATERIAL MORPHS, BONE POSE MORPHS, UV MORPHS, GROUP MORPHS)

The data of these morphs is preserved and will be re-exported when a previously imported PMX model is exported from Blender:
UV morphs - Yes
bone pose morphs - Yes
group morphs - Yes
material morphs - Yes

These morphs can be edited in Blender:
UV morphs - Yes
bone pose morphs - Yes
group morphs - Yes
material morphs - Yes

(To edit a UV morph in Blender:
1. In the mmd_tools Morph Tools panel, select the UV morph that you want to edit.
2. Click [View] to create a temporary UV map of the UV morph data.
3. Click [Edit] to edit this temporary UV map in Blender's UV Editor. The vertices of the UV morph will be selected in Edit mode of the 3D View window, and in Blender's UV Editor.
4. After you have finished editing the UV morph, click [Apply] to add the edited UV morph data into the UV morph of the MMD model. 
5. Click [Clear] to delete the temporary UV map.)

These morphs can be posed and animated in Blender:
UV morphs - Yes
bone pose morphs - Yes
group morphs - Yes
material morphs - No
(On the right side of the Morph Tools panel, click on the middle arrow button, then click [Bind] to make the morphs slider controls appear. (The [Create] menu item is only used for testing purposes.))

VMD import of animated bone pose morphs - Yes
VMD import of animated UV morphs - Yes
VMD import of animated group morphs - Yes
VMD import of animated Material morphs - No

VMD export of animated bone pose morphs - Yes
VMD export of animated UV morphs - Yes
VMD export of animated group morphs - Yes
VMD export of animated Material morphs - No

11. MMD_TOOLS MODEL JAPANESE TO ENGLISH TRANSLATION FEATURES

Mass translation and adding of English names to an MMD model. Yes. (Translation button)

**Comment by Hogarth-MMD** [comment]
I am putting together a list of mmd_tools features, accompanied by brief tutorial information. Can other people please help me to correct any errors or incompleteness in the list which I have posted above?

**Comment by Hogarth-MMD** [comment]
I don't understand why these 2 features are needed: 
Material Sorter
Meshes Sorter

Cannot the materials be sorted under the Materials tab of the Properties window? If I sort the materials in the normal Blender way, will this order of materials be ignored when exporting a model from Blender?

**Comment by Hogarth-MMD** [comment]
"Attach Meshes to Model
This will locate any meshes not part of an MMD-style model and attach them to the last material in the selected imported model."

I don't understand this. A mesh object cannot be attached to the material of another mesh object. This idea seems to be nonsensical.

**Comment by Hogarth-MMD** [comment]
"Apply and Clean Bone Constraints
MMD and Blender handle bone appends in different ways. To translate between these, use Apply to translate appends into a form usable by Blender or Clean to translate appends into a form usable by MMD. Bones will be cleaned automatically upon export."

I don't understand this. Does this mean that the user must click on the "Apply Bone Constraints" button before animating an MMD model in Blender? In addition to clicking on the "Build Physics" button before animating an MMD model in Blender?

**Comment by Hogarth-MMD** [comment]
In the Wiki, there is an absence of information about the 4 advanced morph types. I need this information to complete the list of mmd_tools features.

**Comment by nathanvasil** [comment]
> Resizing a model when converting it to MMD:

See the "scale" parameter on export dialogue.

> These morphs can be edited in Blender: (How?)
> material morphs - No

Material morphs can be edited (for export, since they don't currently render without some work).
In order to edit material morphs, or any other morphs, check out the "Morph Tools" subsection of the toolbar.  You can edit these values and they'll propagate to an export.

> Clean physics
> (What does this do? Revert a model from mmd_tools animation mode back to mmd_tools edit mode???)

That's my understanding, yes.  It's the reverse of "build physics".

> Materials Sorter (What does this do?)

Allows specification of material order for .pmx export in order to prevent rendering problems related to draw order + alpha.

> I don't understand this. A mesh object cannot be attached to the material of another mesh object. This idea seems to be nonsensical.

MMD models are kept track of at a few levels-- you have the individual object, but that object can be separated by materials into multiple objects.  So you also have MMD tools keeping track of which objects belong to which models in order to export properly.  "Attach meshes to model" well, attaches a mesh that is not yet part of the model to the model.  Attaches _all_ unattached meshes, IIRC.  This is to enable export of meshes created entirely within Blender.  (The way to do this manually is to parent the mesh to the model's armature, which I find simpler and more intuitive.)

> I don't understand this. Does this mean that the user must click on the "Apply Bone Constraints" button before animating an MMD model in Blender? In addition to clicking on the "Build Physics" button before animating an MMD model in Blender?

I believe that building is done automatically on import, but if you change the MMD Bone custom properties, it won't propagate to the Blender bone properties until you apply bone constraints.

MMD does support a few things that aren't supported very directly by Blender, notably, rot/mov appends with influences outside of 0-1 range.  I'm not sure if MMD Tools is handling those properly yet.  (It's possible to do so, just cumbersome.)

> In the Wiki, there is an absence of information about the 4 advanced morph types. I need this information to complete the list of mmd_tools features.

What do you need to know?  I wrote that before bone/uv/mat/group morphs were being read by Blender, and I haven't yet used those newer functions of mmd_tools.  I've only ever used them to edit morphs for exports.  But if you need some help understanding something in particular about these morphs, I could do my best.

**Comment by powroupi** [comment]
>VMD import export of animated bone pose morphs - ?
VMD import export of animated Material morphs - ?
VMD import export of animated UV morphs - ?
VMD import export of animated group morphs - ?

Currently, you can export `.placeholder` object's shape key animation to a VMD file which has the ability to export all key frames of all morphs. (`.placeholder` is created when click [Bind] or [Create] in Morph Tools panel's special menu).

Select `.placeholder`/mesh object to export `morph.vmd`, select armature object to export `dance.vmd`.
Select root object will export `combined.vmd` of the armature object's bone animation and the first mesh object's shape key animation.

Select root object to import VMD to all object of the model (armature, meshes, `.placeholder`).

**Comment by Hogarth-MMD** [comment]
"Select .placeholder/mesh object"
I don't understand this. How can I select this object?

**Comment by powroupi** [comment]
@Hogarth-MMD After clicking [Bind] or [Create] in Morph Tools panel's special menu, `.placeholder` object is created under root object, go to Outliner you'll see it, left mouse click to select it. :)

**Comment by Hogarth-MMD** [comment]
Can someone please explain how to edit UV morphs in Blender with mmd_tools?

**Comment by Hogarth-MMD** [comment]
Bone constraints apply clean

@nathanvasil gave an explanation of his understanding of these 2 buttons. Will @powroupi please give an authoritative explanation and clarification of these 2 buttons? Previously I asked if Apply Bone Constraints is needed before animating an MMD model in Blender?

**Comment by Hogarth-MMD** [comment]
Previously I asked if the order of a model's materials can be sorted in the normal Blender way before exporting the model to pmx. So no one knows the answer to this question? I cannot be lazy and I need to do this experiment myself if I want to find the answer? LOL. :smile:

**Comment by powroupi** [comment]
To edit UV morph:
1. click **[View]** to create temporary UV map, it will be the result of active UV morph, the vertices will be selected in Blender UV Editor.
2. **[Edit]** temporary UV map via Blender UV Editor, the vertices will be selected in Edit mode of 3D View according to the selected vertices in Blender UV Editor.
3. **[Apply]** UV offsets of selected vertices in Edit mode of 3D View, select all to calculate all vertices.
4. **[Clear]** temporary UV map
5. Ps. If a vertex is shared among multiple faces and you don't want the vertex's UV morph to affect all those faces, you may need to rip the vertex.

>if Apply Bone Constraints is needed before animating an MMD model in Blender?

Of course yes, it will set up bone constraints of MMD bone's Move/Rotate append.

>if the order of a model's materials can be sorted in the normal Blender way before exporting the model to pmx.

Yes, Material Sorter is made for older Blender versions, and it lists MMD material's `name_j` and `name_e`.

**Comment by powroupi** [comment]
>Meshes Sorter
(What does this do?)

The mesh order affects material order on [Export] and [Join Meshes]. So, you may use Meshes Sorter to adjust material order as need after clicking [Separate By Materials].

**Comment by Hogarth-MMD** [comment]
"if Apply Bone Constraints is needed before animating an MMD model in Blender?
Of course yes, it will set up bone constraints of MMD bone's Move/Rotate append."

Is this the one and only purpose and result of Apply Bone Constraints?

**Comment by Hogarth-MMD** [comment]
'Ps. If a vertex is shared among multiple faces and you don't want the vertex's UV morph to affect all those faces, you may need to rip the vertex."

Sorry, I don't understand what this means: "rip the vertex" (?).

**Comment by Hogarth-MMD** [comment]
So, when an MMD model is imported into Blender, it does not have any Blender equivalent of the copy rotation or copy movement constraints? Before animating the MMD model in Blender, someone needs to click on the [Apply Bone Constraints] button, if he wants to see the Copy Rotation and Copy Movement constraints in the Blender animation?

**Comment by Hogarth-MMD** [comment]
I was not able to do a UV morph edit, because the texture image for the UV morph is not appearing in the Blender UV editor. The model which I tried to edit has about 50 different texture images, and I have no idea which texture image should be appearing for the UV morph that I tried to edit.

**Comment by Hogarth-MMD** [comment]
' (.placeholder is created when click [Bind] or [Create] in Morph Tools panel's special menu)."

I don't understand these instructions. What is the difference between [Bind] and [Create] ?

**Comment by powroupi** [comment]
>Is this the one and only purpose and result of Apply Bone Constraints?

Yes, and it is applied on import by default. You may click [Apply] to make sure the constraints are set up properly if you modified the armature object.

>Sorry, I don't understand what this means: "rip the vertex" (?).

Just like when you want to make UV morph for only one face of Blender's default cube which has only 8 vertices, you will need to separate out the face to make sure its 4 vertices are not used by other faces before making UV morph for that face.

>I was not able to do a UV morph edit, because the texture image for the UV morph is not appearing in the Blender UV editor...

You may set texture/material shading in 3D View and try to figure out correct texture. In some cases, you can see the effect in 3D View while editing UV even if the texture image is not appearing in the Blender UV editor.

>What is the difference between [Bind] and [Create] ?

The only difference is that [Create] will not set up drivers/constrains for you. ([Bind] = [Create] + [Driver Stuff])

**Comment by Hogarth-MMD** [comment]
Thanks for your replies, @powroupi ! What is the benefit of [Create], then?

**Comment by powroupi** [comment]
>What is the benefit of [Create], then?

Just for testing some simple things in some cases. :smiley:

**Comment by Hogarth-MMD** [comment]
Okay, I finished the new list of mmd_tools features (unless I have made a few errors). You can find it in the first comment of this issue. You can also find it the mmd_tools wiki (tutorials section). In addition to a list of features, it also has brief tutorial information for each feature.
 
https://github.com/powroupi/blender_mmd_tools/wiki/MMD_TOOLS-LIST-OF-FEATURES-AND-BRIEF-TUTORIAL-INFORMATION-FOR-FEATURES

**Comment by powroupi** [comment]
@Hogarth-MMD, thank you very much. :smile: And I thnk maybe we can make it look better by [styling it with Markdown](https://guides.github.com/features/mastering-markdown/). :yum:

**Comment by Hogarth-MMD** [comment]
Adding and editing physics rigid bodies and joints - Yes
(Rigid Bodies panel, Joints panel of mmd_tools)

I missed a feature! But I just added it to the list.

**Comment by Hogarth-MMD** [comment]
I don't see any information about making correct line breaks with markdown. I was having problems editing line breaks in the wiki.
I also don't see anything about making colored text. Colored text would make a nicer-looking appearance.

**Comment by powroupi** [comment]
Headers, bold texts, lists, and links should be good enough I think. :smile: 
# Header `# Header`
## sub header `## sub header`
**Bold** `**Bold**`

**Comment by nagadomi** [comment]
About physics rigidbody, can mmd_tools correctly preview rigidbody collision settings on Blender?
MMD uses `Collision Group Mask` like Blender Game Engine. However, Blender uses `Collision Group`. mmd_tools seem to avoid collisions using `Disable Collision` option of Joints without using Collision Group. It does not seem to be compatible.
I know this issue generally do not matter in my usecase if increase `Steps per second` and `Solver Iteration` in `Rigid Body World`, or a little fixes. This is just a quick question.

**Comment by powroupi** [comment]
@nagadomi Select a MMD rigid body object, go to [Properties window]->[Object tab]->[MMD Rigid Body panel], there are the settings of MMD rigid body, (Select a MMD joint object, you will see [MMD Joint panel]), you will need to click [Build] if you modified these values.

`mmd_tools` uses Blender viewport physics which has most corresponding settings for MMD physics (except `Collision Group Mask` :cry: ) and easier to set up. (the size of BGE `Collision Group Mask` is not the same in Blender 2.7x versions, and there are some alpha issues :cry:)

**Comment by nagadomi** [comment]
Thanks for quick reply. The above question was about physics simulation on Blender. So, does it mean that `Collision Group Mask` on `MMD Rigid Body` panel cannot be previewed on Blender's physics simulation due to difference in physics engine?

**Comment by powroupi** [comment]
It is necessary to [Build] physics to preview the result of `Collision Group Mask` settings, and it will ignore some [non collision constraints](https://github.com/powroupi/blender_mmd_tools/blob/67a002bcfbe8a3c6427f76a2b0b23c13eb6ce486/mmd_tools/core/model.py#L880-L882).

**Comment by Hogarth-MMD** [comment]
Adding and editing physics rigid bodies and joints - Yes
(Using the Rigid Bodies panel and Joints panel of mmd_tools. With a Rigid Body selected, its settings can be viewed and edited under the Object tab of Blender's Properties Window, in the [MMD Rigid Body] panel. With a Joint selected, its settings can be viewed and edited under the Object tab of Blender's Properties Window, in the [MMD Joint] panel.)

Okay, I have amended the list of features as you see above. I already knew this, of course. I was just testing to see if other people also knew this. :smile:

**Comment by nagadomi** [comment]
@powroupi 
Oh, Does mmd_tools implements Collision Group Mask with only Rigid Body Constraints? :scream:  I didn't think of it that way. I will try to read the code. Thanks for the info.

**Comment by Hogarth-MMD** [comment]
When I am re-editing a Wiki page, I can get a double spacing or no spacing of lines. I cannot get a single spacing of lines of text. Shift Enter does not give me a single spacing of lines of text.

**Comment by nagadomi** [comment]
>I can get a double spacing or no spacing of lines. I cannot get a single spacing of lines of text.

I don't recommend this way. You can use single spacing with putting two white spaces at the end of the line.
```
Text.  <- 2 white space here
Text.
```
reference https://gist.github.com/shaunlebron/746476e6e7a4d698b373

**Comment by Hogarth-MMD** [comment]
If someone edits a model to add or delete vertices, will any of the model's data be messed up as a result of adding or deleting vertices?
UV morph data?
Vertex morphs data?
SDEF data?
vertex group which stores the order of vertices?
other data?

**Comment by nathanvasil** [comment]
Depends on how those verts are added.  Subdividing, knife tool, loop cut tend to create data appropriately.  Making a fresh vert, like ctrl LMB, doesn't.  Not sure about things like alt-p poke faces. it probably does, or else I would have noticed.

Shapekeys / vertex morphs, and SDEF since it uses those, can get really badly screwed up by changes to geometry like adding verts, but Blender's to blame for this, not MMD Tools.  But usually you can get away with it anyways.  Not sure about SDEF, interpolated center/radius values shouldn't really be correct unless they're all the same and I can't remember if that's the case.

Vertex order won't make any kind of sense after adding verts, but you don't actually need it for anything.

Weights, incl. UV morphs, will get appropriately interpolated values on subdivision type actions.

**Comment by nagadomi** [comment]
Let me confirm if I got it. Is Constraint of bone.fixed_axis not supported on Blender?

**Comment by Hogarth-MMD** [comment]
So, if I add or delete a vertex, nothing will be left but the evil, mutilated remains of this model?
:worried: :cry:

**Comment by powroupi** [comment]
>If someone edits a model to add or delete vertices, will any of the model's data be messed up as a result of adding or deleting vertices?

In my opinion, it can be safer to add new mesh object if you want to add new geometry, and can be safer to "separate selection" `in edit mode, [Mesh]->[Vertices]->[Separate]->[Selection]` if you want to remove some vertices. SDEF data are not reliable after changing geometry in Blender, you may need to fix them in PMDE/PMXE.

>Is Constraint of bone.fixed_axis not supported on Blender?

It is not yet implemented in `mmd_tools`. Similar to `Limit Rotation` constraint, however, bone direction (bone tail position) is irrelevant in MMD. (it is a little tricky to implement :cry: )

**Comment by Hogarth-MMD** [comment]
I don't see any reason why adding vertices would cause a problem(?). The newly added vertices will always have vertex indexes higher than all of the other vertex indexes.

And thank you @nagadomi for your very helpful information about wiki line breaks. :+1:

**Comment by powroupi** [comment]
>I don't see any reason why adding vertices would cause a problem(?)

Yeah, I mean you don't need to worry about messing up an existing object if you add/edit new geometry in a new mesh object. :)

**Comment by nathanvasil** [comment]
> I don't see any reason why adding vertices would cause a problem(?). The newly added vertices will always have vertex indexes higher than all of the other vertex indexes.

My understanding is that in order to preserve imported vertex order, t's not using Blender's index, it's using the mmd_vertex_order vertex group.  So when you, say, subdivide an edge, you'll end up with interpolated values for that vertex group for your new vertex.  I'm not sure, but I believe that pushes everything higher than that up one: it squeezes the new vert into the middle of whatever you did.

It's easy enough to test out, save some morphs to .csv from PMXE, import, make some verts, export with vertex order, see what happens when you try to import your morphs back into the model from .csv.   But like I said, it's not really very important.

**Comment by Hogarth-MMD** [comment]
@nathanvasil and others may not know this:
In Blender you can see the vertex indexes of a mesh object if Blender is running in debug mode. If you run Blender in debug mode, an option to display the vertex indexes will appear in edit mode for mesh objects, which you can then enable. To run Blender in debug mode, just type bpy.app.debug = True    into the Blender python console. Alternatively you can run Blender from the command line blender.exe --debug

**Comment by Hogarth-MMD** [comment]
Hello @powroupi! I see that mmd_tools now has 3 export options for vertex order: 
from the mmd vertex order vertex group, from Blender, and None. I don't understand how there can be vertex order sorting None. Can you please explain these options?

**Comment by powroupi** [comment]
Sort Vertices:
 - **None**: No sorting, the vertex sequence is defined by pmx exporter while gathering mesh data
 - **Blender**: sort vertices by blender's internal vertex order (and object order), [low -> high]
 - **Custom**: sort vertices by custom vertex weight of vertex group "mmd_vertex_order"  (and object order),  [low -> high]

**Comment by powroupi** [comment]
See/edit wiki for documents of features. :smile:
