### ISSUE TITLE
MMD style rendering in Cycles

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#146]
I made a first draft of an MMD nodes setup for Cycles: http://www.mediafire.com/file/scarw5tcmv4zdcz/MMDLightMats.blend .

It's insufficiently tested, I'm certain there are bugs, but the general flow should be there.  It replicates MMD's self-shadow mode 2.  I've labelled my nodes but organization isn't as good as it could be.

Exact lighting and edge line probably aren't obtainable, just tuning it by eye.  Haven't actually tuned edge line thickness, just used a value that worked.

There are a few drivers if you want to load with auto-run scripts.  Some values are created just for the potential to create drivers (for mat morphs), but I didn't create the actual drivers for those values.

I wrote some words about it in a text block included in the file.

Right now, I think this is sort of a stupid rendering trick-- you could just render it in MMD in a fraction of the time and complexity-- but I know some people are interested in this.  Not something I would personally want to implement in MMD tools :)  Offering in case there's more interest than I thought, and for people visiting in order to figure out how to do this.  Closing this issue as I open it :)

**Comment by Hogarth-MMD** [comment]
It's a completely empty .blend file. I'd like to have a look at your node setup.

**Comment by nathanvasil** [comment]
I just redownloaded it to test.  It's not an empty file.

It contains a mesh, duplicated to 4 layers for render layers, each with its own material for its particular render layer, and a compositing setup, as well as textures for the mesh.

**Comment by Hogarth-MMD** [comment]
Great, thanks! It looks like I was having a browser download problem, and I wasn't getting the complete .blend file, but now I have it.
