### ISSUE TITLE
PMX export does not generate PMX

### ISSUE THREAD

**Issue by fu3nori** [powroupi/blender_mmd_tools#147]
Nice to meet you.
Although this add-on, ver.0.4.5 has been installed on Blender 2.79b, although PMX can be imported, the phenomenon that PMX is not generated when PMX export is executed has occurred.
Could you handle it here?

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: I'm currently developing [dev_test](https://github.com/powroupi/blender_mmd_tools/tree/dev_test) branch, you may update your `mmd_tools` to that version which should be able to export PMX files. :yum: 

[0.4-main](https://github.com/powroupi/blender_mmd_tools/tree/0.4-main) and [master](https://github.com/powroupi/blender_mmd_tools/tree/master) have not been updated for a long time, so using [dev_test](https://github.com/powroupi/blender_mmd_tools/tree/dev_test) branch is recommended. And please remember to remove old `mmd_tools` folder before installing a new one. :)

**Comment by fu3nori** [comment]
Thank you very much for your quick reply.
I verified it immediately using "dev_test", but I could import it but it was not possible to export.

So I made a simple cube with blender and tried exporting in the same way, but I could not export it.

I predict that it is not a matter of model data, but a compatibility problem between the current version of Blender and addons, but is there a solution?

**Comment by powroupi** [comment]
You need to [Create Model] to create basic MMD rig in Blender and parenting your meshes to the armature object (or [Attach Meshes to Model]), you may replace the basic armature with your armature object as need, then export the MMD rig. This is the basic way to export PMX using `mmd_tools`.

There is also a [Convert Model] button to convert existing model. Select your armature object, [Convert Model] to convert it to MMD rig, then export the MMD rig. :smile: 

Additionally, you may read [wiki/Documentation.ja](https://github.com/powroupi/blender_mmd_tools/wiki/Documentation.ja), hope it helps. :)

**Comment by fu3nori** [comment]
Thank you very polite commentary.
I will try out the action while referring to the wiki immediately.

**Comment by fu3nori** [comment]
And I'm sorry many times.
I performed the operation again based on the information of the wiki I taught. .
Then I opened the MMD tab and clicked the Create button.
Then, I selected import from the file menu and incorporated my own LWO.
Then, I output pmx from the file menu, but the file was not output.
Also, the Convert button on the MMD tab was also grayed out and could not be used.
The setting is as follows, but are there other oversights I have overlooked?
Setting window figure ↓
https://imgur.com/a/wd4hXZb

**Comment by powroupi** [comment]
Looks like you want to export the object `ship`.

In the picture, you might just click [Attach Meshes to Model] button, then you should be able to export the MMD model  `New MMD Model`. :smiley: 

Or, in the Outliner, expand `New MMD Model`, you should see the armature object `New MMD Model_arm`, drag and drop your `ship` to the armature object `New MMD Model_arm`, then you should be able to export the MMD model  `New MMD Model`. :smiley:

**Comment by fu3nori** [comment]
Thank you for always polite explanation. Immediately, I will try after coming home.
I am very grateful for the kind response.

**Comment by fu3nori** [comment]
Thank you very much.
This problem solved successfully.
I was convinced that we could convert only with the Import menu and the Export menu.
However, by executing [Attach Meshes to Model] as you explained, you can convert the file successfully!
Thank you!

**Comment by powroupi** [comment]
You're welcome. :smile: 
If your model contains only meshes, [Create Model] and [Attach Meshes to Model] should be enough. If your model contains armature and meshes, select the armature and then [Convert Model], it is another way. :smiley:
