### ISSUE TITLE
convert mesh-only model to MMD model

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#148]
Hello @powroupi ! Someone was asking for my help to convert a model to MMD which has a mesh object, but no armature object.  Maybe some time when you have some free time, you can add this feature to the "Convert Model" button. :smile:

**Comment by powroupi** [comment]
There is a basic way I've mentioned in #147 (use [Create Model] and [Attach Meshes to Model], it is pretty simple). You could select a armature object and click [Convert Model] any time if you want to convert `mmd_material` (the conversion only work with Blender Internal Renderer material and limited though) and some little things.

The [Convert Model] expects a rigged model, and personally I don't recommend users to use it without understanding how to convert it manually when using `mmd_tools`. :sunglasses:
