### ISSUE TITLE
[discussion] how to use blender to swap model parts

### ISSUE THREAD

**Issue by ptrthomas** [powroupi/blender_mmd_tools#149]
big thanks again to @powroupi and all other contributors. great to see how this has matured over 2 years. and now I'm actually able to do complex stuff in blender

till now I only focused on animation and exporting to unreal-engine, but I'm now considering getting into simple modeling, and one of the things I want to do is take parts (skin, hair) from one model and transplant them onto another.

maybe this is simple or maybe not because of the need to manage armature binding and vertices. maybe this is already well documented somewhere, in that case - apologies and just point me to the right place.

questions: how would you go about this, and does mmd_tools have any functions that make this easier. what should I watch out for

**Comment by nathanvasil** [comment]
MMD tools doesn't have anything specific for that, although if you're trying to add .pmx parts, some of the ways to interact with physics in Blender via MMD tools are easier than doing it in PMXE (and the MMD Tools rigid body implementation is great, simpler to deal with than doing it from scratch in Blender.)

Just start by unparenting a mesh, removing its armature modifier, and reparenting it to a different armature (with armature deform, nothing else).  Often, the standardized nature of the MMD skeleton will mean it will just work (but not necessarily work well.)  Other times, it will be weighted to model-specific bones and you'll need to recreate those bones on the destination model.  For weights, there are a lot of tools, ranging from a weight transfer (data transfer modifier) through Blender's automatic weights through weight painting and more.

If you haven't already, you'll want to get comfortable with animation, posing in Blender, because it's easier than running through export cycles, and important for understanding which engine is screwing it up when something goes wrong.

If you have a DA account, you should feel free to send me a PM anytime you hit a snag.  I'm at https://vasilnatalie.deviantart.com/ and usually willing to help people work through their modelling issues.

**Comment by ptrthomas** [comment]
@nathanvasil thanks, this is super helpful. since I'm not focusing on clothes (idea is to use unreal engine for 100% cloth simulation, even hair) I'm hoping that removes most of the rigid body complexity. is that right ?

BTW I've always found the rigid body world in blender and some of the constraints very hard to understand and always felt there might be a simpler way. suppose you had to write mmd_tools from scratch - would you do anything differently ? I don't mind getting into coding this. also long term I'm wondering if it is worth writing a direct pmx --> unreal engine exporter etc.

**Comment by Hogarth-MMD** [comment]
With MMD models, a complicating factor is needing to delete physics when performing this operation. PMD editor and PMX editor have a feature that you can merge 2 armatures, including merging 2 bones which have the same name, when you import a model with the add/append import option selected. Blender does not have anything similar to this feature.

**Comment by powroupi** [comment]
As @nathanvasil said, `mmd_tools` doesn't have anything specific for that, sorry. :disappointed: If your models are not too complicated, merge/swap them might not be too hard I think (there are some tutorials). :smile: 

Some references:
 - [Keep weights when joining armatures?](https://blenderartists.org/t/keep-weights-when-joining-armatures/655054)
 - [How to combine various armatures?](https://blender.stackexchange.com/questions/10772/how-to-combine-various-armatures)
 - [Searching - blender swap model parts](https://www.google.com/search?q=blender+swap+model+parts)

**Comment by ptrthomas** [comment]
@powroupi thanks for the links ! very useful. I'll close this, but all - feel free to add more points when you think of them.

**Comment by Hogarth-MMD** [comment]
```python

# Select Object, Join
# to combine the selected armature objects into one object
# Then run this script to delete all bones with "duplicate" bone names
# "Duplicate" bone names are bone names which end with .001 or .002 etc.

import bpy

digits = "0123456789"
bones_to_be_deleted = []

bpy.ops.object.mode_set(mode="EDIT")
for b in bpy.context.active_object.data.edit_bones:
	if b.name[-4:-1] == '.00':
		if b.name[-1] in digits:
			bones_to_be_deleted.append(b)

for b in bones_to_be_deleted:
	bpy.context.active_object.data.edit_bones.remove(b)

bpy.ops.object.mode_set(mode="POSE")

```

**Comment by Hogarth-MMD** [comment]
Above is a simple python script to delete duplicate bones after joining armatures in Blender.

**Comment by Hogarth-MMD** [comment]
I wonder if it might be possible to automatically move physics from one armature to another, automatically adding physics to a model which has no physics. It could be a big time-saver. The problem would be to make the rigid bodies and joints move along with the bones. Each joint is typically connected to 2 bones through 2 rigid bodies, so how would you make them move along with the bones? What about the ability to save physics presets to be used with adding physics? That could be a helpful time-saver.

**Comment by nathanvasil** [comment]
You can transfer physics easily enough, but it won't necessarily match the skeleton you import it onto.

Bones move bone-type rigid bodies, which move joints, which move physics type rigid bodies, which move bones and possibly more joints, which move more physics type rigid bodies....

In rough terms, that means that you could get appropriate translation of rigid bodies by translating the same amount you translated the bone, and joints, the same amount you translated the bone to which its first rigid body is attached.

But MMD armatures don't contain enough information to be able to rotate or scale physics.

**Comment by Hogarth-MMD** [comment]
"till now I only focused on animation and exporting to unreal-engine"

Just taking a look at the animations you've made, @ptrthomas . A lot of hard work and generosity has gone into MMD and mmd_tools. I'm curious to see what people are going to do with it. MMD is loads of fun. :smile: 
https://www.youtube.com/user/ptrthomas/videos

**Comment by ptrthomas** [comment]
@Hogarth-MMD thanks :) looking back I have a nice assortment of videos now ! Fun ? yeah ! mmd_tools has been a blast.

I'm pretty sure I'm the first to manage to get a Lat model into UE: https://www.youtube.com/watch?v=fbbuS7TqiX0 and the first to retarget an MMD motion onto an UE4 character rig: https://www.youtube.com/watch?v=NVBDtNE4LDk 

I'm interested in seeing what Blender EeVee does, since there is so much time spent in the UE conversion - I might stay in Blender for movies maybe !

**Comment by Hogarth-MMD** [comment]
Your youtube videos are very eye-catching and professional-looking. I'm impressed.
