### ISSUE TITLE
Sour type model‘s Skeleton is broken with MMDTools

### ISSUE THREAD

**Issue by bladesero** [powroupi/blender_mmd_tools#153]
![qq 20180618142812](https://user-images.githubusercontent.com/18096279/41521258-0f267008-7304-11e8-84b3-7ddd5988d660.png)

**Comment by nagadomi** [comment]
It seems that the iteration of arm IK is not enough.
It is probably fixed with the following steps.

1. Select the armature
2. Object Tab -> MMD Model Information Panel -> Change MMD IK Loop Factor
3. Input 10 and Click

**Comment by bladesero** [comment]
yes，thank you
