### ISSUE TITLE
VMD export problem

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#158]
Someone is asking for my help. Any idea how to solve this person's problem?:

"I'm having a problem when trying to export an animation to vmd format. It works fine in blender but when I try to import the exported vmd file in MMD the arms and legs for some reason not rotate at all."

**Comment by Hogarth-MMD** [comment]
This person now says that he was able to solve this problem.

**Comment by zeromizkun** [comment]
@Hogarth-MMD Heyho, any ideas what was done to solve the issue? I might have it too, only my hips and chest bones are moving, the arms and legs have no keyframes after exporting to vmd :(

**Comment by Hogarth-MMD** [comment]
When bones of a model fail to be animated, it is usually because bone names in the animation are not the same as bone names of the model. My mmd_tools_helper Blender add-on can be used to diagnose bone naming issues:
https://github.com/Hogarth-MMD/mmd_tools_helper/archive/master.zip

Note that mmd_tools_helper is not updated for Blender 2.8.
For more help, see the mmd_tools github wiki tutorials:
https://github.com/powroupi/blender_mmd_tools/wiki/Links-to-mmd_tools-Tutorials

**Comment by Hogarth-MMD** [comment]
This is a helpful tool for diagnosing problems with a VMD file:

VMDConverterGraphical 
(converts VMD files to CSV text files and CSV text files to VMD files)
https://bowlroll.net/file/13705
Unzip password is in the included text file (numa).

**Comment by Hogarth-MMD** [comment]
Another problem can arise when a VMD animation is exported from MMD. Only the selected bone frames will be exported. Sometimes people fail to select all bone frames before exporting the VMD animation from MMD. In MMD, select Edit, Select all bone frame.
