### ISSUE TITLE
Rotation limit of IK is not correctly imported

### ISSUE THREAD

**Issue by nagadomi** [powroupi/blender_mmd_tools#16]
Here is the original X rotaion limit of right knee bone. It is 0.5~180.
![mmd_leg_ik](https://cloud.githubusercontent.com/assets/287255/16711992/caddc29a-46b2-11e6-98b6-1c7c8a776ccb.png)

Here is the imported X rotaion limit of right knee bone. It is 0~180.
![blender_leg_ik](https://cloud.githubusercontent.com/assets/287255/16711993/cd11a63a-46b2-11e6-8d9a-744bc27a060d.png)

I think [importer code is correct](https://github.com/powroupi/blender_mmd_tools/blob/9a8d08056b28405a77e7a46f7f0751bd0069f285/mmd_tools/core/pmx/importer.py#L239), but in blender, a positive value of minimum angle of IK is not allowed.

When I manually added "Limit Rotation Constraints", lots of imported motions works more properly.
![fix_leg_ik](https://cloud.githubusercontent.com/assets/287255/16712002/1c4e0702-46b3-11e6-9927-29639405a071.png)

**Comment by powroupi** [comment]
Thank you for reporting this issue. :)

> I think importer code is correct, but in blender, a positive value of minimum angle of IK is not allowed.

Yes, you are right, this also affects the pmx exporter.

> When I manually added "Limit Rotation Constraints", lots of imported motions works more properly.

I think the owner space should be `'LOCAL'`..., i will try it later. :smile: 

EDIT:
After playing the settings, the result works fine when using your settings, and works good (i think) using `Local Space` and `Min X` set to 20 degrees (optional 10 ~ 30 degrees).

EDIT2:
Well, i think it is the IK iterations issue, in most case, it can be solved by increasing the IK iterations. :smile:

**Comment by nagadomi** [comment]
I think rotation_limit_x_min=0 is the most bad choice. because the knee cannot bend with vertical moving or vertical pushing. It causes leg teleporting sometimes. if rotation_limit_x_min > 0, knee bends easily.

I think this is the reason why is MMD's rotation_limit_x_min 0.5 by default.

**Comment by powroupi** [comment]
Okay, i used your trick to fix the rotation limit of IK, also fixed the exporter. :)
Feel free to report further issues. Thank you. :smile:

**Comment by nagadomi** [comment]
Thanks :smile: 
A basic problem of IK is blender's IK solver is different with MMD's IK solver. I  need lots of motion fixes for this :cry:
