### ISSUE TITLE
Conversion to Cycles Mats ignoring sphere maps

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#163]
Just released my first original MMD model ( https://www.deviantart.com/vasilnatalie/art/Download-Miss-April-pmx-for-MMD-754905333 if you don't mind the self-promotion) and decided to see how MMD Tools handled use in Blender.  Just downloaded a fresh copy of MMD Tools yesterday, so I imagine my copy is up to date.

There are a couple of issues (physics, probably bones), but what stuck out most was conversion to Cycles materials, which is ignoring the model's sphere maps.

Sometimes, it's appropriate to ignore sphere maps, because they mostly represent environment maps that are better represented by actual environments or HDRI worlds in Blender, but they do contain some information about the material that can be important.  That's especially noticeable when it comes to using a sphere map to give a material Fresnel transparency (like for glasses).

It's not that hard to implement a sphere map in Cycles nodes; there's a lot of info out there about implementing matcap shaders, which is the same thing.  In MMD, material alpha is equal to diffuse alpha * texture alpha * sphere map alpha (regardless of whether sphere map is in add mode or multiply mode or even subtex mode.)

**Comment by Hogarth-MMD** [comment]
The eyeglasses and eyes of this model are being rendered completely opaque in Blender, but they display fine in MMD with the correct transparency. Is this an mmd_tools issue? I'm curious to understand why this happens.

**Comment by nathanvasil** [comment]
Because the transparency is being provided by the sphere map, which MMD Tools ignores.

**Comment by powroupi** [comment]
Okay, I've updated it. It will use all texture slots that influence diffuse color or alpha. (supports coordinates mapping `UV` and `Normal`) And before converting materials, you may disable toon/sphere textures if you don't want to convert them. :)

**Comment by nathanvasil** [comment]
Transparency looks great, thanks!

I'm not sure if you want to do a Mix RGB with add spheres, though-- these get lighted inappropriately.  Think of them as environment maps.  IF you want to handle them, and I'm not sure you should, they should probably be handled with an emission shader added (not mixed) to the MMD shader.  Otherwise, you're getting (light1 * (diffuse+(light2 * diffuse)) instead of (light1 * diffuse)+(light2 * diffuse).

Mixing RGB with mult spheres is perfectly appropriate though.  And handling alpha from add spheres like you're doing is perfect.

**Comment by powroupi** [comment]
I just found a simple solution is to set Image Texture node's `Color Space` to `Non-Color Data` for SphereAdd textures, and it's better I think. :smiley: 

By the way, I'm thinking a way to convert Reflection/Specular Color as well, any idea? :thinking:

**Comment by Hogarth-MMD** [comment]
Congratulations and thanks to @powroupi for these recent mmd_tools updates.
Any possibility of also implementing toon textures and ambient color in cycles? Mmd_tools beautifully ready for Eevee and Blender 2.8?

**Comment by nathanvasil** [comment]
> Non-Color Data for SphereAdd textures, and it's better I think

Yeah, that's probably a good idea, but you're still multiplying by scene lighting.  I guess it's probably fine though.

> By the way, I'm thinking a way to convert Reflection/Specular Color as well, any idea?

The start of all my Cycles mats is a diffuse + glossy mixed on the basis of (Fresnel times a constant).  Specular color plugs nicely into glossy color.  I use my own Fresnel node group, Schlick's approximation, I get too much rim from Blender's Fresnel unless I have a ridiculous amount of geometry to occlude the rim.

I was digging around in Raycast yesterday, still digging (that's somewhere I could makes some pull requests if I knew the etiquette etc. for it) and somewhere in all that code, there's a function for conversion of specular exponent to 0-1 range roughness that works well.  I'll keep an eye out for it when I do some more digging, will post here if I see it.

All that leaves is the k * Fresnel for the mix.  Using IOR of 2 is probably safe, even though it won't be right for some things (black diffuse metals).  For the constant, I just eyeball it, but it should go up as luminance(MMDSpecularColor) approaches 1 and as luminance(MMDDiffuse * Texture) approaches 0, (and vice versa, go to 0 for black spec and for white diffuse), although it shouldn't vary much, texel to texel, for a single MMD material.  Don't know how you'd get the average texel, considering a single texture might represent multiple materials, the nature of UV maps, and no imageTextureFiltered node for Cycles-- you could do your own image processing I guess, but that's more work than it's worth.

But, once you have a value like that, I'd say start by trying MMDSpecular minus Diffuse, remap from (-1,1) range to (0,1) and multiply it by your Fresnel to control the mix.

Edit: Note that this is actually the best way to represent an add-sphere as well.  Add-spheres and specular both represent the same glossy shader.  While there's a lot of information that gets lost by baking it to sphere map, it would be possible to reconstruct some of it through image analysis.  Glossy color is at least max individual RGB values for the sphere map, and an IOR/Fresnel could be approximated by doing a radial blur on the sphere map and seeing how the value/transparency values change as you go from the edge to the center.  As sphere/diffuse approaches infinity, the mix approaches 1, same as with specular.  You might be able to get roughness from frequency analysis-- as the sphere data frequency increases, roughness decreases.  For some things, like skin, you'd get inappropriately colored spec, baked into the sphere map, but for some things, like metals, you'd probably get more info out of a sphere map (IOR) than out of specular settings.

**Comment by nathanvasil** [comment]
Here we go, line 674 of https://github.com/ray-cast/ray-mmd/blob/8d961c986f0ba473e66bfb077a0f4e18490c79b1/Materials/material_common_2.0.fxsub .  Notice that it's smoothness, not roughness, and notice the next two functions that suggests it should be mapped to inverse squared rather than just inverse.  Which is in keeping with what it looks like.  Not sure what distribution Raycast is using, but raycast's inverse smoothness squared ought to be about in line with roughness sent Beckmann distribution, just eyeballing it.

**Comment by powroupi** [comment]
Okay, I decided to convert it in simple way at the moment, currently the default values of glossy are
```python
shader.glossy_color = blender_material.SpecularColor
shader.glossy_rough = 1/blender_material.SpecularHardness
```
so that it is easier to tweak the nodes of MMDBasicShader group in the way you like.

Also, `mmd_tools` can display correct SubTexture now. :smile:
