### ISSUE TITLE
I can't export a xps model to pmx, here is the error that I had :

### ISSUE THREAD

**Issue by Omizuri** [powroupi/blender_mmd_tools#164]
Hello ! I'm a mmd user, and I want to convert few models that come from games. But those models are for another program called xps, I tried to follow tutorials, but after importing the xps file (with a plug in) in blender 2.77, I immediately export to a pmx file in blender, but when I write the name of the file, and click on "export pmx file", this message appears : 
![capture](https://user-images.githubusercontent.com/41402288/42913849-b9d37d80-8ae6-11e8-9e90-6b0c673a9ccc.PNG)
and I tried with different models, and I tried to install different blender mmd tools, but it doesn't work :(
Please help me !

**Comment by Hogarth-MMD** [comment]
You can find various tutorials here, including a tutorial about model conversion:
https://github.com/powroupi/blender_mmd_tools/wiki/Links-to-mmd_tools-Tutorials

To avoid that error, I think that you need to click the mmd_tools Convert Model button with the armature object of your model selected to be the active object.

**Comment by powroupi** [comment]
See similar issue powroupi#193.
