### ISSUE TITLE
Exporting VMD from F-curve modifiers?

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#168]
Is it possible to export a VMD animation from an F-curve modifiers animation? If so, how to do that? Right now I am mostly interested in exporting an f-curves morphs animation. (The VMD file format requires key frames.)

**Comment by nagadomi** [comment]
You can bake f-curve modifiers into keyframe.

1. Select the armature
2. Object Mode
3. 3D View > Tools Shelf > Animation Tab > Bake Action (Bake Data = Pose)
4. (Clean unnecessary channels)

You can change the sampling rate with `frame step` field.

**Comment by Hogarth-MMD** [comment]
Bake action does not work with a shape keys animation, does it?

**Comment by Hogarth-MMD** [comment]
https://download.blender.org/demo/test/test260.tgz

In this file, in the animation folder, is a dolphin model and a dolphin swimming animation. I want to convert the dolphin swimming animation to VMD and upload the dolphin model and animation as a gift for the MMD community.

The animation is a lattice shape keys animation with cycles f-curve modifiers on the lattice shape keys animations, so this is a tricky conversion. 

Converting the lattice shape keys to mesh shape keys is easy. This is just "Apply modifier as shape key". 
The next unsolved problem is editing mmd_tools source code to export a shape keys  animation from a lattice.
Then convert f-curves modifiers to key frames.

**Comment by nagadomi** [comment]
hmm, it seems to be unable to bake shapekey animation with `Bake Animation`. But it is not difficult to implement the same function in blender python.
```python
import bpy

def bake_shapekey(obj, shapekey_name, frame_step=1):
    shapekey = obj.data.shape_keys.key_blocks[shapekey_name]
    action = obj.data.shape_keys.animation_data.action
    fcurve = action.fcurves.find(shapekey.path_from_id('value'))
    frame_start = bpy.context.scene.frame_start
    frame_end = bpy.context.scene.frame_end
    
    # evaluate the shapekey value for each frame
    keyframes = []
    for frame in range(frame_start, frame_end + 1, frame_step):
        keyframes.append((frame, fcurve.evaluate(frame)))
    # insert keyframe to the current action
    for frame, value in keyframes:
        kp = fcurve.keyframe_points.insert(frame, value)
        #kp.interpolation = "BEZIER"
    # remove f-curve modifier 
    # ...

bake_shapekey(bpy.data.objects['Sphere'], 'Key1', 2)
```
Note that  this method is not efficient for cycles fmodifier. However, this method can bake other modifiers such as noise fmodifer.

**Comment by Hogarth-MMD** [comment]
Thanks @nagadomi !! This would be a good new feature for mmd_tools. If @powroupi  wants to add it to mmd_tools that would be very nice. 

Where is the line of code that I need to edit for VMD export?:
if o.type == 'MESH':
change to:
 if o.type == 'MESH' or o.type == 'LATTICE':

**Comment by powroupi** [comment]
Another way is to use [FCurve]->[Key]->[Sample Keyframes] and manually duplicate keyframes in Dope Sheet for cycling.

>Where is the line of code that I need to edit for VMD export?

I've updated VMD import/export of shape key animation (589e9bc), now you can export shape key animation of `LATTICE` object (also include other types of objects which can use shape keys). :smile:

**Comment by Hogarth-MMD** [comment]
The code of @nagadomi seems to work flawlessly with Suzanne the monkey, but when I try it with the dolphin.blend lattice, I get an error message which says that the fcurve is a Nonetype object. I don't understand why this is happening.

**Comment by Hogarth-MMD** [comment]
"manually duplicate keyframes in Dope Sheet for cycling"

Do you mean manually copy and paste keyframes again and again and again and again for every shape key? I wish to avoid this.

**Comment by Hogarth-MMD** [comment]
If this does not impose too much on the time of @nagadomi and @powroupi , it would be helpful if you would test your code and test your instructions on the dolphin.blend file. This is confusing me when your code and your instructions don't seem to work on the dolphin lattice animation.

**Comment by Hogarth-MMD** [comment]
Thank you @powroupi for adding this beautiful new feature to mmd_tools to export VMD animations from a lattice and from other types of objects. This VMD export seems to work flawlessly. 

BUT the exported VMD animation does not work in MMD because the shape key values have some negative values and also values slightly greater than 1.0 (1.00498).  I have not thought of a solution to this problem. The minimum values of the lattice shape keys are -1.0, which is not accepted by MMD.

**Comment by Hogarth-MMD** [comment]
```python
fcurve = action.fcurves.find(shapekey.path_from_id('value'))
```
After executing this line of code by @nagadomi , the value of fcurve is None. I don't understand why this happens.

**Comment by nagadomi** [comment]
@Hogarth-MMD 
`data_path` of that fcurve is formatted `key_blocks[1].value` instead of ` key_blocks ['Key 1'].value`. I think that the file was created with a very old version of Blender. 
It can be fixed as follows.
```python
    fcurve = action.fcurves.find(shapekey.path_from_id('value'))
    if fcurve is None:
        data_path_old = "key_blocks[%d].value" % list(obj.data.shape_keys.key_blocks).index(shapekey)
        fcurve = action.fcurves.find(data_path_old)
```
~Edit: I do not know if vmd exporter supports this old format data_path.~

**Comment by Hogarth-MMD** [comment]
```python
import bpy

def bake_shapekey(obj, shapekey_name, frame_step=1):
	shapekey = obj.data.shape_keys.key_blocks[shapekey_name]
	action = obj.data.shape_keys.animation_data.action
	fcurve = action.fcurves.find(shapekey.path_from_id('value'))
	if fcurve is None:
		data_path_old = "key_blocks[%d].value" % list(obj.data.shape_keys.key_blocks).index(shapekey)
		fcurve = action.fcurves.find(data_path_old)
	frame_start = bpy.context.scene.frame_start
	frame_end = bpy.context.scene.frame_end

	# evaluate the shapekey value for each frame
	keyframes = []
	for frame in range(frame_start, frame_end + 1, frame_step):
		keyframes.append((frame, fcurve.evaluate(frame)))
	# insert keyframe to the current action
	for frame, value in keyframes:
		kp = fcurve.keyframe_points.insert(frame, value)
		#kp.interpolation = "BEZIER"
	# mute (not remove) f-curve modifiers
	for m in fcurve.modifiers:
		m.mute = True


for sk in bpy.context.active_object.data.shape_keys.key_blocks:
	if sk.name != 'Basis':
		bake_shapekey(bpy.context.active_object, sk.name, 2)

# Every 2 key frames of animation are key framed. 
# In the final version the user should have a choice of the number of frames between key frames.
```

**Comment by Hogarth-MMD** [comment]
Okay, above is the python script which is needed to convert an F-curves modifiers shape keys animation to key frames, by @nagadomi , with a few edits by me. And thanks to @nagadomi , it now even works with weird ancient Blender files. :+1: 

@powroupi is wonderfully generous with his time. This project to make a dolphin swim in MMD is just for fun and to stimulate the improvement of mmd_tools. So @powroupi can decide when he wants to add support for shape key values which are outside of the 0-1 range.

**Comment by powroupi** [comment]
>BUT the exported VMD animation does not work in MMD because the shape key values have some negative values and also values slightly greater than 1.0 (1.00498).

Hmm, I've tested it, and you can enter negative values without any problems in MMD, and the exported VMD animation works fine in MMD and Blender. :confused: 

Steps for VMD:
1. Select `Lattice` object, optionally set frame end to 56
2. Run `bake_shapekey` script of @nagadomi / @Hogarth-MMD (frame_step=1)
3. Export to VMD with `Use Frame Range` enabled

Steps for `Dolphin`:
1. Manually create shape keys for `Dolphin` object (using `Apply as Shape Key` function)
2. Remove `Lattice` modifier(s) of `Dolphin` object
3. `mmd_tools`->[Create Model], then [Attach Meshes to Model]
4. Select the armature object, then [Convert Model] (for converting MMD materials), optionally tweak MMD material, mesh object's location/rotation
5. Export to PMX

**Comment by Hogarth-MMD** [comment]
@powroupi wrote:
Hmm, I've tested it, and you can enter negative values without any problems in MMD, and the exported VMD animation works fine in MMD and Blender."

Sorry, I am very confused. I tested it also in MMD. My Dolphin doesn't move. The slider controls in MMD are 0 to 1, so how can you say that negative values of morphs are possible in MMD? I am using MMD 9.31 Direct X version. Are negative values of morphs a new feature of MMD that I know nothing about?

**Comment by Hogarth-MMD** [comment]
I was using a dolphin PMD model which I exported from Blender with pymeshio some time ago. I just tried it with a dolphin PMX model exported with mmd_tools and the dolphin seems to be swimming fine in MMD. So maybe PMX supports negative morph values but PMD does not support negative morph values?

**Comment by nathanvasil** [comment]
.pmd's support negative morphs as well.  This isn't new.  To enter a morph outside the 0,1 range in MMD, use the numeric entry box instead of the slider for the morph.

**Comment by Hogarth-MMD** [comment]
Dolphin pmx model and dolphin vmd swimming animation download:
https://sta.sh/02c5ef3ja7c

In converting this model and this animation, I used some weird Blender add-on, but sorry, I don't remember the name of it. :smile:
Thanks to everyone who helped!

**Comment by Hogarth-MMD** [comment]
![dolphin preview](https://user-images.githubusercontent.com/10057979/44848822-26884680-ac26-11e8-8f2f-1518d7f853a1.jpg)
