### ISSUE TITLE
python bone orientation question

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#169]
If I am creating a new bone with Python and I want the (edit mode) X-axis or Z-axis of this bone to be pointing towards a certain direction, how do I do that?

**Comment by nathanvasil** [comment]
You might find it useful to inspect what's happening in the console when you place a cursor and then use ctrl-n->cursor on a selected bone in edit mode (that's one way to set the local Z axis pointing to a particular location.)  Another option here would be to create a temporary locked track constraint (lock Y axis), apply the pose as resting pose (ctrl-a in pose mode), then delete the constraint.

**Comment by Hogarth-MMD** [comment]
I just figured this out.  This is related to bone roll.

vector of the x axis (read only):
bpy.context.active_object.data.edit_bones[0].x_axis

vector of the z axis (read only):
bpy.context.active_object.data.edit_bones[0].z_axis

bpy.context.active_object.data.edit_bones[0].roll

So how is bone roll mathematically related to vector of x or z axis?
The y axis is decided simply by the locations of the head and tail.

**Comment by nagadomi** [comment]
`roll` can be changed with `align_roll(z_axis)`. 
https://docs.blender.org/api/current/bpy.types.EditBone.html#bpy.types.EditBone.align_roll
`y_axis = (bone.tail - bone.head).normalized()`
`x_axis = y_axis.cross(z_axis)`
`z_axis` can be changed with `align_roll`.  It is assumed to be an orthogonal vector of y_axis. so `z_axis.dot(y_axis) == 0`, also `x_axis.dot(y_axis) == 0, x_axis.dot(z_axis) == 0`
`roll` is a rotation angle around y_axis. but I do not know where 0° is.

Also, you should use https://blender.stackexchange.com or https://blenderartists.org for common questions of blender.

**Comment by Hogarth-MMD** [comment]
Thanks to @nathanvasil and @nagadomi  for their helpful information! Closing this issue.
