### ISSUE TITLE
Material morph weirdness

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#17]
Check out http://www.mediafire.com/download/8cbt1xc9j4s2i9a/sugianytoolstest.zip .  toolstest.pmx is just the main model imported, separated, rejoined, and exported.

Bone and material morphs have been altered between the import and the export.  Check out morph 97 in the original, rewritten to 102 in the new.  The original is a bit redundant, probably from an import, doing a multiply 0 on all materials and on one material, but this is okay with MMD.  After running it through sugiany devtest tools, the all-materials portion of the morph is lost.

Another example of this is morph 87 in the new pmx.

**Comment by powroupi** [comment]
Is the order of morphs really important? This addon just put those together according to their type (vertex morphs, bone morphs, material morphs, uv morphs, group morph), just like the morph tools panel in blender. :confused: 

> After running it through sugiany devtest tools, the all-materials portion of the morph is lost.

Okay, i think that issue is solved now! :smile:

**Comment by nathanvasil** [comment]
Oh, I said sugiany again, I tried to edit it but I missed an instance :(  I meant your version, powroupi.

Order of morphs doesn't matter as far as I can tell (well, it affects display, but no biggie).  I just mentioned the numbers to make it easier to find in both files.  It's not just putting morphs together.  It's dropping the all-materials portion of the morph, at least when a single morph contains both an all-materials effect and an effect on another material.

**Comment by powroupi** [comment]
> It's dropping the all-materials portion of the morph

This should be solved now, i updated my branch earlier today. Try download it again -> [dev_test](https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip) :smile:

**Comment by nathanvasil** [comment]
Oh, sorry, didn't understand.

I tested briefly.  It looks okay now.
