### ISSUE TITLE
imported pmxmodel has not shadow and physical operations

### ISSUE THREAD

**Issue by Mainlst** [powroupi/blender_mmd_tools#170]
When I imported pmxMMD model,it had not shadow and physical operations.How I do?
left  after imported model
right original model

PC
windows10 64bit blender2.79 mmd_tools ver.0.6.0
![blender](https://user-images.githubusercontent.com/35127783/44789668-23666980-abd8-11e8-8d7e-1f418d386274.PNG)

**Comment by powroupi** [comment]
How did you create the "imported model"? If you import original model to Blender with default import options/settings and then export it without any change, save to the same folder, you should get the same model (with shadow and physics). :confused:

**Comment by Mainlst** [comment]
OK,I could solve this issue.I mistake way of export.I mistake plugin kind.
and Should I To export MMD model,create a mmd model root object first?I didn't understand it.

thanks very much.☺

**Comment by Mainlst** [comment]
I could create a MMD model.I am very happy.😊
