### ISSUE TITLE
Tutorial creating and editing morphs: material, group, uv, bone

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#172]
EDIT: All of this tutorial information is now in the mmd_tools wiki:

How to create and edit Material morphs, Group morphs, Bone morphs, UV morphs
https://github.com/powroupi/blender_mmd_tools/wiki/How-to-create-and-edit-Material-morphs,-Group-morphs,-Bone-morphs,-UV-morphs
  
  

How to create and edit a material morph using a temporary "Work Material":  
  
1. In the Morph Tools panel of mmd_tools, select the [Material] button, for the material morphs category of your model's morphs.  
2. Add a new material morph by clicking on the + button. A new material morph will then appear listed immediately below whichever material morph is active in the list of material morphs.  
3. Give your new material morph a Japanese name and an English name.  
4. Add a material to this material morph by clicking on the + button (on the right of the Material Offsets list box).  
5. Beside "Related Mesh:", select the mesh object that you want to work on.  
6. Beside "Material:", select a material that you want to morph.  
7. Click [Create Work Material] .  
8. Adjust the settings for your working material.  
9. Click [Apply] .  
10. Click [Clear] .  
11. Add another material, repeating steps 4 to 10, until your material morph is morphing all of the materials that you want it to morph.  
12. You can then save this material morph that you have created by exporting your model to a .pmx file or by saving a .blend file.  
  
  
How to create and edit a material morph without using a temporary "Work Material":  

The advantage of using a temporary "Work Material" is that you can see the effect of your material morph being previewed on your model in the 3D View window. You can edit your material morph without creating a "Work Material", however. Simply follow the instructions above, but skip steps 7,9, and 10. In other words, you don't click need to click on these 3 buttons: [Create Work Material], [Apply], [Clear], if you are editing a material morph without using a temporary "Work Material".

**Comment by Hogarth-MMD** [comment]
How to create and edit a group morph:  
  
  
1. In the Morph Tools panel of mmd_tools, select the [Group] button, for the group morphs category of your model's morphs.  
2. Add a new group morph by clicking on the + button. A new group morph will then appear listed immediately below whichever group morph is active in the list of group morphs.  
3. Give your new group morph a Japanese name and an English name.  
4. Add an existing morph to this group morph by clicking on the + button (on the right side of the Group Offsets list box). Below the Group Offsets list box, use the list menu of morphs categories and the text input box of morphs names, to choose which morph will be added to the group morph.  
5. On the right side of the name of this morph in the Group Offsets list box, input a decimal number value, to set the value of this morph in the group morph. This value should usually be a decimal number from 0.000 to 1.000, but a negative decimal number or a decimal number greater than 1.000 are also possible. The default value is 0.000, so if you don't change this value away from its default value, the group morph will do nothing.  
6. Add another morph, repeating steps 4 to 5, until your group morph is morphing all of the morphs that you want it to morph.  
7. You can then save this group morph that you have created by exporting your model to a .pmx file or by saving a .blend file.

**Comment by Hogarth-MMD** [comment]
To edit a UV morph in Blender:

1. In the mmd_tools Morph Tools panel, select the UV morph that you want to edit.
2. Click [View] to create a temporary UV map of the UV morph data.
3. Click [Edit] to edit this temporary UV map in Blender's UV Editor. The vertices of the UV morph will be selected in Edit mode of the 3D View window, and in Blender's UV Editor.
4. After you have finished editing the UV morph, click [Apply] to add the edited UV morph data into the UV morph of the MMD model. The vertices that you edited must be selected  because [Apply] will only calculate selected vertices. Existing UV morph data will be overwritten by the UV data of the selected vertices.
5. Click [Clear] to delete the temporary UV map.

**Comment by Hogarth-MMD** [comment]
I don't have a tutorial for bone morphs yet. I am having a problem with this.

**Comment by nathanvasil** [comment]
Thanks Hogarth, it's great to have that information all in one place.

**Comment by Hogarth-MMD** [comment]
The default value of a morph in group morph should be 1.000 . 
And I just realized that the value of a morph in a group morph can be less than 0.000 or greater than 1.000 .

**Comment by powroupi** [comment]
> 7. Click [Create Work Material].

If you know the math of material morph, you can edit the values of morph data directly without using temporary material.

> 4. After you have finished editing the UV morph, click [Apply] to add the edited UV morph data into the UV morph of the MMD model.

Make sure to select the vertices you edited or select all vertices in 3d view, because [Apply] will only calculate selected vertices and overwrite UV morph data.

**Comment by Hogarth-MMD** [comment]
When editing a UV morph, what happens when the user clicks on [Apply]? This needs to be clarified. 
Is the existing UV morph data completely erased and then replaced by the UV data of the selected vertices? 
If no vertices are selected, will the UV morph be completely erased? 
Or will the previous UV morph data of the unselected vertices be preserved in the edited UV morph?

**Comment by powroupi** [comment]
>Is the existing UV morph data completely erased and then replaced by the UV data of the selected vertices?

Yes.

>If no vertices are selected, will the UV morph be completely erased?

Yes.

Ps. The data will be stored in vertex groups, you can weight paint `UV_*` vertex groups (or assign weights) if you know how to edit it, see https://github.com/powroupi/blender_mmd_tools/issues/131#issuecomment-386942874

**Comment by Hogarth-MMD** [comment]
To edit an already existing bone pose morph:  
  
1. Select the armature object of your MMD model to make it the active object.  
2. Enter Pose mode.  
3. In the Morph Tools panel of mmd_tools, select the [Bone] category and in the list of bone morphs select the bone morph that you want to edit to make it the active bone morph.  
4. At the right side of the mmd_tools Morph Tools panel, click on the arrow to display a list menu. In this list menu, select [Copy Morph]. A copy of your bone morph will then appear in the Morph Tools panel. Now you can edit this copy of your bone morph safely, without overwriting and losing the data of your original bone morph.  
5. Immediately below the list box of morphs in the morph tools panel, you will see 3 buttons: [View], [Apply], and [Clear]. To edit the bone morph, you don't need to use any buttons other than these 3 buttons.  
6. Click [View] to copy the bone pose of your bone morph onto the active armature. You will then see the bones of the armature rotated and/or moved into the bone pose of your active bone morph.  
7. Edit the armature pose by rotating and/or moving its bones using the tools that Blender provides for this purpose.  
8. Click [Apply] to store the armature pose into the active bone morph. The data of the active bone morph will then be replaced and overwritten with the data of the armature's pose.  
9. You can then save the bone pose that you have created by exporting your model to .pmx or by saving a .blend file.  
  
  
To create and edit a new bone pose morph:  
  
1. Select the armature object of your MMD model to make it the active object.  
2. Enter Pose mode.  
3. In the Morph Tools panel of mmd_tools, select the [Bone] button, for the bone morphs category of your model's morphs.  
4. Add a new bone morph by clicking on the + button. A new bone morph will then appear listed immediately below whichever bone morph is active in the list of bone morphs.  
5. Give your new bone morph a Japanese name and an English name.  
6. Immediately below the list box of morphs in the Morph Tools panel, you will see 3 buttons: [View], [Apply], and [Clear]. To edit your new bone morph, you don't need to use any buttons other than these 3 buttons.  
7. If the bones of your armature already have a pose on them which you DO NOT want to be part of your bone pose morph, click [Clear]. All poses of the selected bones of the active armature will then be cleared and you will see the selected bones reset to their default location, rotation and scale.  
8. Edit the armature pose by rotating and/or moving its bones using the tools that Blender provides for this purpose.  
9. Click [Apply] to store the armature pose into the active bone morph. If you have already applied an armature pose into the active bone morph, that data of the active bone morph will then be replaced and overwritten with the data of your armature's current pose.  
10. You can then save the bone pose that you have created by exporting your model to a .pmx file or by saving a .blend file.
