### ISSUE TITLE
Unable to export a xps model to pmx. There nothing appears in a destination folder.

### ISSUE THREAD

**Issue by Sstingray** [powroupi/blender_mmd_tools#178]
Title. No erros. No messages. Just nothing. If i previously improting model in pmd/pmx formart exporting works fine. Also its wont work with any different 3d models format, no matter if it include bones or its just mesh file.

**Comment by Sstingray** [comment]
Pressing "Convert" in MMD plugin resolved the issue.

**Comment by Hogarth-MMD** [comment]
mmd_tools wiki tutorials are here, including a tutorial about model conversion:
https://github.com/powroupi/blender_mmd_tools/wiki/Links-to-mmd_tools-Tutorials
