### ISSUE TITLE
mmd_tools_helper is broken

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#182]
In a recent mmd_tools commit, @powroupi  made a completely unnecessary change to the mmd_tools API which breaks the mmd_tools_helper [Add Display Panel Groups] operator and which breaks the instructions in 2 of my mmd_tools github wiki tutorials.

https://github.com/powroupi/blender_mmd_tools/commits/dev_test
Commits on Nov 2, 2018
Change MMDDisplayItemFrame.items to MMDDisplayItemFrame.data and refi…
https://github.com/powroupi/blender_mmd_tools/commit/7723c706fc6f14dbd6da18355e1713aaf9b7d364

If someone wants the most recent version of mmd_tools which works with mmd_tools_helper, you can download it here:
https://github.com/powroupi/blender_mmd_tools/archive/55a650dddec9e4000434e8f0de3301075504ae7f.zip

I have absolutely no plan or intention of updating mmd_tools_helper add-on every time that @powroupi feels like behaving in this dictatorial, unpredictable, discourteous and inconsiderately time-wasting way.

**Comment by powroupi** [comment]
Sorry for that change. Because the 'items' overwrites [CollectionProperty.items](https://docs.blender.org/api/2.79/bpy.types.CollectionProperty.html) function (inherited from bpy_struct.items), I made the change to prevent this conflict. :)

**Comment by powroupi** [comment]
Okay, I've created a tag v0.6.0 (see [Tags](https://github.com/powroupi/blender_mmd_tools/tags)). You can download [https://github.com/powroupi/blender_mmd_tools/archive/v0.6.0.zip](https://github.com/powroupi/blender_mmd_tools/archive/v0.6.0.zip) which will be the same as your link. After that I'll try to make some compatible changes for blender 2.8. :smile:

**Comment by Hogarth-MMD** [comment]
> Sorry for that change. Because the 'items' overwrites [CollectionProperty.items](https://docs.blender.org/api/2.79/bpy.types.CollectionProperty.html) function (inherited from bpy_struct.items), I made the change to prevent this conflict. :)

Hello @powroupi! Thank you for your replies. In spite of this "conflict", everything related to the MMD Display panel items has been working correctly, in both mmd_tools and mmd_tools_helper, so because of that fact, I request and recommend that you make a new commit which reverts the mmd_tools API for Display Panel items back to the previous mmd_tools API for Display Panel items, thereby undoing the change which you made. Inheriting and overriding functions and variables from a class is reasonably common and permitted in python script writing, so I don't see this as being a problem.

If something is working fine and if something is not broken, there is a wise saying which says:
"If something is not broken, then don't fix it."

**Comment by Hogarth-MMD** [comment]
The ball is in the court of @powroupi with this issue.

Does @powroupi have a better alternative to offer?

**Comment by nagadomi** [comment]
@Hogarth-MMD
I think that you should follow upstream changes, or fork the repo and develop/maintain on your own.
Anyway, blender 2.8 will break all addons. :cry:

**Comment by Hogarth-MMD** [comment]
The change that @powroupi made to the display panel items is not related to Blender 2.8, is it?

**Comment by powroupi** [comment]
That change is not related to Blender 2.8, I just think that we should not overwrite CollectionProperty.items() function. You could simply modify [mmd_tools/properties/root.py](https://github.com/powroupi/blender_mmd_tools/blob/ac61f8a8ff78a38ea6c04ef37b5f6f343f4e3d91/mmd_tools/properties/root.py#L217) to revert the change locally:
```python
    data = CollectionProperty(
        name='Display Items',
        type=MMDDisplayItem,
    )
    @property
    def items(self):
        return self.data
```

**Comment by Hogarth-MMD** [comment]
Hello @powroupi!

1. Wasting my time at this time has potentially very cruel and tragic results. This is grimly serious. Inflicting this time-wasting fiasco on me at this time is very bad timing. I do not have time to waste at this time. I need this distraction and this waste of time to be completely ended. Then I need to take a break from mmd_tools development so I can do my personal problem-solving without any distraction. I don't know much time will be needed for this.

2. Updating mmd_tools helper is not so straightforward. If I fix it, it will be broken for people who are using an earlier version of mmd_tools. I cannot fix it without simultaneiously breaking it.

3. Will @powroupi please send to me a pull request that fixes mmd_tools helper, including an error message for people who are using an earlier version of mmd_tools?

3. Will @powroupi then send to me his guarantee that the API of mmd_tools will be completely frozen and that it will not be changed in the future?

**Comment by powroupi** [comment]
1. Sorry for the bad timing, but it's not necessary to update your addon immediately, and you don't have to update it if you're not interested. :)

2.&3. I've made a PR for you, it should work now, you can merge it when you have time. :smile:

4. I think the only thing left of my plan is to make `mmd_tools` work on Blender 2.8, no more plans to update anything anymore. So, it will be the final version of my fork if everything works fine on Blender 2.8. Thanks everyone who helps me to improve this addon, feel free to fork & continue it if you're interested. Thank you. :kissing_heart:

**Comment by Hogarth-MMD** [comment]
Thank you @powroupi! This is an excellent fix. This fix even gives mmd_tools helper backwards and forwards compatibility with all versions of mmd_tools. Thank you for teaching me how to do this.

In the future, I recommend to @powoupi and to anyone else who is reading this comment:
You should never break someone's add-on, and never break someone's programming code,  without simultaneously sending to this person a fix for this broken code. There are various factors which may cause an excessive delay or excessive wasted time for someone in fixing his own broken code.

And I understand that in the future I should just ask for @powroupi's help, instead of feeling confused and assaulted. And if I said anything that seemed ungrateful to @powroupi, please accept my apology for this misunderstanding.

Closing this issue.
