### ISSUE TITLE
Request changing the "Convert Material For Cycles" shader

### ISSUE THREAD

**Issue by repsanims** [powroupi/blender_mmd_tools#183]
Hey, I've been using this feature and it seems quite hard to change every single material to get supported in blender 2.80.

As you can see here I have the node of the default conversion of my 'MMD' model to 'Cycles':
![screenshot 33](https://user-images.githubusercontent.com/45067376/48900239-74f35d00-ee84-11e8-9ac1-76a9a6a864ed.png)

But then it would be a problem for later use in Blender 2.80 using the Eevee engine as you can see here:
![screenshot 36](https://user-images.githubusercontent.com/45067376/48900849-21820e80-ee86-11e8-8e9d-80570c10a45d.png)
![screenshot 37](https://user-images.githubusercontent.com/45067376/48900850-23e46880-ee86-11e8-91f5-0dab9050492f.png)

So I'm suggesting a change in shader from the add-on shader to a more friendly Blender supported Principled shader that look something like this:
![screenshot 34](https://user-images.githubusercontent.com/45067376/48901048-c4d32380-ee86-11e8-9668-caf9d258f73c.png)

Thanks is advance.

**Comment by nagadomi** [comment]
I think that it would be better if we can select `MMDBasicShader`,` PrincipledBSDF`, `Emission` or GroupNode on Convert Material operator. 
@repsanims 
You can edit MMDBasicShader with Tab key, and replace all materials. To use TransparentBSDF(MMDAlphaShader) on EEVEE, it needs to change the blend mode on the material tab.

**Comment by ptrthomas** [comment]
sorry to hijack this thread - but can someone help me understand what will happen to mmd_tools with EEVEE - if it is documented somewhere, just point me to it, thanks.

I'm seeing so many great examples in my feeds now and want to experiment with MMD when I get a chance

**Comment by powroupi** [comment]
@repsanims, I think modify MMDBasicShader is the easiest way for now. :)

I'm thinking a way to handle shader (material node) stuff, ideally a node group with most parameters of mmd_material, so that users can modify/change shaders easier. But I don't have detailed solution yet. :cry:

@ptrthomas, currently the latest mmd_tools use bpy_extras.node_shader_utils.PrincipledBSDFWrapper to update materials of Blender 2.8. It's a temparary solution, because handling material nodes is a little tricky, and I'd like to wait for Blender 2.8 stable before making further changes about shaders. :)

**Comment by ptrthomas** [comment]
@powroupi ok thanks. so if I upgrade to 2.8 and install the addon like in the old days - all the usual stuff will work ?

**Comment by powroupi** [comment]
>all the usual stuff will work ?

Yes, I think all `mmd_tools` stuff will be the same as usual, the only change now is that the `MMD` tool tab is moved to the right side `N` panel for Blender 2.8. :smile:

**Comment by ptrthomas** [comment]
@powroupi thank you for all the info !

**Comment by repsanims** [comment]
> I'm thinking a way to handle shader (material node) stuff, ideally a node group with most parameters of mmd_material, so that users can modify/change shaders easier. But I don't have detailed solution yet. 😢

@powroupi It's ok for now, I'm just looking for more photorealistic render in a more efficient way.
MMD itself have a great shader support and a physic built in, but it doesn't give a realistic result. The reason I use Blender for rendering my MMD is because it's is more photorealistic using the ray-tracing engine, and bake-able physic feature so it can looks more natural.

Anyway, the default conversion is ok. This is just a suggestion, but I will appreciate it if you ever implement it.
Thank you for the reply!
