### ISSUE TITLE
Blender 2.8 Beta released

### ISSUE THREAD

**Issue by Darkblader24** [powroupi/blender_mmd_tools#184]
**Blender 2.80 Beta** is now live, and the **Python API** is final.
https://www.blender.org/
Bug Reports are now open to the public.

**Comment by powroupi** [comment]
Got it! Thanks for the information. :smile:

**Comment by Darkblader24** [comment]
No problem :)
Love your progress on the 2.8 update so far, thank you so much!

**Comment by Hogarth-MMD** [comment]
The Blender 2.8 Release Notes
https://wiki.blender.org/wiki/Reference/Release_Notes/2.80

**Comment by Hogarth-MMD** [comment]
Eevee user manual
https://docs.blender.org/manual/en/dev/render/eevee/

**Comment by Hogarth-MMD** [comment]
How do we send bug reports and feature requests to the Blender 2.8 developers?

**Comment by ptrthomas** [comment]
Blender 2.8 final should be out July 30 ! https://www.blendernation.com/2019/07/29/blender-2-80-final-release-scheduled-for-july-30/

we ❤️ you @powroupi  !
