### ISSUE TITLE
[question] how to re-apply physics

### ISSUE THREAD

**Issue by ptrthomas** [powroupi/blender_mmd_tools#189]
I admit that I have never fully understood what happens when you use the "rebuild" options.

here's my situation, I got an MMD motion that was for a non-standard model. so before importing the motion I had to take the`UpperBody` bone and make its parent the `LowerBody` instead of `Waist`.

After that I tried various combinations of `clean` and `build` but many rigid bodies stay in place.

what's the simplest way I can solve this ? any insights on how physics for bones / rigid bodies are managed in blender will be appreciated !

**Comment by powroupi** [comment]
Make sure [Rigid Body World](https://docs.blender.org/manual/en/dev/physics/rigid_body/world.html#settings) is enabled and **Start/End** of [Rigid Body Cache](https://docs.blender.org/manual/en/dev/physics/rigid_body/world.html#rigid-body-cache) are set properly. It's better to [Build] physics at the start frame of Rigid Body Cache, you may need to jump to the start frame or [Bake All Dynamics] before playing animation.

The following are the minimum steps to test rigid bodies and joints of your PMD/PMX model in Blender:
1. Open a new empty scene in Blender, enable `mmd_tools` addon.
2. Import a PMD/PMX file with import options: Scale 0.2, enable only Armature&Physics parts.
3. Make sure current frame is the first frame, and [Build] imported model.
4. Toggle visibility of Rigid Body objects, and [Play] to check the result (you can also move root object while playing to test it).

If everything is fine, then you can go with VMD motions:
1. Open a new empty scene in Blender, enable `mmd_tools` addon.
2. Import a PMD/PMX file with import options: Scale 0.2, all parts.
3. Import a VMD file to the model with import options: Scale 0.2.
4. Make sure Start/End of Rigid Body Cache match the motion's length.
5. Make sure current frame is at first frame, and [Build] imported model.
6. [Play] to check the result.
(7. [Clean] the model and go to first frame before importing another VMD motion.)

**Comment by ptrthomas** [comment]
thank you @powroupi !
