### ISSUE TITLE
[question] shading in blender 2.8

### ISSUE THREAD

**Issue by ptrthomas** [powroupi/blender_mmd_tools#192]
just started and am quite lost:

<img width="761" alt="image" src="https://user-images.githubusercontent.com/915480/50375839-17406500-062a-11e9-9465-5674a749a176.png">

I'm not able to get shading to work at all. some error about backface_culling

**Comment by nagadomi** [comment]
Maybe your blender 2.8 or mmd_tools is a bit old.
No error with blender2.8 branch and latest mmd_tools.

**Comment by ptrthomas** [comment]
@nagadomi thanks I used the latest branch of mmd_tools and rigid bodies and the physics "build" are a lot better.

I'm using the Dec 22 version of Blender 2.8 

when you click on the "Shadeless" button does it work for you ?

![image](https://user-images.githubusercontent.com/915480/50380006-eb040300-0680-11e9-9706-a88632a2b08b.png)

**Comment by powroupi** [comment]
The functions of shading buttons for Blender 2.8 might still need some tweaks. Currently, you might directly use settings of viewport Shading and Overlay. :)

ps. you might need to unhide Rigid Bodies and Joints before clicking [Build] button. Currently, SDEF functions and Physics may not stable yet. :cry:

**Comment by ptrthomas** [comment]
@powroupi thanks for the tip to un-hide rigid bodies AND joints. that makes a difference !

shall I keep this ticket open for the shading buttons.

**Comment by powroupi** [comment]
@ptrthomas, you can close it if your questions got answered. I'd like to wait for Blender 2.8 final before fixing those bugs of mmd_tools on Blender 2.8. Thank you. :smile:

**Comment by nagadomi** [comment]
@ptrthomas
Shadeless button does not work, but `View3DOverlay` has `show_backface_culling` attribute, so no error occurs, in my env.

**Comment by ptrthomas** [comment]
thanks @nagadomi and @powroupi ! will close for now.

**Comment by ptrthomas** [comment]
thanks everybody for your help ! check out my first test (short) video using Eevee !

https://youtu.be/cXF0oH2DNh0

figured out how to convert each texture and that the MMDAlphaShader does a fantastic job ! is this shader defined in python code somewhere - can someone help point me to it.

any suggestions to achieve a more toon-shader look, is there an easy way to add outlines ?

and maybe I should mix a standard (principled BSDF ?) shader so that it is not 100% shadeless.

I love eevee - the next year is going to be fun

**Comment by powroupi** [comment]
MMDAlphaShader is defined in `create_MMDAlphaShader()` of [cycles_converter.py](https://github.com/powroupi/blender_mmd_tools/blob/dev_test/mmd_tools/cycles_converter.py). On Blender 2.8, `mmd_tools` currently is using MMDShaderDev which is defined in [core/material.py](https://github.com/powroupi/blender_mmd_tools/blob/ac26c55a985d62ae9439a961d27e796444d09069/mmd_tools/core/material.py#L652).

You can go to Blender's [Shader Editor](https://docs.blender.org/manual/en/dev/editors/index.html) window ([Node Editor] on Blender 2.7x), select a node group, then hit [Tab] to tweak/navigate the shader. You can try anything you want, [Principled BSDF], [Shader To RGB] etc.

Click [Create] button of `Edge Preview:` on `mmd_tools` tool tab will create outlines. Alternative way is to use [freestyle outline](https://docs.blender.org/manual/en/latest/render/freestyle/introduction.html#what-is-freestyle) or post processing on Compositing window.

**Comment by ptrthomas** [comment]
thanks @powroupi !
