### ISSUE TITLE
two problems met in the Blender 2.8

### ISSUE THREAD

**Issue by lwp513202035** [powroupi/blender_mmd_tools#194]
At the very first, hearing that you have no more plans to update anything anymore after the MMD-tools working well on Blender2.8, thank you for your selfless dedication on this wonderful plugin, @powroupi 

And , here are some problems I met in Blender2.8 beta. When there are too many rigdbodys and jionts in the MMD model（like a dead or alive character MMD model ）,when I import it into Blender 2.8，blender just becomes so slow . And when I work on the project , it often turns to no response. Besides, building physics in blender 2.8 seems doesn't work right ?

**Comment by powroupi** [comment]
Thank you, you're welcome. :) I will update things that don't take me too much time, I think. :)

>When there are too many rigdbodys and jionts in the MMD model...

It is unavoidable that blender could become slow if there are too many objects in a scene.:cry: You could disable import option [Physics] to prevent importing rigidbodies and joints, or use a MMD model which has fewer rigidbodies and joints. :)

>Besides, building physics in blender 2.8 seems doesn't work right ?

Currently, It only works when rigidbodies and joints are not hidden, and the armature object may need to be in Pose mode. :)

**Comment by lwp513202035** [comment]
> Thank you, you're welcome. :) I will update things that don't take me too much time, I think. :)
> 
> > When there are too many rigdbodys and jionts in the MMD model...
> 
> It is unavoidable that blender could become slow if there are too many objects in a scene.😢 You could disable import option [Physics] to prevent importing rigidbodies and joints, or use a MMD model which has fewer rigidbodies and joints. :)
> 
> > Besides, building physics in blender 2.8 seems doesn't work right ?
> 
> Currently, It only works when rigidbodies and joints are not hidden, and the armature object may need to be in Pose mode. :)

Thanks for the reply. Since it work well in Blender2.79, I import model in 2.79 and build physics in it. Then when I adjust all the things well , I delete the temporary and open it in Blender 2.80 cause I just want to use the EEVEE.
I  just think that the workflow is troublesome ,but if it is unavoidable, maybe I should wait 2.8 to become more perfect .

**Comment by ptrthomas** [comment]
@lwp513202035 one observation as someone who has been experimenting with Eevee for the last week - by default, the MMDShader that mmd_tools applies to all the materials seems to have some performance issues. to check - switch to wireframe or "solid" shader mode (not rendered) and if things are smooth now - that is the problem. when loading some models, all of blender slows to a crawl in "LookDev" and "rendered" view.

I have actually been converting all shaders to custom or MMDAlphaShader by hand in order to get things to work.

**Comment by zeromizkun** [comment]
So Guys how did you get mmd tools in Blender 2.8? for me it wont work the way I usually did it with 2.79, even if I try install manually..

**Comment by powroupi** [comment]
I've updated `mmd_tools` for Blender 2.80 RC2. If you still have issues on Blender 2.80 final release, you may report it then. Thank you. :smile:
