### ISSUE TITLE
[Build] and [Clean] appear to be missing in Blender 2.8?

### ISSUE THREAD

**Issue by ChellyCoco** [powroupi/blender_mmd_tools#195]
Hi, After hours of scrubbing through 2.8s interface, I can't for the life of me find the Build and Clean Rigid Bodies. Searching the Operator in every mode possible also returns nothing. Either I'm doing something horribly wrong in the entirely wrong mode, or these are missing.

I tried building the Rigid Bodies in 2.70a and then exporting both as a .blend and .pmx but it doesn't seem to carry over, so for now I can't see a workaround.

Many thanks for any help pointing me in the right direction!

**Comment by powroupi** [comment]
Hi, @ChellyToys, the tool panel of `mmd_tools` is moved to right side `N` panel (`MMD` tab), everything is still there and most functions should work. :)

Current major issues on Blender 2.8 (lateast is not tested yet):
- [Build]/[Clean] currently only works when rigidbodies and joints are not hidden, and the armature object may need to be in Pose mode.
- SDEF functions may not stable yet ([Bind] and toggle on/off may not work as expected, and crash when [Unbind]).

**Comment by ptrthomas** [comment]
@powroupi is there some explanation of SDEF you can point me to ?

**Comment by powroupi** [comment]
@ptrthomas I think most informations about SDEF are in #162. :smile:

**Comment by ptrthomas** [comment]
@powroupi wow that's a lot ! thanks !
