### ISSUE TITLE
Referencing vertex morphs for exported models

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#198]
Is there a way to reference shapekeys/vertex morphs in a model without exporting and re-importing?  This would be nice so that I could keep everything handy in a .blend file rather than a .pmx.

I've made a simple demo file at https://mega.nz/#!6SIy0CDA!BQoowA2TBE8oMApNibja_a-DW_2yWOpVaVlwXVIXMr0 .  This is a cube with two shapekeys and a group morph.  Is there a way to make the group morph reference the shapekeys?  Is there a way to assign display panels for the shapekeys, for instance, to assign them to "hidden" so that they won't be displayed on the exported model?

**Comment by powroupi** [comment]
> Is there a way to make the group morph reference the shapekeys?

The `Vertex` type of group morph references vertex morph on `Morph Tools` panel, so you need to add vertex morph items manually on `Morph Tools` panel. An easier way is to click [Create] under Menu functions, it will load all shape keys into vertex morphs on `Morph Tools` panel. :)
ps. Rename vertex morph's (JP) name will rename corresponding shape key's name, rename shape key's name will not update corresponding vertex morph's (JP) name.

>to assign them to "hidden" so that they won't be displayed on the exported model?

Once vertex morphs have been added on `Morph Tools` panel, you can change their category to "Hidden". However, you can still add "hidden" morphs into Facial items on `Display Panel` panel. You can use List's filtering options (little plus icon) to show only "Hidden" Facial items, and them remove them as you want.

**Comment by nathanvasil** [comment]
Thanks, that works nicely!
