### ISSUE TITLE
Need help - how to add a rigid body

### ISSUE THREAD

**Issue by ptrthomas** [powroupi/blender_mmd_tools#2]
I've been trying and trying to add just one single rigid body with a dynamic & bone constraint and see it work.  No luck :( Really need a nudge in the right direction.  Here attached is a very simple blend file with a pmx and motion data loaded:

[mmd-arm-test.blend.zip](https://github.com/powroupi/blender_mmd_tools/files/189919/mmd-arm-test.blend.zip)

I added a rigid body to the head bone (static) which is fine.  Now I want to add another bone for hair and am stuck here.  I don't understand how to create the joint, what is the order, is there a naming convention etc.  If you are able to add a rigid body with a dynamic / damped track to this attached file, do let me know the steps to do it and I can take it from there.  Thanks !

**Comment by powroupi** [comment]
I found the problem, to solve this:
1. enable [Rigid Body World] in the scene tab of properties window
2. hit [Clean] button
3. select and delete and re-add your joint using the physics tools of mmd_tools
4. hit [Build] button, and you should get it to work!

Sorry for lack of documents, the common order is that:
You add the rigid body and joint objects when the model is not built and then hit [Build] to see the result.
You need to hit [Clean] before adding more physics.

Another note:
I've modified the code of Build & Clean, so the [Rigid Body World] may not be enabled if the model isn't built successfully.
In this case, you need to re-enable [Rigid Body World] option manually.
And hit [Clean] and then check & fix your physics settings of mmd_tools and [Build] again to see if everything is ok and so on...

About the 3rd step on top, somehow your joint object is not added to the group 'RigidBodyConstraints', and the constraints setting of [Rigid Body World] panel is empty, i'm not sure what cause this, those settings should be setup automatically...

**Comment by ptrthomas** [comment]
Thanks !  Actually I was trying to mix too many things, the armature is actually from here: http://www.blendswap.com/blends/view/66562

So even though I started by creating a creating a root model object from mmd tools, I somehow parented the above armature to it.  Obviously this caused some properties and constraints to be missing.  I'm actually surprised things worked as much as they did !

So thanks, I was able to get things working with your instructions.  Even better, I created a model from scratch using mmd_tools the "right way" and was able to add rigid bodies successfully.  And I tried to modify an existing model and that is working fine also.  I think I understand the order of creating rigid bodies and joints now.  Hopefully we can document this together in the future !

Good to know about the blender "rigid body world" so I can look out for it in the future.  Thanks again for your help.  You can close this issue now.

**Comment by powroupi** [comment]
You are welcome! I'm glad to help. :)
