### ISSUE TITLE
Export animated model as a fbx file WITH SDEF weights

### ISSUE THREAD

**Issue by koaTS** [powroupi/blender_mmd_tools#200]
Hi. I'm currently trying to export the animated mmd model to the other engines such as ue4 or unity.

The problem is that the animated model often has the shrunk arms when they rotated too much. 
This is because MMD model uses SDEF to avoid the arm shrinking problem, but the other engines do not have SDEF.

I knew mmd_tools import all SDEF weights as BDEF so I was OK with this issue. I manually weight painted to fix the problem. But I noticed that mmd_tools actually can store the SDEF information like #162 

I'm kinda new to blender so having hard time to understand the post :( I messed with 'bind' SDEF button and shape keys few times but I just don't see any changes.

Can I export animated model as a fbx file with SDEF weights applied?

**Comment by nagadomi** [comment]
I am not familiar with unity or FBX,
MMD4Mecanim seems to be compatible with SDEF (XDEF).
https://twitter.com/Stereoarts/status/461032739349610496

[MMD4Mecanim](http://stereoarts.jp/)
[Tutorial (Japanese)](http://stereoarts.jp/MMD4Mecanim%20%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB%EF%BC%88%E5%9F%BA%E6%9C%AC%E7%B7%A8%EF%BC%89.pdf)

**Comment by Hogarth-MMD** [comment]
mmd_tools stores the SDEF data of an imported MMD model in 3 shape keys. Blender's FBX exporter is not programmed to interpret those 3 shape keys as being SDEF data. If you can find a PMX importer for ue4 or unity, that is the only thing that might work, that I can think of.

**Comment by Hogarth-MMD** [comment]
To convert the SDEF mesh deformations into a mesh animation, you would need a shape key for every key frame. I'm pretty sure that Blender cannot do that without a special python script being made to do that.

**Comment by Hogarth-MMD** [comment]
I cannot really tell you how or if this would work, but there are 2 file formats (.mdd and .pc2) which can be used to store a mesh animation. 

Blender user manual, mesh cache modifier.
https://docs.blender.org/manual/en/latest/modeling/modifiers/modify/mesh_cache.html

**Comment by koaTS** [comment]
Thank you very much to nagadomi and Hogarth! I really should try both method.

**Comment by Hogarth-MMD** [comment]
Here is the documentation page for Blender's FBX importer and exporter:

http://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/Import-Export/Autodesk_FBX

According to information on this page, the Blender FBX add-on does not support import or export of shape keys.

binary FBX files only.
Version 7.1 or newer.
Missing
Mesh: shape keys.
