### ISSUE TITLE
using multiple translation csv dictionaries

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#201]
In mmd_tools user preferences, I assigned a folder where my csv translation dictionaries are located. I want mmd_tools to automatically combine all dictionaries in that folder into one dictionary and then make a translation. It seems to be impossible to do that. however. I can get one incomplete translation with one dictionary and a different incomplete translation with the other dictionary. If mmd_tools would combine all dictionaries into one dictionary, this would be a nice time-saver for me in developing a new and better translations.csv file.

**Comment by powroupi** [comment]
Possible solutions by searching `concat csv files` on internet... :sunglasses:
