### ISSUE TITLE
Crashes whenever converting material to cycles

### ISSUE THREAD

**Issue by narbartor** [powroupi/blender_mmd_tools#207]
This problem happens whenever I convert the material for cycles. It doesn't happen every time, it just happens whenever it feels like it. There are times when it crashes only once and is fixed the next time I open Blender. Other times, I have to do it several times because it crashes every time. Even times where it just doesnt crash at all, but the next time I use the model, it crashes.

It's not something that just happens with a certain type of model either, happens to all models I use

**Comment by powroupi** [comment]
Yea, you might check #56 to see if there is any solution works for you. I currently can't fix this issue, sorry. :cry:

However, if you only want to use Cycles, you could try modifying [mmd_tools\core\material.py](https://github.com/powroupi/blender_mmd_tools/blob/444800564364667d51059f6b5b36e79ac3bf42ce/mmd_tools/core/material.py#L767) as following (and restart Blender) to make `mmd_tools` use Cycles shader only.

```python
FnMaterial = _FnMaterialCycles
if 0 and bpy.app.version < (2, 80, 0): # <-- modify this line to disable/enable BI function
    FnMaterial = _FnMaterialBI
```

And then you can change to Cycles, and import a MMD model, cycles shader should be there, no longer need to convert material to cycles. And see if there will be any crash. :)

**Comment by narbartor** [comment]
Sadly, it seems to still crash

**Comment by powroupi** [comment]
You might try disable `mmd_tools` and only import some FBX models (Open Blender -> Change to Cycles -> Import FBX file) to see if there will be any crash, this way we can know if it is a problem related to 'mmd_tools`. Thank you. :)

**Comment by narbartor** [comment]
It may be a problem on my computer because I use an xps importer and it doesn't crash when I change the materials to cycles. And in my laptop, MMD Tools doesnt crash Blender when I do it there.
