### ISSUE TITLE
No longer works on latest Blender 2.80 beta version

### ISSUE THREAD

**Issue by Darkblader24** [powroupi/blender_mmd_tools#209]
"RuntimeError: Fehler: 'UL_Morphs' doesn't contain '_UL_' with prefix & suffix"

**Comment by powroupi** [comment]
I guess it need to be changed from `UL_*` to `OBJECT_UL_*` (https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Addons). But I want to wait a few more days to update it. :sunglasses: (API does not seem to have frozen)

**Comment by powroupi** [comment]
@Darkblader24, I've updated it (f0580b3), using `MMD_TOOLS_` as prefix, and it should be fixed now. :smile:

**Comment by Darkblader24** [comment]
Thanks, it works wonderfully 💯
