### ISSUE TITLE
Shading error again

### ISSUE THREAD

**Issue by Darkblader24** [powroupi/blender_mmd_tools#210]
Here is the error: https://i.imgur.com/cs4w4k5.png

**Comment by powroupi** [comment]
Okay, It should be fixed now. I'm not sure how it happens, though. :sweat_smile: I would like to know how `YYYOpenAndImport.py` works. Did you run it via Console without opening Blender?

**Comment by Darkblader24** [comment]
I start Blender via a bat file which contains this line:
`%BasePath%blender.exe -P %BasePath%YYYOpenAndImport.py -- %1`
This opens Blender and automatically starts the YYYOpenAndImport.py script in which "bpy.ops.mmd_tools.set_shadeless_glsl_shading()" is called. I assume Blender is not fully loaded at that point in time.

But this fixed the error, so thanks 👍

**Comment by powroupi** [comment]
Okay, you're welcome. :smile: I had never considered that case, thanks for the report. :)
