### ISSUE TITLE
Not installing properly on Blender 2.79b on Ubuntu

### ISSUE THREAD

**Issue by KianaDaEditor3701** [powroupi/blender_mmd_tools#212]
I'm trying to install the v0.6.0 of mmd_tools but Blender seems to reject it. I tried to follow the troubleshooting guide by @powroupi on #130 (with me "translating" the Windows directories as to that of Linux) but no luck. I also tried to install the v0.4.0 but the error still persists.

Blender's internal Python console returns an AttributeError.

Here's the output of the Blender Python console:
![Screenshot_20190411_224601](https://user-images.githubusercontent.com/40626713/55966776-9de98280-5cab-11e9-92f1-c49a123feadb.png)

Any help?

**Comment by nagadomi** [comment]
Did you download mmd_tools from https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip ?

I use this addon on Ubuntu.
The installation command is as follows:
```
git clone https://github.com/powroupi/blender_mmd_tools.git
cd blender_mmd_tools
cp -r mmd_tools ~/.config/blender/2.79/scripts/addons
```

**Comment by KianaDaEditor3701** [comment]
No. I just downloaded the latest version on the Releases page.

And I'll try your install procedures and I'll let you know if that works
for me too.

**Comment by KianaDaEditor3701** [comment]
AYAYAY! Still not working!

![Screenshot_20190411_233414](https://user-images.githubusercontent.com/40626713/55970588-63371880-5cb2-11e9-9634-f253dbf318d4.png)

**Comment by nagadomi** [comment]
Hmm,
As far as I know, Python bundled with Blender's binary contains numpy module.
However, probably Blender on Ubuntu uses system Python.
So we may need to install numpy.
```
sudo apt-get install python3-pip 
pip3 install numpy
```

**Comment by KianaDaEditor3701** [comment]
Still no luck. `python-numpy` was already installed in the system...
Someone said in the Ask Ubuntu forums that `numpy` should be inside the `blender/2.xx/python`.

**Comment by powroupi** [comment]
@CV01HatsuneASD, you might temporarily disable the line [mmd_tools/core/sdef.py#L4](https://github.com/powroupi/blender_mmd_tools/blob/9b02ccfd0c954e528f8cef27e36dd43cd25f2546/mmd_tools/core/sdef.py#L4) as following, it should work around the issue (you will not be able to use SDEF buttons, though).
```python
import bpy
from mathutils import Vector, Matrix, Quaternion
#import numpy as np <- disable it temporarily
import time
```
If `mmd_tools` can be enabled, then we need to figure out the error of numpy. You might try the follwing command in Blender's internal Python console to see if numpy is working or not.
```python
>>> import numpy
>>> numpy.version
>>> numpy.version.version
```

**Comment by KianaDaEditor3701** [comment]
> If `mmd_tools` can be enabled, then we need to figure out the error of numpy. You might try the follwing command in Blender's internal Python console to see if numpy is working or not.
> 
> ```python
> >>> import numpy
> >>> numpy.version
> >>> numpy.version.version
> ```

Negative... mmd_tools still cannot be enabled... Tried to update the `numpy` to 1.16, copied the libraries to the `~/.local/blender/python/lib` directory but nothing happened...
![Screenshot_20190412_110225](https://user-images.githubusercontent.com/40626713/56009478-7548a380-5d12-11e9-8851-114ab15fb6b4.png)

**Comment by nagadomi** [comment]
@CV01HatsuneASD 
Blender 2.79 uses Python 3.X,  `python-numpy` is for Python 2.7.
You need to install `python3-numpy` package (or Install via pip3 with the above command).

**Comment by KianaDaEditor3701** [comment]
FIXED!!!

![Screenshot_20190412_113537](https://user-images.githubusercontent.com/40626713/56010647-19cce480-5d17-11e9-9256-c174e63382ee.png)
p.s. Model by sour

**Comment by KianaDaEditor3701** [comment]
Thanks for helping me, @nagadomi!!!!
