### ISSUE TITLE
Error on model import

### ISSUE THREAD

**Issue by Darkblader24** [powroupi/blender_mmd_tools#213]
I get an error when importing a certain hair model.
This is the error: https://i.imgur.com/GCXdScN.png
And here is the model: https://www.deviantart.com/vanillabear3600/art/Twin-buns-for-mmd-download-751514724

**Comment by powroupi** [comment]
Thank you for reporting this issue, I've fixed it (d7fff8b). :smile:

**Comment by Darkblader24** [comment]
Thanks, it works 👍
