### ISSUE TITLE
Problems using mmd tools for blender 2.80

### ISSUE THREAD

**Issue by NetralGD** [powroupi/blender_mmd_tools#215]
This plugin does not want fine be set at 2.80. 
First, blender doesn't want to see him in the list of add-ons. Then suddenly it will appear, but not working correctly. More precisely, the standard menu doesn't appear in blender. And the only import models is only possible via the import menu in the File menu. After some time after working on the blender plug-in menu appeared in the drop-down menu on the button to the N. And it worked!!
But recently the plugin stopped working and the blender menu additions wrote that the plugin requires version 2.8 X.
How to install this plugin on Blender 2.80 ? 
P:S On blender 2.79 b no problems.

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile:

I just did a quick test using today's lastest blender 2.8, and it's working. Are you using latest `mmd_tools` (https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip) ? The addon installation is the same with blender 2.7x, just remember to remove all old `mmd_tools` before installing a new one, there can be only one `mmd_tools` in one Blender release.

And yes, the `MMD` Tool Shelf is on the `T` panel for Blender 2.7x, but `N` panel for Blender 2.8x currently. :)

**Comment by NetralGD** [comment]
It works! And not lost),
But maybe I understand why. I did everything also and removed the old mmd tools, but the new one didn't work. However, the latest version of mmd tools in the release tab was 0.6.0. When a version is you given me, is 0.7.0. Also I remember that the last working version I also have become 0.7.0.(although I downloaded and installed 0.6.0.).
So I probably just used the old version, but there is no link to download version 0.7.0. Or this plugin itself is updated to this version ?

**Comment by powroupi** [comment]
The version 0.6.0 in the release tab was the tag before making major changes for Blender 2.8 API compatible. The latest version is under development, so it is only available from main page https://github.com/powroupi/blender_mmd_tools or the above quick download link. :)

**Comment by narbartor** [comment]
I've tried installing the latest version into my 2.8, but it doesnt seem to work

**Comment by powroupi** [comment]
You might reference #130 if you still have the installation issues. Thank you. :smile:
