### ISSUE TITLE
Could you teach us how to use it in blender 2.80 by video?

### ISSUE THREAD

**Issue by zhouhang95** [powroupi/blender_mmd_tools#217]
A lot of guys want to use eevee in 2.80. But, Blender 2.80 has a great gap with 2.79.
Just recording sceen is ok.
Thank you.

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile:

The interface of `mmd_tools` is basically the same, you might reference https://github.com/powroupi/blender_mmd_tools/wiki/Guide-to-the-mmd_tools-Interface . The only difference is that the `MMD` tool tab is moved to Properties Region of 3d view window (press `N` to show/hide Properties Region) on Blender 2.8.

I'm still learning eevee, so I don't know much about using eevee, sorry. :cry: Basically, after importing a MMD model, just try to modify the node group `MMDShaderDev` in Shader Editor to change default `mmd_tools` shader (click select the node group `MMDShaderDev`, press `Tab` to enter/exit editing).

**Comment by zhouhang95** [comment]
As your known, MikuMikuDance software is outdated. So users use lots of other sofrwares to improve it. Maybe we can use blender as an all-in-one platform to replace them. Functions like camera tracking, model editing, fluid Simulation, and so on.

**Comment by powroupi** [comment]
>Functions like camera tracking, model editing, fluid Simulation, and so on.

Sorry, I don't know so much, I think it's best to wait for the official documentation of Blender 2.8 or search the tutorial from the Internet. :)
