### ISSUE TITLE
mesh disappear from imported model at newest version 2.80 (Date:2019-05-14)

### ISSUE THREAD

**Issue by ghost** [powroupi/blender_mmd_tools#219]
Hi powroupi =)
I'd like to report that I met an error with model import by newest 2.80.
when importing MMD model, mesh is lost and only vertex is there. like below:
![Screenshot at 2019-05-15 21-53-06](https://user-images.githubusercontent.com/33831371/57777713-6fa10c00-775d-11e9-9ca6-f782a302e734.png)
![Screenshot at 2019-05-15 21-51-30](https://user-images.githubusercontent.com/33831371/57777706-6d3eb200-775d-11e9-968d-a4aa4c0cb246.png)
I doubt that this error has been caused by the change added to shader nodes nearest?
(and or just me?)
I would really appreciate any help.

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile:

Yes, there is a breaking change https://developer.blender.org/D4807. :cry:

For now, you can temporarily disable the line [mmd_tools/core/material.py#L405](https://github.com/powroupi/blender_mmd_tools/blob/ebcadb429924d397803ffc38d6d2fdc61132da5a/mmd_tools/core/material.py#L405), I'll update it in a few days. :)
```python
    def create_sphere_texture(self, filepath, obj=None):
        texture = self.__create_texture_node('mmd_sphere_tex', filepath, (-2, -2))
        sphere_texture_type = int(self.material.mmd_material.sphere_texture_type)
        # texture.color_space = 'NONE' if sphere_texture_type == 2 else 'COLOR' #<-- disable this line for now
        self.update_sphere_texture_type(obj)
        return _DummyTextureSlot(texture.image)
```

**Comment by ghost** [comment]
woow! Thank you for your quick reply and your great help!
I follow your suggestion, it is works very well like a charm. :smile: 
![Screenshot at 2019-05-16 11-14-57](https://user-images.githubusercontent.com/33831371/57821698-70bd5200-77cc-11e9-8e84-8d5a7eb6a018.png)
I really appreciate your great effort on this super useful addon everytime.
Thank you!

**Comment by powroupi** [comment]
Okay, I've updated `mmd_tools`, you might test it again (https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip). Thank you. :smile:

**Comment by ghost** [comment]
Thank you so much for update!
It is working absolutely fine with 2.80 date:19-05-14 and date:19-05-19 too! :100: 
![Screenshot at 2019-05-19 22-38-13](https://user-images.githubusercontent.com/33831371/57983025-f02a7a00-7a87-11e9-8fd0-094dbc0568d4.png)
I'm really happy that enjoying MMD model in blender again! :smile: :heart:
I deeply appreciate for your effort and hard work. Thank you very much!!

**Comment by nagadomi** [comment]
again
https://developer.blender.org/rB7aaa7aa9dd79b8c6e37f351fd67a93ba07fbb883
```
scripts/addons/mmd_tools/core/material.py", line 112, in _load_image
    img.use_alpha = (img.depth == 32 and img.file_format != 'BMP')
AttributeError: 'Image' object has no attribute 'use_alpha'
```
(I've just commented out the line for now.)

**Comment by powroupi** [comment]
@roundog-moz, thank you, you are welcome. :smile:

@nagadomi, thanks for the report, I'll update it next time. :smile:
