### ISSUE TITLE
Joints not work after exporting to pmx file

### ISSUE THREAD

**Issue by Vwings** [powroupi/blender_mmd_tools#222]
Blender version: **2.80 beta**
After exporting to pmx file and reopen using pmx editor, the joints still exist in the menu tab, but  are not visiable in 3d viewport and  also not work.

**Comment by powroupi** [comment]
Yes, the position of joints will be incorrect unless you unhide the joints before exporting to a pmx file when using Blender 2.8 beta. I found the matrices of joints were not updated after import, because they are hidden by default, and I think Blender will solve this problem. :)

**Comment by Vwings** [comment]
Thanks for your reply, it works after unhiding the joints.
