### ISSUE TITLE
Physics Bugging and Crashing in Blender2.8

### ISSUE THREAD

**Issue by AlanWestwood** [powroupi/blender_mmd_tools#225]
First of all, thank you for your efforts. Your work is remarkable. @powroupi 

Let's get straight to the issue as I put in the title, physics.

I'm now using Blender2.8, 2.80.69 specific. And whatever .pmx I import, clicking the Physic-Build, and press spacebar to play the animation without any motion for testing, then everything looks like exploding.

![img](https://user-images.githubusercontent.com/51512790/59149207-a06b1d00-8a4d-11e9-9196-a7d23bcd98b0.jpg)
*Model - TDA's Hatsune Miku Append*

This is what it looks like, I wonder if I'm not doing it correctly. I read the documentation but didn't found the solution.

I wonder the mode could be the problem? Like object mode, pose mode, or If I should select the armature first then click the Build?

And sometimes, it works. I don't know if there's a pattern, but I really can't tell what did I do to make it works. So, I came here to ask for help. Please help.

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile:

It probably is the same issue with #222, unhiding the rigidbodies/joints before clicking [Build] should solve it. :)

Because it's working fine using Blender 2.7x, I'm waiting for Blender 2.8 final release before fixing these issues.

**Comment by AlanWestwood** [comment]
> Thank you for reporting this issue. 😄
> 
> It probably is the same issue with #222, unhiding the rigidbodies/joints before clicking [Build] should solve it. :)
> 
> Because it's working fine using Blender 2.7x, I'm waiting for Blender 2.8 final release before fixing these issues.

Thank you, it's working!

It seems like I need to turn the globally visibility on and run the Physics Build. The Eye icon in outliner are showing, but the globally visibility are turn off. Turning all of them on solved the problem.

I'll be really looking forward to your MMD_Tools for Blender2.8 release. Your work is marvelous.

**Comment by nagadomi** [comment]
>The Eye icon in outliner are showing, but the globally visibility are turn off

I also encountered this problem before.
In the latest Blender 2.8, the icon to turn off rendering/global visibility are not displayed by default, so it's hard to recognize the visibility of old projects.

![outliner](https://user-images.githubusercontent.com/287255/59188890-b5fa5700-8bb3-11e9-8500-79f5e4f41daa.png)
