### ISSUE TITLE
properties\camera.py has infinity loop and causes crash in 2.8

### ISSUE THREAD

**Issue by Filexor** [powroupi/blender_mmd_tools#228]
See attached file for information.
If you load motion to camera with default settings, crash happens at 26th frame.
[CameraMotion.zip](https://github.com/powroupi/blender_mmd_tools/files/3293392/CameraMotion.zip)

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile:

You may modify [mmd_tools/properties/camera.py#L12](https://github.com/powroupi/blender_mmd_tools/blob/f756a5a9f1ab20afb42a064281cbf0bbe0870f4b/mmd_tools/properties/camera.py#L12) to see if it works or not. It was a temporary fix for old Blender 2.8 daily build in #196, so now I want to wait for Blender 2.8 final relase before fixing these issues. :)
```python
if bpy.app.version < (2, 80, 0) or 1: # <-- modify this line
    def __update_depsgraph(cam, data_prop_name):
        pass
```

**Comment by nagadomi** [comment]
A related report.
`cam.data.lens` is set via the` MMDCamera.Angle`, but when using CONSTANT Interpolation (I converted camera to 60FPS) it didn't work correctly with animation rendering mode(`render(animation=True)`). The lens of the camera was changed after the frame was rendered.
It works fine when rendering 1 frame on GUI.

I am not sure if it is a 2.8 issue or it should set the driver directly to cam.data.lens.
I used the following quick-fix script.
```python
import bpy
import math

def my_camera_handler(scene):
    cf = scene.frame_current
    mmd_cam = bpy.data.objects["MMD_Camera"]
    cam = bpy.data.objects["Camera"]
    angle = mmd_cam.animation_data.action.fcurves[9].evaluate(cf)
    lens = cam.data.sensor_height/math.tan(angle/2)/2
    if (abs(cam.data.lens - lens) > 0.0001):
        cam.data.lens = lens

bpy.app.handlers.frame_change_pre.clear()
bpy.app.handlers.frame_change_pre.append(my_camera_handler)
```

**Comment by powroupi** [comment]
Okay, I've updated `mmd_tools`, it should work on RC2 now. :smile: (1 frame delay issue is not tested :P )
