### ISSUE TITLE
Meshes on MMD models are split apart when exported.

### ISSUE THREAD

**Issue by Shinteo** [powroupi/blender_mmd_tools#230]
After exporting the mesh as PMX, on re-importing, some parts of the mesh are no longer connected, with overlapping vertices. This results in a visible line when attempting to render with the model in other 3d software

On testing it further, it seems to have to do with the UV mapping. The mesh is cut along the lines of the UV map.

**Comment by nagadomi** [comment]
As far as I know, it is PMX format specification. Mesh is splitted by UV seam.
You can merge overlapping vertices with `Remove Doubles` option in the import dialog.
However, it is better to  merge manually because it sometimes breaks a mesh that is used for material morph.

**Comment by powroupi** [comment]
Yea, it's PMX format specification, it's not a bug, :)
