### ISSUE TITLE
Can't see mesh even though it's all imported?

### ISSUE THREAD

**Issue by ChellyCoco** [powroupi/blender_mmd_tools#231]
I'm having trouble importing like, ANY model that I've attempted to make myself with this plugin. They show no errors in PMD and work perfectly in MMD, and I've compared with working models to try and see if I've missed something but I can't see any differences.

I've tried every sort of setting and translation, I've had it in all English and Japanese, I've deleted bones and meshes to test - I'm out of options!

Everything imports with the model but the mesh isn't visible unless I disable the MMD Armature modifier, even then though nothing works and I can't build physics or import motions. I've put a video up here: https://youtu.be/DNMpNEWI0NI

Also dropped the model here (warning, he's a mess because he's unfinished! I have no drive to finish him if I can't get him into Blender.. Also he was made in Vroid so ignore the awful hair names lol): https://drive.google.com/file/d/1OfRQFUW_J25APndGsdT2MZGNBwVwEZUM/view?usp=sharing

I've included a 04. debug log in there too

**Comment by nagadomi** [comment]
The model's root bone(全ての親) length is invalid (NaN).

**Comment by powroupi** [comment]
@ChellyTots, thank you for reporting this issue, it should be fixed now. :smile:

We could check Float values in readVector/readFloat functions in pmd/pmx.__init__.py if necessary, I just fixed the bone issue for now. :)
