### ISSUE TITLE
X-flipped pose broken for some bones

### ISSUE THREAD

**Issue by toomasluts1** [powroupi/blender_mmd_tools#232]
When I paste an X-flipped pose, it doesn't get mirrored correctly to the other side of the body, bones get bent backwards. This happens with all arms bones starting from the shoulders and also with wings of a winged character. It doesn't happen with legs though, those work fine.
Also, I can fix this manually in edit mode by changing the rolls of those bones to the equal and opposite value of the other side's bones but it's quite tedious (fingerbones zZz..)

**Comment by nagadomi** [comment]
mmd_tools has its own x-flipped pose operator.
![flippose](https://user-images.githubusercontent.com/287255/41613743-6f4a72bc-7431-11e8-85f7-92ec1c2cfad9.png)
related #20 #154

**Comment by toomasluts1** [comment]
Ooh ok thanks
