### ISSUE TITLE
Something very weird about physics in Blender 2.80.74

### ISSUE THREAD

**Issue by lwp513202035** [powroupi/blender_mmd_tools#234]
Hi @powroupi 

I am here cause I found something very weird about the physics in Blender 2.80.74，not the RC version , but the builder version at July 5th.

Just like you said before , to make the physics bulid right in Blender 2.80，we need to unhide the rigidbody and joint . And I find that it is done automatically when I import a MMD model using the latest MMDtool.

Then I hit the "bulid" to bulid physics , then every rigidbody explodes. _(:з」∠)_

Then I clean the physics , uncheck the √ to exclude the whole collection .

Then check the √, bulid physic again, then the physics works well sometimes , and may not work othertime.

And all the operation above is not useful in RC version . The physics cannot work in RC version at all.

I feel so strange _(:з」∠)_.....

**Comment by powroupi** [comment]
Make sure settings of [Rigid Body](https://docs.blender.org/manual/en/dev/physics/rigid_body/world.html) are well configured, Scene's Start frame should be equal to Rigid Body Cache's Start frame, and go to start frame everytime before clicking [Build].

I can play physics on RC2, but I've got a crash of [Build]/[Clean]/[Play] cycle, I think there would be something need to be fixed. :)

**Comment by powroupi** [comment]
I've updated `mmd_tools`. Now, you should be able to click [Build] without unhiding the rigid bodies and joints after importing a MMD model.

Please test latest `mmd_tools` and Blender 2.80 release version again to see if there is still any issues. Thank you. :smile:
