### ISSUE TITLE
Weird black color on some materials

### ISSUE THREAD

**Issue by KianaDaEditor3701** [powroupi/blender_mmd_tools#235]
Something's weird is going on in my [downloaded model](https://www.deviantart.com/brausshows/art/TDA-Miku-and-Teto-Qipao-DL-670375393). The materials node shows nothing where this black color coming from, and neither disabling the toon and the sphere texture nor bypassing the MMDShaderDev with a diffuse BSDF with the main base texture connected to the color node.

Here are the examples:

![need to debug this4](https://user-images.githubusercontent.com/40626713/61788973-0bc64e00-ae46-11e9-8181-1c75cdd24730.png)
*rendered image (with the noticeable darkening)*

![need to debug this2](https://user-images.githubusercontent.com/40626713/61789011-2a2c4980-ae46-11e9-863c-91fd49f7cd9c.png)
*shown with my default shading window*

![need to debug this3](https://user-images.githubusercontent.com/40626713/61789034-3a442900-ae46-11e9-9d13-c023eb6eefb2.png)
*view from the material node editor*

Tested on the beta Blender 2.8 (Beta 2019-04-26) on Ubuntu 18.04.1 64-bit
And I'm currently testing this also on the Blender 2.8 Release Candidate 2.

**Comment by nagadomi** [comment]
All faces in the dress are not connected, and the normals are weird.
Texture can be displayed with turn off `Object Data Tab > Normals > Auto Smooth` on blender.

**Comment by powroupi** [comment]
I think it's a fake velvet effect which does not work on Path Tracing rendering. So you may either fix mesh's normals or modify shader nodes of MMDShaderDev (connect a corrected normal to Diffuse/Glossy shader's [Normal] input). :)

**Comment by KianaDaEditor3701** [comment]
May I ask... Why mmd-tools sometimes loads nonexistent textures?

**Comment by nagadomi** [comment]
Regarding the above model,  some file paths for toon textures are incorrect. I think it is a problem in the model.
