### ISSUE TITLE
Using material morphs the same way as vertex morphs

### ISSUE THREAD

**Issue by KianaDaEditor3701** [powroupi/blender_mmd_tools#237]
The original MMD has this but I think mmd_tools don't have it. Any help?

**Comment by nagadomi** [comment]
`Bind` with Morph Tools adds shape key drivers to `.placeholder` object.
![material_morph](https://user-images.githubusercontent.com/287255/62007711-b2368a00-b18b-11e9-9624-7eb8017fd112.png)

**Comment by KianaDaEditor3701** [comment]
Why mmd_tools don't automatically bind material morphs? Do you think manual binding is necessary?

**Comment by nagadomi** [comment]
Maybe the same reason as not automatically binding physical or bone constraints. And, bone morphs and material morph bindings seem to be experimental features.

In my opinion, I think that this bind button is better placed at the same level as the bind button of physics or bone constraints.

**Comment by KianaDaEditor3701** [comment]
> Maybe the same reason as not automatically binding physical or bone constraints. And, bone morphs and material morph bindings seem to be experimental features.

Yep. Some models are not morphing materials very well. They tend to z-fight... (might because of conflicting duplicated meshes)
