### ISSUE TITLE
IK construct behaves differently in MMD/PMXE vs Blender

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#24]
http://www.mediafire.com/download/wsruloxdxa3mcdj/test.pmx -- just the pmx, that should be all you need.

The "focus" bone is an IK structure intended to simplify animation of eye tracking in MMD; it is intended to be registered to another bone in MMD via the outside parent settings, at which point the model's eyes will track that bone.

1) Load into MMD or PMXE/transform.  Notice how the "focus" bone moves the eyes when moved.

2) Import into Blender, switch to pose mode and adjust the "focus" bone.  Although it is having some effect, it's behaving entirely differently than it does under MMD.

This is a complicated bone structure that I made a long time ago, and I'm not sure that all elements are necessary for its function in MMD-- it was hard to make, and so once I got it working, I haven't touched it since.  Just starting to learn Blender animation and rigging and discovered this issue.  It's not important to me, but could impact import/export of motions.  I haven't experienced any problems with import/export related to this bone structure; your bone fixes have kept the structure entirely intact and working in MMD through import/export cycles.

**Comment by powroupi** [comment]
Confirmed. Thank you for reporting the issue. :smile: 

Hmm, i think the IK limit angles are converted in wrong way (work ok in legs though), but i don't know the right way yet, need more time to figure out that. :disappointed: 

And actually, we can't expect the IK behavior is identical. There are 2 different behaviors (at least):
1. The loop count (MMD) does not behave the same way with the iterations (Blender).
2. There is no "IK Unit Angle" in blender's IK system.

So it should be normal if there is any difference when using IK bone structure (except the issue of IK limit angles). :)

EDIT:
I think the [IK dummy bones](https://github.com/powroupi/blender_mmd_tools/blob/6acb856c88e007c8c88b7fba04eae8ec90f4521d/mmd_tools/core/model.py#L292-L308) might not be necessary. The IK works better after doing following fixes in blender:
1. Select bone "目戻.R", change target bone of IK constraint from "右eyeIK.ik_target_dummy" to "eyeIK.R" ("右EyeIK.ik_target_dummy" might be duplicated, mute or remove that IK constraint). Assign IK limit angles of Z axis: -30 ~ 18 degrees.
2. Select bone "目戻.L", change target bone of IK constraint from "左eyeIK.ik_target_dummy" to "eyeIK.L" ("左EyeIK.ik_target_dummy" might be duplicated, mute or remove that IK constraint). Assign IK limit angles of Z axis: -18 ~ 30 degrees.

**Comment by powroupi** [comment]
Well, i guess this issue is probably solved now. :smile: (might still have minor issues, but i might not be able to make it better >_<)

Finally i got the idea to convert the IK limit angles. Current conversion will work best if the bone's axis is aligned to global axes. :)

**Comment by nathanvasil** [comment]
Looks great, thanks.
