### ISSUE TITLE
MMD tools not working with blender 2.80.75

### ISSUE THREAD

**Issue by KeyOfCode** [powroupi/blender_mmd_tools#242]
![image](https://user-images.githubusercontent.com/53923140/62746824-d4fd5400-ba51-11e9-9e66-ed164e988b0c.png)

**Comment by powroupi** [comment]
Currently, Blender 2.8 release version is supported by latest `mmd_tools`. If you are using (newer or older) daily build versions of blender, `mmd_tools` might not work. Please use Blender 2.8 release version instead.

And you might enable all types of addon filter (enable **[Official] [Community] [Testing]**, and select category **[All]** ), then search `mmd` again to make sure there is only one `mmd_tools` addon. If there are multiple `mmd_tools` addons, please remove all of them and then reinstall the one you want.

**Comment by KeyOfCode** [comment]
I think I downloaded the release version, as I directly downloaded from the page instead of searching for any other builds.

**Comment by KeyOfCode** [comment]
Also, mmd tools appear in the add on list, whether I install it from Blender or I place it directly in the add on folder, but it won't work.

**Comment by nagadomi** [comment]
From the error message, it seems that two mmd_tools are installed.
```
C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mmd_tools
C:\Users\at4hp\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\mmd_tools
```
You should uninstall it first.

**Comment by KeyOfCode** [comment]
I see, thanks! I'll try again now

**Comment by KeyOfCode** [comment]
It worked! Well, so far. I'll point out any other bugs I find later, but many thanks!
