### ISSUE TITLE
I can't enable the addon

### ISSUE THREAD

**Issue by Blush112** [powroupi/blender_mmd_tools#243]
I've been trying to use the addon but when I try to enable it I get this issue

![Screenshot_637](https://user-images.githubusercontent.com/54073907/62955057-71ab5300-bdbe-11e9-8abb-33e6d270b741.png)

**Comment by nagadomi** [comment]
>`mmd_tools\properties\__init__.py, line 53`

It is an older version of mmd_tools, but the error message seems to show the newest mmd_tools's code.
Maybe you should uninstall(`Remove`) the old mmd_tools first, then shutdown Blender and reinstall mmd_tools from https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip.
