### ISSUE TITLE
MMD shader for Eevee

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#245]
Did a first draft of creating a true-to-MMD shader for Eevee.  This is a lot simpler than trying to do it in Cycles, thanks to some Eevee specific tools-- no need to composite in lighting, for example.

File is available at http://pasteall.org/blend/index.php?id=52217 .  Contains an Animasa Miku doing Hibikase.  All Eevee mats have been set-- hopefully in a method that makes it, uhh, relatively easy to figure out what's happening, in way that makes it easy to pop in things like normal maps, etc.

MMD_Tools has seemed to want to avoid drivers in the past, so I made some odd decisions setting up the sun.  Note that the sun as a lamp is used only to create a shadow map-- its vector is read by the Eevee materials, and the sun strength/color is set in the material settings (in linked node groups, so you can edit once to affect all.)

Includes MMD-specific stuff like add-syn, transp buttons.  Shadow mode 1 and 2 differ by how they handle shadowbuffer depth, I believe, and I'm letting Eevee handle the shadowbuffer, so there's no difference there.  File is set up loading textures as non-color, rendering to raw to preserve MMD's lack of gamma correction.

Probably some bugs.  Offering in case it's useful to anyone.

**Comment by nathanvasil** [comment]
Oh, and it looks like one of the less documented changes to 2.8 were some dependency improvements that now permit bone->physics->bone within a single armature.  Not sure if that might be something that could streamline MMD Tools' physics setup, just sharing.

**Comment by ptrthomas** [comment]
@nathanvasil thanks for sharing ! hope I get time to look at this soon. can you give me one example (so that I understand better) what the bone->physics->bone can do ? I've always felt mmd physics when in blender is over-engineered, and this may make it easier to export physics to game engines such as unreal

**Comment by nathanvasil** [comment]
@ptrthomas The main issue with Blender+armatures+dependencies previous to 2.8 was that an armature was evaluated as a single object for dependency purposes.  If you had a rigid body parented to one bone, then another bone parented to that rigid body, you had a dependency loop, because the rigid body depended on the armature and the armature depended on the rigid body.  This usually required setting up some proxies or splitting up armatures.

That's no longer the case in 2.8.  There are some other dependency changes, but what's exciting to me is that this appears to no longer be evaluated at the armature level, but at the bone level.

(Other places where this is really good news for somebody like me are with mesh-defined angle limits/interpolation, where I can parent a non-rendering mesh to, say, an upper body and then have the clavicle track a marker shrinkwrapped to that mesh, to define weird angle limits or to create custom remapping of keyframed transformation or even to fix clipping problems with mesh booleans; and curves, where I can now control a curve via hooks from the same armature that then has a spline IK chain dependent on the curve.)
