### ISSUE TITLE
_shadow_ bones aren't made when I push Rotate+ button

### ISSUE THREAD

**Issue by moco-rocket** [powroupi/blender_mmd_tools#246]
When I make some additional bones such as arm twist_L, wrist twist_L etc, I usually push the Rotate+ button in bone pannel. I understand that shadow bones and dummy bones are made automatically for bone constraint settings. Now, I want to append the 'mmd_additional_rotation' constraint on shoulderC (means shoulder cancel) bone (it make an influence on shoulderP bone), but '_shadow_sholderC' bone was NOT made and 'mmd_additional_rotation' bone constraint on shoulderC bone got 'shoulderP' bone as the target. sholderP bone was added by me not automatically.  please teach me how to set the bone constraint to shoilderC bone and make shadow/dummy bones correctly. Thank you.

**Comment by powroupi** [comment]
If you want `Bone1` to be controlled by `Bone2`:
 - in Pose mode, select `Bone1`
 - on the MMD Bone Tools panel, push/enable [Rotate +] or [Move +], set influence to 1.0 or any other value, and choose `Bone2` in the dropdown menu of Additional Transform Bone. That's it !!

Additionally, you can click the buttons [Apply]/[Clean] of [Bone Constraints:] on the MMD ToolSheif [Operator] panel any time to re-apply these settings. :)
