### ISSUE TITLE
"Upgrade to 2.8"

### ISSUE THREAD

**Issue by SkylerTDC** [powroupi/blender_mmd_tools#249]
When i try to put on the addon it always tells me i need to upgrade to 2,8x which is what im using
i dont know if this is an issue you can help me fix or not though

Ive tried uninstalling blender, uninstalling the mmd tool, removing the tool from blender and readding it

but nothing seems to work
![Blender issue](https://user-images.githubusercontent.com/55714592/65455456-8e1fbe00-de47-11e9-8aa4-5d59bea9315c.PNG)

**Comment by zhouhang95** [comment]
use latest version
now it is 0.7.0

**Comment by powroupi** [comment]
@SkylerTDC 
Please use my `dev_test` branch https://github.com/powroupi/blender_mmd_tools/tree/dev_test
Directly download link: https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip
Thank you. :smile:

**Comment by SkylerTDC** [comment]
@zhouhang95 could you possibly link me that? i cant find it

**Comment by powroupi** [comment]
@SkylerTDC the link I posted above is 0.7.0. :smiley:

**Comment by SkylerTDC** [comment]
@powroupi ive gotten it added on but now it gives me a new error

**Comment by powroupi** [comment]
@SkylerTDC 
Please make sure to remove old `mmd_tools` before installing a new `mmd_tools`.
If there is still any error, please paste the error messages or attach the screenshot here, thank you. :smile:

**Comment by powroupi** [comment]
The original issue should be solved. If you got any new error, please open a new issue, thank you.
