### ISSUE TITLE
Unnormalized weights getting improper normalization on export

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#25]
http://www.mediafire.com/download/vhhae4gc2csbdvz/4.blend -- an imported pmx that I messed with a bit.

Don't know how to identify Blender vertices by number or I could direct you to specific examples.  Blend file provided contains several unnormalized vertices.  Relative weights are pretty reasonable, which you can see at a glance in pose mode.

On export, relative weights are getting mangled.  On one vertex (exports as #425 for me), Blender vertex weights of 0.008/0.765 are getting turned into MMD weights of 0.2352941/0.7647059.  Looks like it's just subtracting the main weight to figure the second weight.

(Not even sure how I managed to get an un-normalized weight, I wasn't doing any weight painting, nor did I delete any bones or vertex groups from Blender.  No relevant errors on PMX validation on the source either.)

Pretty obvious work around, of course.

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: 

I think it's the issue that the exporter didn't normalize the weights correctly (it assumed the weights were normalized). The normalized weights of 0.008/0.765 should be 0.01035/0.98965. Now, the issue should be solved. :smile: 

P.S. You should keep the **bone weight** counts of every vertex less or equal 4, it is easy to forget (not noticeable) that in blender. :)

(You can close this issue If you don't see any further issues in my updated version)

**Comment by nathanvasil** [comment]
Looks good.

Just out of curiosity, how will it handle >4 weights?  Won't it just drop the last and then renormalize like Blender does if you tell it to?

Might also be a good idea to lock mmd_edge_scale and mmd_vertex_order vertex groups on imported models to prevent these from impacting normalization and "limit total."

**Comment by powroupi** [comment]
> Just out of curiosity, how will it handle >4 weights?...

Yeah, currently the exporter will drop those weights and just pick up first 4 weights, and then renormalize. By the way, the zero weights will be dropped first. For example, the result of [0.15, 0, 0.5, 0, 0, 0.25, 0.1, 0.3] will be [0.15, 0.5, 0.25, 0.1]. :)

> Might also be a good idea to lock mmd_edge_scale and mmd_vertex_order vertex groups...

I agree. And they can be safely remove if you just need the default values. :)
- The default weight of mmd_edge_scale is 1.
- The default weight of mmd_vertex_order is internal vertex index. The order of mmd_vertex_order is the same with the order of internal vertex index if you don't changes anything.
