### ISSUE TITLE
Can not select bone I need in 2.80.

### ISSUE THREAD

**Issue by zhouhang95** [powroupi/blender_mmd_tools#252]
In pose mode, it work well in 2.79.
In 2.80, only root bone can be selected, others can not.
But all can be selected by outline window.

**Comment by zhouhang95** [comment]
only this bone can be select, others can not.

**Comment by zhouhang95** [comment]
![screenshap](https://user-images.githubusercontent.com/15245678/66036575-27ce2600-e540-11e9-94dc-4b9e8ca3c054.png)

**Comment by nagadomi** [comment]
Check the `Restrict selection in the 3D View` icon.
![select_icon1](https://user-images.githubusercontent.com/287255/66054595-36800180-e56f-11e9-858a-b7023422c3ae.png)
![select_icon2](https://user-images.githubusercontent.com/287255/66054601-397af200-e56f-11e9-8642-1fbcdf3022b9.png)

Maybe this is an old .blend file conversion issue and not related to mmd_tools.

**Comment by zhouhang95** [comment]
I find this problem in my one pc, but the other doesn't meet this problem..................

all in all, tks for your reply.

**Comment by nathanvasil** [comment]
There are a lot of similar reports for 2.8, unrelated to MMD Tools.  See https://developer.blender.org/T68217 for one example.  Should be fixed in 2.81.
