### ISSUE TITLE
Blender2.8 installation error

### ISSUE THREAD

**Issue by Zacharia2** [powroupi/blender_mmd_tools#253]
Traceback（most recent call last）：
    File"/usr/share/blender/2.80/scripts/modules/addon_utils.py",line 384,in enable mod.register()
     File"/usr/share/blender/2.80/scripts/modules/addons/mmd_tools/_init_.py",line 120, in register properties.register()
     File"/usr/share/blender/2.80/scripts/modules/addons/mmd_tools/properties/_init_.py",line 68, in register prop_obj = properties.setdefault(bpy.types.Object,{})
    ValueErrror:bpy_struct "Object" registration error:mmd_root could not register

**Comment by powroupi** [comment]
I guess you have installed duplicated plugins or outdated versions, you can test it:
- Make sure you are using Blender 2.80 release and latest [mmd_tools](https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip).
-  Start Blender, [File]->[Defaults]->[Load Factory Settings], and then enable `mmd_tools` again, `mmd_tools` should be enabled succesfully.

**Comment by powroupi** [comment]
>File"/usr/share/blender/2.80/scripts/modules/addons/mmd_tools/init.py",line 120, in register properties.register()

I think you put `mmd_tools` inside wrong folder, move your folder _/usr/share/blender/2.80/scripts/**modules/addons/mmd_tools/**_   to  _/usr/share/blender/2.80/scripts/**addons/mmd_tools/**_, then it should work. :smile:

If it still won't work, you might also refer [Blender's Directory Layout](https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html), cleanup Blender's **USER** & **SYSTEM** folder. If you put your 3rd party addons to Blender's **LOCAL** path, you will need to cleanup that as well. And then re-add / re-install your 3rd party addons.

Usually:
 - Blender Addons are inside **LOCAL**\scripts\addons\\*
 - User / 3rd party addons are inside **USER**\scripts\addons\\* or **SYSTEM**\scripts\addons\\*

Installation Note of `mmd_tools`:
- Do not directly install the zip file you downloaded. Extract the `mmd_tools` folder which is inside the zip file, Copy `mmd_tools` folder to one of Blender's addon path instead. And do not rename `mmd_tools` folder to any other names.

**Comment by GameXLife** [comment]
I got same problem under Windows system and found that can be fixed easily.
If you do all the steps and error still occurs, don't need to do any other thing.
Just close blender and restart it with "Run as  Administrator".
Then go to AddOn tab and reactive mmd_tools, now it works.

**Comment by powroupi** [comment]
Some installation related issue powroupi#98 (or powroupi#91, powroupi#92).
