### ISSUE TITLE
Some about normal or shader?

### ISSUE THREAD

**Issue by zhouhang95** [powroupi/blender_mmd_tools#255]
![image1](https://user-images.githubusercontent.com/15245678/67593156-1ae5d080-f794-11e9-9572-a76c307e6cd6.jpg)

![image2](https://user-images.githubusercontent.com/15245678/67593158-1de0c100-f794-11e9-80e1-68da31d278fe.jpg)

What do you do in your add-on? Why the lines  disappear?
Fig.1 is blender2pmxem, Fig.2 is blender_mmd_tools.

**Comment by powroupi** [comment]
It is custom normals / custom-split-normals: :smile:
 - [meshes/properties/custom_data#custom-split-normals](https://docs.blender.org/manual/en/latest/modeling/meshes/properties/custom_data.html#custom-split-normals)
- [modeling-meshes-normals-custom](https://docs.blender.org/manual/en/latest/modeling/meshes/structure.html#modeling-meshes-normals-custom)

If you disable [Properties editor ‣ Object Data ‣ Normals ‣ Auto Smooth], it will show default normals of the geometry. Usually you can remove/merge doubled vertices to get smooth normals if you don't want custom normals.

**Comment by zhouhang95** [comment]
Could you change the dispaly in solid mode back to blender default dispaly.
As you look, now it is hard to see the surface details.

**Comment by zhouhang95** [comment]
I mean the render methed not smooth normals.

**Comment by powroupi** [comment]
Do you mean "metallic" look? Try this command in Blender Python Console:
```python
>>> for m in D.materials: m.metallic = 0
>>>
```
For now, you can also remove these 2 line in [core/material.py#L536-L537](https://github.com/powroupi/blender_mmd_tools/blob/717d813d4ce4e8243f2d82acf853217953483b64/mmd_tools/core/material.py#L536-L537) as you like. :smile:

**Comment by nagadomi** [comment]
>Could you change the dispaly in solid mode back to blender default dispaly.

I think this refers to the viewport shading setting.
![viewport_shading](https://user-images.githubusercontent.com/287255/67629535-7ad69700-f8ba-11e9-93c4-6b6e76f0db56.png)

**Comment by zhouhang95** [comment]
Thanks a lot!
