### ISSUE TITLE
Blender2.81 import issues

### ISSUE THREAD

**Issue by NaughtDZ** [powroupi/blender_mmd_tools#256]
![77750170_p0](https://user-images.githubusercontent.com/37768911/69477917-13632700-0e27-11ea-95f7-c56e9d925d89.png)
What wrong?

**Comment by nagadomi** [comment]
It has already been fixed a month ago.

**Comment by powroupi** [comment]
Yes, this issue is fixed. And make sure you are using official released version of Blender, `mmd tools` is not guaranteed to work on any daily builds of Blender. Thank you. :smile:
