### ISSUE TITLE
Where can I know how the mmd file format is defined

### ISSUE THREAD

**Issue by threethreenine** [powroupi/blender_mmd_tools#257]
I want to add mmd extension on other engines，i need to know the file farmat of mmd.
For example, the vertex storage arrangement in the PMX model, bone binding relationship, expression and expression drive, bone animation in vmd, and the arrangement of key frames of expression animation.

**Comment by powroupi** [comment]
Sorry, I don't have any documents for mmd file formats, but I think you can find some by searching it from internet. :smile: And there are already repositories in Github (https://github.com/search?q=MikuMikuDance) you can read their code to figure out mmd file formats.

Here are the entry of "load" functions inside `mmd_tools`:
[mmd_tools/core/pmd/\_\_init__.py](https://github.com/powroupi/blender_mmd_tools/blob/3fb389a28cebdb140cb6a7477c26eab45df43660/mmd_tools/core/pmd/__init__.py#L328)
[mmd_tools/core/pmx/\_\_init__.py](https://github.com/powroupi/blender_mmd_tools/blob/3fb389a28cebdb140cb6a7477c26eab45df43660/mmd_tools/core/pmx/__init__.py#L350)
[mmd_tools/core/vmd/\_\_init__.py](https://github.com/powroupi/blender_mmd_tools/blob/3fb389a28cebdb140cb6a7477c26eab45df43660/mmd_tools/core/vmd/__init__.py#L326)

**Comment by threethreenine** [comment]
Thank you very much for your code. I'm sorry to tell you that I'm not very familiar with python and it may take a while to understand your code.
Now I come across a .pmx format model, I can open it with MikuMIkuDance, but not with the PMXEditor.exe tool. When I parse this .pmx file, data out of bounds occurs at the extended Morph location, I do n’t know if I parse The problem with the algorithm is also the problem with the model itself.

**Comment by powroupi** [comment]
I think it is better to focus on the models that can be opened in both MMD and PMXE at beginning,
once you got it to work, then you can find some ways to workaround the issues on the models which contain some corrupted/invalid data. :smile:

There are also Implementations in other programming languages (C++, C#, JS, ...) In GitHub (https://github.com/search?q=MikuMikuDance) that could help.

ps. `mmd_tools` does not support PMX 2.1.

**Comment by oelison** [comment]
Here you could find a description:
https://mikumikudance.fandom.com/wiki/VMD_file_format
But I can not find the audio data.
