### ISSUE TITLE
Where is the mmd_tools dropdown?

### ISSUE THREAD

**Issue by wowweemip-fan** [powroupi/blender_mmd_tools#258]
Where is the mmd_tools dropdown?

**Comment by powroupi** [comment]
Here is a `mmd_tools` interface document (it's not up to date yet, but it's almost the same): :smile:
https://github.com/powroupi/blender_mmd_tools/wiki/Guide-to-the-mmd_tools-Interface

If you have issues on installation, you might take a look the following documents:
https://github.com/powroupi/blender_mmd_tools/wiki/How-to-install-the-mmd_tools-Blender-add-on
https://github.com/powroupi/blender_mmd_tools/wiki/Documentation#installation

Thank you. :smile:

**Comment by wowweemip-fan** [comment]
Awesome thank you!
