### ISSUE TITLE
It's not working in 2.81

### ISSUE THREAD

**Issue by DeGraphics-Studios** [powroupi/blender_mmd_tools#260]
I tried importing a model in Blender 2.81 and the model did not import properly.  I have tried it with other models and I g get the same result.
<img width="1680" alt="Screen Shot 2019-12-31 at 10 52 34 PM" src="https://user-images.githubusercontent.com/24575690/71637963-7e6efd00-2c20-11ea-944e-e321ef66732d.png">

**Comment by DeGraphics-Studios** [comment]
I fixed it, I just had to turn translation on.

**Comment by CrimsonSZ-Q** [comment]
How to install in 2.81 ?, 
![Uploading 15782772317141566968456.jpg…]()

**Comment by DeGraphics-Studios** [comment]
> How to install in 2.81 ?,

I'm basically using the steam version, but again, I was able to fix it.
