### ISSUE TITLE
after separating by materials, when I click"bind", shader editor settings will change, it happens in all materials

### ISSUE THREAD

**Issue by DoroMan233** [powroupi/blender_mmd_tools#261]
when I click the bind button, all my material settings will change：(
![71678675-ac8b4300-2dc0-11ea-918d-c34b9ff13cd5](https://user-images.githubusercontent.com/57245933/71778137-ec327480-2fe4-11ea-8e94-1f182be0cc1f.png)
![71679084-b497b280-2dc1-11ea-99f3-a701b10d2aca](https://user-images.githubusercontent.com/57245933/71778142-f5234600-2fe4-11ea-9523-127edafa2f7e.png)

, how show I deal with this situation？I don't want set the materials once again, it takes me much time

**Comment by nagadomi** [comment]
PMX models have material morphs and UV morphs, which only work with mmd_tool's material settings. Bind button is used to apply those feature.
If you don't need matrial morph and UV morph, change the material after bind.

**Comment by powroupi** [comment]
Okay, update your `mmd_tools`, it won't change shader now. But material morphs will only work if `mmd_shader` node is used.
