### ISSUE TITLE
failure of rigid bodies after append

### ISSUE THREAD

**Issue by DoroMan233** [powroupi/blender_mmd_tools#263]
![BUG2](https://user-images.githubusercontent.com/57245933/73560349-b8d2f080-4491-11ea-9262-d36cbec02f49.png)
this is the correct rigidbodies performance after I import a pmx model by mmdtools:)

![bug](https://user-images.githubusercontent.com/57245933/73560393-d3a56500-4491-11ea-8ea0-c5d9bd29cb4b.png)
and this one is the same model, but it's append from a blend file which has saved the pmx model import by mmdtools, but this time, the rigidbodies were exploded:(

is there any tips about solving the problem that rigbodies doesn't work after append?

**Comment by DoroMan233** [comment]
blender version is 2.81a :)

**Comment by nagadomi** [comment]
When appending an object, Blender duplicates the original collection and assigns the object to it. And, rigid bodies only work with objects that belong to the collection specified in Rigid Body World settings.
You need to manually fix Rigid Body World settings and the collection to which each rigidbody/joint constraint belongs.

**Comment by DoroMan233** [comment]
> When appending an object, Blender duplicates the original collection and assigns the object to it. And, rigid bodies only work with objects that belong to the collection specified in Rigid Body World settings.
> You need to manually fix Rigid Body World settings and the collection to which each rigidbody/joint constraint belongs.

thanks!
