### ISSUE TITLE
Blender crashes whenever I want to convert the model into cycles

### ISSUE THREAD

**Issue by Titaniumbot360** [powroupi/blender_mmd_tools#265]
In Blender 2.82, whenever I want to convert a model to use for cycles, the program ends up crashing altogether. Even if I didn't do anything with it, is there a way to fix it?

**Comment by nagadomi** [comment]
This issue has been reported many times, but the cause is unknown.
I also encountered this issue a few years ago but have not recently encountered.
Try https://github.com/powroupi/blender_mmd_tools/issues/56#issuecomment-391103050
