### ISSUE TITLE
Problem while importing PMX

### ISSUE THREAD

**Issue by malpower** [powroupi/blender_mmd_tools#266]
Hi guys,
i just installed the addon to blender.
but when i import pmx file, an error message shown up which says:
![图片](https://user-images.githubusercontent.com/1700970/75511672-d57b2d80-5a29-11ea-848e-265548ba34c1.png)

I've set the shared toon texture folder to mmd's data folder.

any idea?
Thank you.

**Comment by nagadomi** [comment]
Maybe you have multiple versions of mmd_tools installed. (the error message does not seem to match the source code.)
Uninstall all mmd_tools first and then reinstall.

**Comment by powroupi** [comment]
Possibly the same issue with powroupi#256. Update `mmd_tools` should fix it. :smile:

**Comment by malpower** [comment]
great, it has been fixed.
