### ISSUE TITLE
More bone issues

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#27]
I'm despairing of Blender and MMD ever actually agreeing.

http://www.mediafire.com/download/pk264oangu8343h/together2.pmx is a model with a lot of complicated bone work, including stuff demanding deformation tier.  MMD, PMXE, and Blender + MMD Tools give three different interpretations of the base pose.  The model isn't really working in any of these, but ideally, it ought to be wrong in the same way in all three.  Although it has a -2 append ratio bone, that's not the problem in the default pose; it's something else.

For a quick pic, check out http://vasilnatalie.deviantart.com/art/One-skeleton-one-pose-three-interpretations-631274718 which has the three interpretations.

**Comment by powroupi** [comment]
In blender, the issue is similar to issue #24, the importer added redundant IK dummy bones and some incorrect IK limit angles, even more, the bone order and deformation tier don't have any effect in blender. So you should never expect the interpretations will be the same. :sweat: 

There are always things that MMD can do but Blender can't do, and always things that Blender can do but MMD can't do. That's a trade off. :)

**Comment by nathanvasil** [comment]
Thank you.  In that case, I'll close the issue.

**Comment by blaychris** [comment]
Hi, I'm quite new to MMD but am ok with Blender. Recently tried to use this model : http://www.deviantart.com/art/Cartoony-Chibi-Base-361861664 to test out this Blender add-on, however, the fingers end up on the floor once imported on to MMD. It weirdly repositions itself correctly when you try to move something, but when you load up the model for animation, the fingers returns back to floor 

![screen shot 2016-10-12 at 1 27 26 pm](https://cloud.githubusercontent.com/assets/1456121/19298376/ae1b67c2-907f-11e6-957b-693180e8fe52.png)

**Comment by powroupi** [comment]
Hi, @blaychris, thank you for reporting the issue. :smile: 
And i found the bone's _transform order/deformation tier_ of pmd model is not converted properly on import, you might need to reconfigure that manually in blender at the moment. If a pmx model, it should work fine. :)

**Comment by nathanvasil** [comment]
@blaychris Edited out some workaround that was more difficult than was necessary.  If you don't want to mess with Blender's settings, saving it as a .pmx (like with PMXE) will work.
