### ISSUE TITLE
I import model only so much black spots

### ISSUE THREAD

**Issue by LsaNa1s** [powroupi/blender_mmd_tools#271]
I tried use blender first time. so....many things haven't been figured out yet. （Forgive me this bad English）
![QQ截图20200306114218](https://user-images.githubusercontent.com/46865146/76050170-79705600-5fa1-11ea-9056-52a42c913841.jpg)

**Comment by nagadomi** [comment]
Download from https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip
I can see that you have installed the old version of mmd_tools.

**Comment by LsaNa1s** [comment]
But after I removed the plug-in which is old，install this new one. there was no response, I can't find it in the plug-in directory either. like this........(Ｔ▽Ｔ)
![QQ截图20200306114218](https://user-images.githubusercontent.com/46865146/76067153-e1d32d80-5fc9-11ea-94e0-8335999fc2a5.jpg)

**Comment by nagadomi** [comment]
`blender_mmd_tools-dev_test.zip` cannot be installed directly as a blender add-on.
Unzip `blender_mmd_tools-dev_test.zip` first and zip only the `mmd_tools` folder inside it, it will be a zip file that can be installed as a blender addon.
Or copy the `mmd_tools` folder to one of blender's addons folder.
See  https://github.com/powroupi/blender_mmd_tools/issues/253#issuecomment-546559216
