### ISSUE TITLE
2.82a - Cannot move (translate) bones on imported pmx model

### ISSUE THREAD

**Issue by microbry** [powroupi/blender_mmd_tools#274]
Hello, I am a new user trying to make an imported PMX model more animatable in Blender 2.82a. 

The models I have tried importing mostly work correctly.  I can import VMD motions to them, apply physics, etc. without issue and it's really promising.  However, when I try to move (grab/translate) a bone in pose mode, I can only move the IK controller bones in the feet.   I can only rotate or scale the other bones, and the grab gizmo does not even appear when it is selected (just the scale and rotate ones).   

Is this normal?  I can't seem to find anything about this issue online so far.   Ideally I would like to add some additional rigging controls to the armature for easier manipulation and control that I can integrate with imported motions, but this issue is blocking my progress in doing so.   I would prefer to work with the existing MMD armature and not have to switch to rigify or such if possible.   

Thanks for your time and effort on this project!

**Comment by nathanvasil** [comment]
MMD Tools transform locks bones according to their MMD bone type.  If you want to translate a bone not intended for translation, select that bone in pose mode and look on properties/bone/transform.  See the lock icons next to the fields?  Click on those lock icons to unlock transforms of that type, in those axes.

**Comment by microbry** [comment]
Thanks for the quick response!  I thought I must have been missing something somewhere, I will try this out.
