### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by IronLover64** [powroupi/blender_mmd_tools#275]
Is it possible to make a button that convers all mmd shaders to principled bsdf while retaining their image textures?

**Comment by NaughtDZ** [comment]
Great. I asked the same question before. As for the answer.....................

I think more people are needed to make this request,so it will be come true.

**Comment by powroupi** [comment]
Similar issues: #183, #248 .

I've added a parameter `Convert to Principled BSDF` to [Convert Materials For Cycles]. Currently, I only implemented a basic conversion. If you have any better idea, please provide more detailed information about how the node setup should look like. Thank you. :smile:

I think the only reason that you need `Convert to Principled BSDF` is to make the node setup to be compatible with FBX exporter on Blender 2.8x, etc. :sweat_smile: 

Ps.
If you want to use MMDShaderDev node group on Blender 2.7x, you can take a look this instruction https://github.com/powroupi/blender_mmd_tools/issues/207#issuecomment-473493745 .
