### ISSUE TITLE
Texture lost in rendering results

### ISSUE THREAD

**Issue by Lukikay** [powroupi/blender_mmd_tools#276]
Thanks for maintaining this tool, it works for me. But I got a texture lost problem in the rendering result.

The texture can display well on the solid model display (set color type as texture):
<img width="863" alt="00" src="https://user-images.githubusercontent.com/39486024/78354130-e5b09a80-75dd-11ea-9c86-37750c7944de.png">

But the texture lost and became some purple colour on the rendering result.
<img width="1025" alt="01" src="https://user-images.githubusercontent.com/39486024/78354566-b0587c80-75de-11ea-96a0-f19c93ff62be.png">

I pressed the 'Convert Materials For Cycles' button but still got this problem when rendering by Cycles.

I'm using blender 2.82a, thanks in advance for any possible solutions!

**Comment by nagadomi** [comment]
See https://github.com/powroupi/blender_mmd_tools/wiki/Mmd-Tools-Shared-Toon-Texture-Folder

**Comment by Lukikay** [comment]
> See https://github.com/powroupi/blender_mmd_tools/wiki/Mmd-Tools-Shared-Toon-Texture-Folder

Many thanks for your answer, but I believe that the texture image might be loaded already.

Otherwise, if Blender cannot find the texture image may lead the rendering result to get an entire purple appearance. Shown below:
![Annotation 2020-04-04 141518](https://user-images.githubusercontent.com/39486024/78420395-5957b380-7681-11ea-9130-5590e6c10cb6.png)

Currently, the skin and hair colour can be displayed properly, but the clothing lost their colour and became purple. I checked the texture image (*.png file), it looks like only the transparent part (alpha channel on) in the image that mapping to the model will lead the purple problem.

**Comment by nagadomi** [comment]
The MMD material may have three textures: base texture, toon texture and sphere texture (matcap). Each texture may or may not be set, depending on the material.
Toon textures are sometimes specified by a shared toon texture name instead of an image file, and Blender doesn't have it, so if the shared toon texture folder is not set, some materials will load incorrectly.

Depending on the model, the toon texture path may be wrong [the error is ignored on MMD, but on Blender it is purple].

**Comment by Lukikay** [comment]
> The MMD material may have three textures: base texture, toon texture and sphere texture (matcap). Each texture may or may not be set, depending on the material.
> Toon textures are sometimes specified by a shared toon texture name instead of an image file, and Blender doesn't have it, so if the shared toon texture folder is not set, some materials will load incorrectly.
> 
> Depending on the model, the toon texture path may be wrong [the error is ignored on MMD, but on Blender it is purple].

Thanks a lot, that's really helpful. Problem solved! 👍
