### ISSUE TITLE
Does this only work for Windows? 

### ISSUE THREAD

**Issue by fkkcloud** [powroupi/blender_mmd_tools#278]
Hi,

I am using 2.82a on OSX 10.15.1
I installed the mmd_tools folder in `/Users/username/Library/Application Support/Blender/2.82/scripts/addons`

I clocked on 'N' to open up viewport properties but I don't see MMD tab.
Any suggestions?

**Comment by nagadomi** [comment]
Is `mmd_tools` enabled in `Preference > Addon` ?
I am using this addon on Ubuntu Linux. It works.
I'm not familiar with OSX env, but https://github.com/powroupi/blender_mmd_tools/issues/212 (numpy issue) may be helpful.

**Comment by fkkcloud** [comment]
dev_tool version worked. thanks!
