### ISSUE TITLE
Question on Lat models

### ISSUE THREAD

**Issue by ptrthomas** [powroupi/blender_mmd_tools#28]
First - thanks for the awesome work on mmd_tools, I was able to cleanly export an FBX into Unreal Engine along with animation (including morphs) and here is the result: https://youtu.be/kX_KzIAYlK4

My question is on the [Lat models](https://bowlroll.net/file/30199) - if you import them into Blender via mmd_tools - the face looks distorted.  I don't have much idea about MMD textures and why this happens but my guess is I need to change some setting - for e.g. transparency, two-sided, unlit, no-shadow, etc.  I can make out that there are 2 or 3 different textures in the face that combine to create the final result.

In case you know more about the special textures that a Lat model face uses - do give me some tips.  My goal is to get a Lat model into Unreal Engine - and I am prepared to create a material from scratch.  Any information that helps me understand the basics of MMD "special" materials would be appreciated.  Thanks !

**Comment by powroupi** [comment]
Thank you, and great video again. :smile: 

I think the materials of pmd should be all single-sided, they were converted to double-sided (i've fixed that now with commit a854a5e). You might need to enable "Backface Culling" in "Shading" panel of 3d view properties to view single-sided faces correctly.

About the issue of her face, i guess the only way is to remodeling the face, because her face is not designed for true 3d rendering, shadows on face does not allowed. :(

**Comment by ptrthomas** [comment]
Thanks :) Appreciate the quick response - this helps.  I will check this later today when I get back home.

If you don't mind can you explain a few things for me:

a) toon texture - I think I understand this - it is a UV map that is in "blend multiply".  Is that correct ?
b) how do sphere and sphere map textures get used in blender ?
c) toon edge - how does this work in blender ?

**Comment by powroupi** [comment]
- Toon texture is used to define the color of shadow parts in MMD, i simply use "Normal" mapping and "blend multiply" to fake it in blender (2nd texture slot of material).
- Sphere texture also use "Normal" mapping, and blend type can be "Add" or "Multiply" (3rd texture slot of material).
- Currently, toon edge is configured for MMD, no effect in blender.

You might try @vipper36's branch [more_imitating](https://github.com/vipper36/blender_mmd_tools/tree/more_imitating), it has better result of "toon texture" and "toon edge". :smile:

**Comment by ptrthomas** [comment]
Great, I'm going to look at that more_imitating branch and learn more about MMD shading.  And it looks like this will indeed help me replicate a toon look using Unreal Engine materials.  Thanks !

Will close this issue.

**Comment by ptrthomas** [comment]
@powroupi you are awesome :)  I tried backface culling and shadeless and here is the result.  Thanks so much !

![lat-blender](https://cloud.githubusercontent.com/assets/915480/18089740/11383eec-6edf-11e6-8d04-0c8504dbcd3f.png)

**Comment by powroupi** [comment]
Thank you, you're welcome! :smile:

**Comment by lordscales91** [comment]
I'm glad to see this project is still alive, with people like you giving feedback and @powroupi doing an awesome work :smile: 

Just wanted to leave a comment here about the Lat models. Have you checked the mesh of the face? It's a complete mess up, at least from my point of view. The face is like composed by several layers.

![Lat face layers](http://i.imgur.com/EVWZ0DZ.png)

Probably it's done this way to achieve some effect on MMD. But still, it looks really weird and makes the model unusable for custom MME shaders like AdultShader

**Comment by ptrthomas** [comment]
Yep, as @powroupi said it is designed specifically to replicate "cel shading", no 3D shadows allowed.  Did you try GLSL + Shadeless + Backface Culling Enabled in blender ?  That should work, at least in blender.

Each layer has a purpose.  What I could make out: the leftmost one only exists to render the expressions (eyebrows, eye outline, mouth) - everything else disappears with backface culling.  The third one again should mostly disappear leaving a fake shadow on the sides.  Not sure about the last one, probably fake shadow again.  There is one more interesting one you missed which adds a black outline down the middle of the face (nose etc) which becomes visible when you view from the side (see my previous uploaded pic).  And the hair shadow on the face is fake, it is a brown translucent layer, thats all.

**Comment by lordscales91** [comment]
@ptrthomas WOW! I didn't expected it was all planned that way. Especially since, as far as  I know, the model was not originally designed for MMD, was ported from somewhere else (Previously to MMD the PVs were made with 3D editors like Metasequioa or Maya). Still, I don't like it, I want to use cool MME shaders :cry:

**Comment by ptrthomas** [comment]
Ah. My suggestion is don't waste your time trying to shade a Lat model, it is an exercise in frustration >_<

Unless you want to go for an "anime" look.  Then shadeless is the way to go.  Here is an example (Unreal Engine): https://www.youtube.com/watch?v=jGA6d_aMVlo

And you can compare this with the video I linked in my first post in this thread (same level / stage) so you can see the difference.

Something interesting I learnt recently is that it is westerners who like to "3D shade" stuff, but the Japanese are so influenced by anime that they don't like it that way.  Which may explain why MMD defaults and Lat models are the way they are.

If you really want to go deep here is an article, all the meat is in the video and it is pretty long: http://www.polygon.com/2015/5/26/8663003/guilty-gear-xrd-cel-shading-making-of

**Comment by lordscales91** [comment]
@ptrthomas Thanks for the information. But I'm not really in shaders (at least not now). It's just that I love the design of the Lat models and I would like to be able to use other shaders apart from the default. In fact, on my videos I never use the default shading.

The shading that I like the most is this one https://www.youtube.com/watch?v=PEce8W8Uxmc
But that shader is private. Do you think it will be possible to recreate this on Unity? I checked the video and the shading is similar.

Probably it would be much easier to create a Lat face replica than trying to "fix" the existing one. Hopefully a friend will do it for me, but he's very busy now.
