### ISSUE TITLE
Error while enabling the add-on

### ISSUE THREAD

**Issue by muzscaly** [powroupi/blender_mmd_tools#282]
![image](https://user-images.githubusercontent.com/15150065/80363666-d6dba180-8884-11ea-8aea-a2c196aa5edf.png)

I did a `--factory-startup` but it didn't work.

Blender 2.82 for Linux

**Comment by nagadomi** [comment]
See #212

**Comment by powroupi** [comment]
This issue is fixed in commit https://github.com/powroupi/blender_mmd_tools/commit/55e656506dd5ca198eafe0bcf5caa7f21191dc32, update your mmd_tools and try again. Thank you.
https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip
