### ISSUE TITLE
Not appearing in the addon preferences

### ISSUE THREAD

**Issue by LunaEye** [powroupi/blender_mmd_tools#283]
I followed the instructions for downloading and extracting and managed to successfully do that. But when I come to activating it in blender under the preferences it isn't showing on the list. I have the latest version of blender installed and have tried to re-extract the file several times by deleting, redownloading and extracting again but it dosen't seem to be working.

**Comment by 3dcinetv** [comment]
Upgrade to 2.8x Error warning when activating the addon in 2.82.
Is this fixed now?

**Comment by wilsoft-gt** [comment]
Same issue here!

**Comment by powroupi** [comment]
Might be the same issue with #98, #112..., there are so many issues about the installation, you might create an issue if none of those issues can help, thank you. :smile:

The addon installation in Blender should be an easy task. You can copy `mmd_tools` folder to addon path of Blender, or zip the `mmd_tools` folder for installing. Just remember to remove any existed `mmd_tools` addon before installing a new one.

ps. `mmd_tools` folder is the folder inside the zip file you downloaded.
https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip
