### ISSUE TITLE
Weight painting for new mesh

### ISSUE THREAD

**Issue by Vwings** [powroupi/blender_mmd_tools#284]
I added a new mesh made in blender to my mmd model by clicking "Atach meshes to model".But there are none vertex groups created for this new object, and I can't paint weight on this mesh.I found a solution: click "Join Meshes" and then "Separate By Materials", and vertex groups were added on my new mesh, but the Subdivison modifier was also applied. Is there a better way to paint weight for new mesh?

**Comment by powroupi** [comment]
Select your mesh object -> Shift select armature object -> [Ctrl+p] parent [With Empty Groups] or [With Automatic Weights].  (Inside 3D viewport menu, [Object]->[Parent]->[With Empty Groups] or [With Automatic Weights])

**Comment by Vwings** [comment]
> Select your mesh object -> Shift select armature object -> [Ctrl+p] parent [With Empty Groups] or [With Automatic Weights]. (Inside 3D viewport menu, [Object]->[Parent]->[With Empty Groups] or [With Automatic Weights])

Thanks
