### ISSUE TITLE
Cant enablwe the addon

### ISSUE THREAD

**Issue by ghost** [powroupi/blender_mmd_tools#286]
![pleacehelp](https://user-images.githubusercontent.com/44642708/82460037-58f46a00-9ac1-11ea-882e-c1c61ebbba00.png)

**Comment by StefansArya** [comment]
Duplicate of #280

**Comment by powroupi** [comment]
~According to the error message, `properties.register()` should be in line 126 in latest `mmd_tools`, so I think you have installed an old version of `mmd_tools` in "D:\New Folder\bored\2.82\scripts\addons\mmd_tools".~

Never mind, I forgot `mmd_tools\__init__.py` has been changed recently. :blush:
