### ISSUE TITLE
Baked focal length is rounded on export

### ISSUE THREAD

**Issue by parse2** [powroupi/blender_mmd_tools#287]
When I check "Bake Animation" in the MMD camera converter, it properly bakes everything. Upon exporting the camera as a .vmd, however, the focal length is rounded to the nearest integer, causing jittery movement. Baked location and rotation are correctly exported. Is this a limitation of VMD, or a bug? Example blend file linked below; first scene contains the original camera and second scene contains the imported camera.

[ex2.blend.zip](https://github.com/powroupi/blender_mmd_tools/files/4673825/ex2.blend.zip)

![image](https://user-images.githubusercontent.com/64366201/82758114-a23f0500-9db2-11ea-953f-59113742db07.png)
![image](https://user-images.githubusercontent.com/64366201/82758123-b256e480-9db2-11ea-916e-aef7b91934de.png)

**Comment by powroupi** [comment]
Yes, this is a limitation of VMD, not sure why keyframes of camera angle are saved as Integer. :cry: However, the interpolations are working fine. So you might use Blender's built-in addon [Add Curve: Simplify Curves] to simplify/cleanup F-Curves after baking the animation, and then export VMD. It's the only way to workaround this issue. :smile:

**Comment by parse2** [comment]
👍 Thanks for the info.
