### ISSUE TITLE
Question About Configuring the "Textures" Folders (and a few Other Questions)

### ISSUE THREAD

**Issue by SpongeMan777** [powroupi/blender_mmd_tools#288]
Note: I am very new to Blender and MMD modeling, so I apologize in advance if any of these questions have a very clear answer to them.

Hi everyone!

I recently installed this addon onto Blender with no problems, however I became confused when I had to configure the addon. I understood that the "shared toon texture folder" should be the directory in the MMD program called "data," and the "dictionary folder" already had a directory folder associated with it, so I didn't change it. However, I'm confused on the "base texture folder," and what path to set it to. I did read the tutorial, but I don't understand what they mean by "path for textures shared between models. In order to copy textures properly while exporting to pmx file."

Another question I'd like to ask is: how do you apply textures to custom MMD models in Blender? (or models that come in their own folder with their own textures) I assume that it has to do with the configuration of the addon with the directories of the texture folders, like I was talking about in my first question.

The third, and final, question I have is based upon the eyes of the models. For me at least, they don't appear to show up at all in Blender. I can't tell if this is an error on my part, or if this is how it is supposed to look.

I provided pictures for questions two and three. The picture with the comparison of the custom model in MMD and Blender (Blender version having no textures) is for question two, and the comparison of the default (included with MMD program) model in MMD and Blender (Blender version has no eye textures) is for question three.

Thanks for reading! :)

![custom_model_in_mmd_blender_comparison](https://user-images.githubusercontent.com/65981353/82965976-8daf6800-9f7e-11ea-80f8-f9e3115f8e55.jpg)

![default_model_in_mmd_blender_comparison](https://user-images.githubusercontent.com/65981353/82965983-943ddf80-9f7e-11ea-97ef-c96c9e3d6d71.png)

**Comment by powroupi** [comment]
>However, I'm confused on the "base texture folder," and what path to set it to.

You can leave it empty, it was implemented from powroupi#7 , here is a short description https://github.com/powroupi/blender_mmd_tools/issues/33#issuecomment-252410285 .

To show textures on Blender's 3d viewport, you can change [Viewport Shading] to `Material Preview` or `Rendered` mode. There are also some options in [Solid] mode. Here are the documents:
https://docs.blender.org/manual/en/latest/editors/3dview/introduction.html
https://docs.blender.org/manual/en/latest/editors/3dview/controls/shading.html

You can configure material settings in MMD Material panel and MMD Texture panel (under Material tab of [Properties Window](https://docs.blender.org/manual/en/latest/editors/properties_editor.html). Mesh object selected to be the active object.)
https://github.com/powroupi/blender_mmd_tools/wiki/Guide-to-the-mmd_tools-Interface

ps. the shading would be different from MMD. You would need to tweak shader nodes and scene lighting to accomplish different result you want. The default shading provided by `mmd_tools` is very basic. :expressionless:

**Comment by SpongeMan777** [comment]
Thank you for clarifying this!

Have a nice rest of your day man :)
