### ISSUE TITLE
Is there a way to edit the texture's shader without removing it?

### ISSUE THREAD

**Issue by Titaniumbot360** [powroupi/blender_mmd_tools#289]
So, I've been trying to find a way to apply a shader on an MMD model's texture, but is there a way to apply without removing the color from the model?

**Comment by powroupi** [comment]
I think there is no texture's shader editor in Blender Internal (2.7x) fashioned way on Blender 2.8x, you can directly remove the texture and edit the shader in Shader Editor.

If you want to mix some shader with MMD model's texture, you can edit it freely in material nodes or duplicate `MMDShaderDev` node group for editing inside the duplicated node group.
