### ISSUE TITLE
mmd tool says i need to upgrade to blender 

### ISSUE THREAD

**Issue by EnderWiggins642** [powroupi/blender_mmd_tools#296]
says that i need to upgrade to blender 2.8x but im using 2.83
![2020-07-01](https://user-images.githubusercontent.com/67703971/86269470-c652ea80-bb97-11ea-841c-dc7e05361ba3.png)

**Comment by Heartran** [comment]
Same problem
![immagine](https://user-images.githubusercontent.com/51830223/89109539-5eb3e780-d442-11ea-8375-73cc884d76e4.png)

I can't figure it out considering that on my other computer works (it was installed on a different version and then moved with the Steam update)

**Comment by nagadomi** [comment]
mmd_tools you have installed is a old version that does not support Blender 2.8x.
Uninstall it and install the latest version.
https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip

**Comment by dinoking27** [comment]
mine is having the same problem too

**Comment by powroupi** [comment]
Please install `dev_test` branch https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip, it's the only one works on Blender 2.8 or later.
