### ISSUE TITLE
How do i fix this?

### ISSUE THREAD

**Issue by sassinzz13** [powroupi/blender_mmd_tools#298]
Hi there How do i fix this kind of error?
iam using blender 2.83
![help](https://user-images.githubusercontent.com/66528388/86828288-9b035a80-c0c5-11ea-9589-f978f029346b.png)

**Comment by nagadomi** [comment]
You can fix it by changing the name of `mmd_tools23` folder back to `mmd_tools`.

**Comment by sassinzz13** [comment]
Thank you very much its now working
