### ISSUE TITLE
Question - renaming of bones

### ISSUE THREAD

**Issue by ptrthomas** [powroupi/blender_mmd_tools#30]
As always, here's my latest video: https://www.youtube.com/watch?v=5GQkTrOy2kQ - once in a while I get questions about my workflow and I always refer people here, to this fork.  Thanks again for making this addon so good @powroupi  !

While I'm getting deep into Unreal Engine I have the need now to rename bones.  So here are my questions:
- in case I rename one of the MMD standard bones, and then later if I try to import motion (VMD) - will that work ?  Maybe the VMD import uses a property and not a name ?  Would you have any idea ?
- one of the problems is Unreal Engine does not like "." in bones and renames it to "_".  So far it works fine, but now I need a workflow that exports out of UE.  Which brings me to my next question:
- I am thinking maybe I should modify the code to rename all the mmd standard bones to english.  And at the same time VMD import should still work.  Which files should I look at.  Any tips or suggestions would be great.

I am willing to do all the code myself, but wanted to check with you in case you know of some problems or limitations with existing code I need to be aware of.

**Comment by powroupi** [comment]
Thank you very much :smile: , and nice video i've watched recently. :+1: 

> in case I rename one of the MMD standard bones, and then later if I try to import motion (VMD) - will that work ? Maybe the VMD import uses a property and not a name ? Would you have any idea ?

It will work if you don't change the property **mmd_bone.name_j** and use bone mapper **'PMX'** when importing VMD, you can rename blender's bone name as whatever you like. But note, the blender's function **Copy/Paste Pose** may break **mmd_bone.name_j**, see issue #20.

> I am thinking maybe I should modify the code to rename all the mmd standard bones to english....

I think the simplest way is to write your own script to change blender's bone name in blender's text editor. (Currently the most important thing about importing VMD is the **mmd_bone.name_j**)

If you want to modify the addon directly, you can reference **mmd_tools.core.pmx.importer.PMXImporter.__renameLRBones()** and **mmd_tools.core.model.Model.renameBone()**.
(you might only need to modify _PMXImporter.__renameLRBones()_, simple as well) :smile: 

P.S.
You will need to change coresponding bone names of vertex groups of mesh objects to keep armature modifier work when changing blender's bone name. (related code _Model.renameBone()_)

**Comment by ptrthomas** [comment]
Thanks @powroupi - this is exactly the kind of information I was looking for.  **mmd_bone.name_j** sounds like it will perfectly work for me.

And yes I'll start with a script, see how that goes and then think of submitting a pull request for _PMXImporter.__renameLRBones()_

I think I remember seeing somewhere in the code that there was a conversion table, for example what I want to do is this kind of renaming:

腕捩.R --> armtwist_R
ひじ補助.R --> elbowaux_R

Does something like this mapping already exist, or I will create it.

**Comment by powroupi** [comment]
You're welcome. :smile: You might also reference englishmap.py from pymeshio:
[https://github.com/ousttrue/pymeshio/blob/master/pymeshio/englishmap.py](https://github.com/ousttrue/pymeshio/blob/master/pymeshio/englishmap.py)

If you want to submitting a pull request about this feature, maybe we need to add an import option for this, you might implement another function (say _PMXImporter.__renameLRBonesEN()_) or add a parameter, ex. _PMXImporter.__renameLRBones(method='EN')_, so that users can choose which version of renaming bones that they like. :smile:

**Comment by ptrthomas** [comment]
That is a great reference.  I want to improve that mapping so it works for most japanese bone names, let me take a look.  And yes, I like your suggestion, especially method='EN' 👍 

Closing this ticket.
