### ISSUE TITLE
Multiple Code Bugs for Mac

### ISSUE THREAD

**Issue by mrrfyW** [powroupi/blender_mmd_tools#306]
<img width="802" alt="Screen Shot 2020-09-12 at 3 56 06 PM" src="https://user-images.githubusercontent.com/69284371/93003908-818ced80-f510-11ea-9148-5587a2f6c1d0.png">

Can you please fix these?

**Comment by mrrfyW** [comment]
[DELETED FOR PRIVACY REASONS]

**Comment by powroupi** [comment]
Duplicate of #292
