### ISSUE TITLE
Not compatible with Blender 2.9

### ISSUE THREAD

**Issue by CrazyToaster975** [powroupi/blender_mmd_tools#307]
Hello, just letting you guys know that this is not working on Blender 2.9. It is telling me to "upgrade" to 2.8

**Comment by PF94** [comment]
time to downgrade back to blender 2.83 for now

**Comment by nagadomi** [comment]
See #296, #249, ...
mmd_tools is compatible with 2,83, 2.90, 2.91.

**Comment by seemon2** [comment]
> See #296, #249, ...
> mmd_tools is compatible with 2,83, 2.90, 2.91.

Hi Nagadom,
I think mmd_tools is compatible to 2.92 that I am using. But it does not work on 2.93 ..
Any plan to upgrade to 2.93?

**Comment by nagadomi** [comment]
@seemon2 I've send Pull Request #338. With this change, it works with 2.93 and 3.0, but may not be merged until the official release of Blender 2.93.

**Comment by seemon2** [comment]
Thanks .. will wait for the official 2.93 release then.

**Comment by powroupi** [comment]
@CrazyToaster975
Please install `dev_test` branch https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip, it's the only one works on Blender 2.8 or later.
