### ISSUE TITLE
Rigid Body collision groups not functioning properly

### ISSUE THREAD

**Issue by Unseen110** [powroupi/blender_mmd_tools#313]
I set up my model's rigid body groups in PMXEditor so that the arms do not collide with cloth/hair, and it works fine in MMD. But when I convert the model to Blender, the arms still do collide with cloth&hair. I checked the rigid body settings under MMD Rigid Body tab in Blender and it all looks like the way I set it up in PMXEditor, but the collision rules still aren't working.

**Comment by nagadomi** [comment]
`Preferences > Addon > mmd_tools > preferences > Non-Collision Threshold`.
Setting the above property to 100 and then rebuilding the physics(`MMD Tab > Physics: Clean,Build`) will probably solve this problem.
mmd_tools uses non-collision constraints to simulate MMD's collision group mask in Blender. if the distance between the rigid bodies is greater than `Non-Collision Threshold`, the non-collision constraint for them is not created for performance reasons.

**Comment by Unseen110** [comment]
Ok yeah that works, thanks
