### ISSUE TITLE
Addon not appearing in Blender 2.91

### ISSUE THREAD

**Issue by Roxote** [powroupi/blender_mmd_tools#315]
![image](https://user-images.githubusercontent.com/19556825/100375629-df4bb480-2fec-11eb-8c3e-950328fd9e7f.png)

Not even showing after I extracted the zip in the correct folder for blender 2.91

**Comment by zephyroths** [comment]
in the zip there's a directory called mmd_tools. that's what you should copy to the addons directory.

**Comment by Roxote** [comment]
My bad, now it's showing correctly after doing what you said.

Thank you!

**Comment by HyperGroups** [comment]
I have the same problem, even after copy the directory.
