### ISSUE TITLE
A bug in the viewport of blender 2.91

### ISSUE THREAD

**Issue by Bancho29** [powroupi/blender_mmd_tools#317]
I often use blender_mmd_tools, but I will report a bug found in 2.91.

When exporting an MMD model with the exporter of blender_mmd_tools (0.7.1, December 8, 2020 version) in blender 2.91, screen fraud was confirmed in "solid mode" of viewport.
(It did not occur in 2.90)

![画像1（2 91エクスポート）](https://user-images.githubusercontent.com/19154759/101962077-87e54f80-3c4e-11eb-88fb-f6a6fb88a179.png)
Image 1 (2.91 export)

![画像2（2 90エクスポート）](https://user-images.githubusercontent.com/19154759/101962081-89167c80-3c4e-11eb-8301-85ae997edaa1.png)
Image 2(2.90 export)

![画像3（モデル移動）](https://user-images.githubusercontent.com/19154759/101962083-89af1300-3c4e-11eb-9a23-fe316442e0e0.png)
Image 3 (when moving the model)

OS used is windows 10 20H2 x64,GPU used is RADEON RX560 (4GB), and the drivers are Radeon Pro Software for Enterprise 20.Q4 and Radeon Software 20.11.1

Currently, there is no choice but to take the following measures.
* Remove all materials
* Set viewport to something other than "solid mode"
* If you still want to use solid mode, set "Color" in "Solid mode" to other than "Material" and set "X-RAY" to Off.

![画像4（対処法1）](https://user-images.githubusercontent.com/19154759/101962084-8ae04000-3c4e-11eb-9a79-66e860228b8b.png)
Image 4 (Countermeasure 1)

![画像5（対処法2）](https://user-images.githubusercontent.com/19154759/101962086-8c116d00-3c4e-11eb-943d-858cea686530.png)
Image 5 (Countermeasure 2) - "X-RAY" to On　

Please correct it.

**Comment by Bancho29** [comment]
（日本語版）
blender_mmd_toolsをよく利用していますが、2.91にてバグが発見されたので報告します。

blender 2.91にてblender_mmd_tools（0.7.1、2020年12月8日版）のエクスポーターでMMDモデルをエクスポートした時、viewportの「ソリッドモード」で画面の不正が確認されました。
（2.90では発生しませんでした）

![画像1（2 91エクスポート）](https://user-images.githubusercontent.com/19154759/101962077-87e54f80-3c4e-11eb-88fb-f6a6fb88a179.png)
画像1（2.91エクスポート）

![画像2（2 90エクスポート）](https://user-images.githubusercontent.com/19154759/101962081-89167c80-3c4e-11eb-8301-85ae997edaa1.png)
画像2（2.90エクスポート）

![画像3（モデル移動）](https://user-images.githubusercontent.com/19154759/101962083-89af1300-3c4e-11eb-9a23-fe316442e0e0.png)
画像3（モデルを移動する場合）


使用OSはwindows10  20H2 x64、使用GPUはRADEON RX560（4GB）、ドライバはRadeon Pro Software for Enterprise 20.Q4 及びRadeon Software 20.11.1 です

現状では下記の対処方法を取るしかありません。

- マテリアルをすべて除去する
- viewportを「ソリッドモード」以外に設定する
- それでもソリッドモードを使いたい場合、「ソリッドモード」の設定の「Color」を「Material」以外、尚且「X-RAY」をOffにする

![画像4（対処法1）](https://user-images.githubusercontent.com/19154759/101962084-8ae04000-3c4e-11eb-9a79-66e860228b8b.png)
画像4（対処方法1）

![画像5（対処法2）](https://user-images.githubusercontent.com/19154759/101962086-8c116d00-3c4e-11eb-943d-858cea686530.png)
画像5（対処方法2）-「X線」をオン

修正お願いします。

**Comment by powroupi** [comment]
Thanks for reporting this issue. :smile: 

I can not reproduce this issue on my computer, so I think it's an issue of graphic card (driver).

Additionally, you might try 'Load Factory Settings' (blender.exe --factory-startup) to identify the issue:
1. Import/Export any FBX model without enabling any other addons.
2. Import/Export any MMD model (PMD/PMX) with only `mmd_tools` enabled.

It should be an issue of `mmd_tools` if it only happens in case 2. Thank you. :smile: 

(Google Translated)
この問題を報告していただきありがとうございます。:smile: 

この問題は自分のコンピューターでは再現できないので、グラフィックカード（ドライバー）の問題だと思います。

さらに、「初期設定を読み込み」（blender.exe --factory-startup）を試して、問題を特定することもできます。
1. 他のアドオンを有効にせずに、FBXモデルをインポート/エクスポートします。
2. `mmd_tools`のみが有効になっているMMDモデル（PMD / PMX）をインポート/エクスポートします。

ケース2でのみ発生する場合は、 `mmd_tools`の問題になるはずです。ありがとうございます。:smile:

**Comment by Bancho29** [comment]
Thank you for your reply.
First of all, the "export" in the above report was a mistake of "import" ...

I tried powroupi's reply, but it was as follows.

1. Import / export FBX model without enabling other add-ons.
![画像6（初期設定でFBXインポート）](https://user-images.githubusercontent.com/19154759/101983480-9408f580-3cbe-11eb-88a3-f9f4b42b292e.png)
Image 6 (FBX import by default)/画像6（初期設定でFBXインポート）
![画像7（移動2）](https://user-images.githubusercontent.com/19154759/101983482-95d2b900-3cbe-11eb-9899-44977ad78998.png)
Image 7 (when moving the model)/画像7（モデルを移動する場合）

   It didn't happen here.

2. Import / export MMD models (PMD / PMX) with only mmd_tools enabled.
![画像8（初期設定でpmxインポート）](https://user-images.githubusercontent.com/19154759/101983481-953a2280-3cbe-11eb-97ac-0ebeb3167f49.png)
Image 8 (pmx import by default)/画像8（初期設定でpmxインポート）

   It happened here.


（日本語版）
返答ありがとうございます。

まず訂正ですが、上記の報告の「エクスポート」は「インポート」の間違いでした…

powroupi 様の返答を試しましたが、以下の通りでした。

1. 他のアドオンを有効にせずに、FBXモデルをインポート/エクスポートします。 

　　こちらでは発生しませんでした。

2. mmd_toolsのみが有効になっているMMDモデル（PMD / PMX）をインポート/エクスポートします。

　　こちらでは発生しました。

**Comment by nagadomi** [comment]
I can not reproduce this issue on my computer too. (Linux, GTX1080, Blender 2.91.0)
If you get glitches when you change `Cube > Material Properties Tab > Viewport Display > Metallic/Roughness`, it's not an issue of mmd_tools.
It may be due to mmd_tools changing the viewport display for each material when importing the model (It is used when type=SOLID and color_type=MATERIAL).

私の環境でも再現できません。(Linux, Blender 2.91.0)
`Cube > マテリアルプロパティタブ > ビューポート表示 > メタリック/粗さ`を変更したときにグリッチする場合はmmd_toolsの問題ではありません。
mmd_toolsがモデルインポート時に各マテリアルのビューポート表示を変更していることに起因しているかもしれません（それはソリッドモードのカラー=マテリアルのときに使用されます）。

**Comment by nagadomi** [comment]
Maybe this issue is related to the following blender's issue.
https://developer.blender.org/T82856
There have been various reports of viewport rendering issues with AMD GPU.
Looks like a similar problem: https://developer.blender.org/T83022

**Comment by Bancho29** [comment]
Thank you for your reply, nagadomi.

> I can not reproduce this issue on my computer too. (Linux, GTX1080, Blender 2.91.0)
> If you get glitches when you change `Cube > Material Properties Tab > Viewport Display > Metallic/Roughness`, it's not an issue of mmd_tools.
> It may be due to mmd_tools changing the viewport display for each material when importing the model (It is used when type=SOLID and color_type=MATERIAL).

In this environment, the display was normal even if I changed `Cube> Material Properties tab> Viewport Display> Metallic / Roughness`,

> Maybe this issue is related to the following blender's issue.
> https://developer.blender.org/T82856
> There have been various reports of viewport rendering issues with AMD GPU.
> Looks like a similar problem: https://developer.blender.org/T83022

What was mentioned in was exactly the defect that was mentioned here.

I knew it wasn't a problem with mmd_tools, but I also understood that it was a problem with the driver or Blender itself ...

（日本語版）
nagadomi様、返答ありがとうございます。

> 私の環境でも再現できません。(Linux, Blender 2.91.0)
> `Cube > マテリアルプロパティタブ > ビューポート表示 > メタリック/粗さ`を変更したときにグリッチする場合はmmd_toolsの問題ではありません。
> mmd_toolsがモデルインポート時に各マテリアルのビューポート表示を変更していることに起因しているかもしれません（それはソリッドモードのカラー=マテリアルのときに使用されます）。

こちらの環境では`Cube > マテリアルプロパティタブ > ビューポート表示 > メタリック/粗さ`を変更しても表示は正常でしたが、

> Maybe this issue is related to the following blender's issue.
> https://developer.blender.org/T82856
> There have been various reports of viewport rendering issues with AMD GPU.
> Looks like a similar problem: https://developer.blender.org/T83022

で挙げられたのは、まさしくこちらの挙げた不具合そのものでした。

mmd_toolsの問題でないのは分かりましたが、むしろドライバかBlender本体の問題ということも理解しました…

**Comment by powroupi** [comment]
>Currently, there is no choice but to take the following measures....

@Bancho29
Looks like it is an issue of Viewport alpha/transparency of Blender 2.91 on some graphic cards. If there is no issues with rendering, you can disable [the following code of mmd_tools/core/material.py](https://github.com/powroupi/blender_mmd_tools/blob/1cd2bcbb023ec04c4b07bfd9013be927017ee058/mmd_tools/core/material.py#L541-L544) to prevent this issue of `mmd_tools`. :smile: 
```python
        if hasattr(mat, 'alpha'):
            mat.alpha = mmd_mat.alpha
        elif len(mat.diffuse_color) > 3:
            mat.diffuse_color[3] = mmd_mat.alpha
```
to
```python
        #if hasattr(mat, 'alpha'):
        #    mat.alpha = mmd_mat.alpha
        #elif len(mat.diffuse_color) > 3:
        #    mat.diffuse_color[3] = mmd_mat.alpha
```
Or reset alpha value of every material from Blender Console Window.
```python
>>> for m in D.materials: m.diffuse_color[-1]=1
...
>>>
```

(Google Translated)
@Bancho29 
一部のグラフィックカードでのBlender2.91のビューポートアルファ/透明度の問題のようです。 レンダリングに問題がない場合は、[mmd_tools/core/material.py のコード](https://github.com/powroupi/blender_mmd_tools/blob/1cd2bcbb023ec04c4b07bfd9013be927017ee058/mmd_tools/core/material.py#L541-L544)を無効にして、この `mmd_tools`の問題を防ぐことができます。:smile:
```python
        if hasattr(mat, 'alpha'):
            mat.alpha = mmd_mat.alpha
        elif len(mat.diffuse_color) > 3:
            mat.diffuse_color[3] = mmd_mat.alpha
```
このように変更します
```python
        #if hasattr(mat, 'alpha'):
        #    mat.alpha = mmd_mat.alpha
        #elif len(mat.diffuse_color) > 3:
        #    mat.diffuse_color[3] = mmd_mat.alpha
```
または、Blenderコンソールウィンドウからすべてのマテリアルのアルファ値をリセットします。
```python
>>> for m in D.materials: m.diffuse_color[-1]=1
...
>>>
```

**Comment by Bancho29** [comment]
Thank you for your reply, powroupi.

> Looks like it is an issue of Viewport alpha/transparency of Blender 2.91 on some graphic cards. If there is no issues with rendering, you can disable [the following code of mmd_tools/core/material.py](https://github.com/powroupi/blender_mmd_tools/blob/1cd2bcbb023ec04c4b07bfd9013be927017ee058/mmd_tools/core/material.py#L541-L544) to prevent this issue of `mmd_tools`. 😄
> 
> ```python
>         if hasattr(mat, 'alpha'):
>             mat.alpha = mmd_mat.alpha
>         elif len(mat.diffuse_color) > 3:
>             mat.diffuse_color[3] = mmd_mat.alpha
> ```
> 
> to
> 
> ```python
>         #if hasattr(mat, 'alpha'):
>         #    mat.alpha = mmd_mat.alpha
>         #elif len(mat.diffuse_color) > 3:
>         #    mat.diffuse_color[3] = mmd_mat.alpha
> ```
I confirmed that it was dealt with by the above correction.
I want you to set it as an option.

Thank you very much.

（日本語版）
powroupi様、返答ありがとうございます。

> 一部のグラフィックカードでのBlender2.91のビューポートアルファ/透明度の問題のようです。 レンダリングに問題がない場合は、[mmd_tools/core/material.py のコード](https://github.com/powroupi/blender_mmd_tools/blob/1cd2bcbb023ec04c4b07bfd9013be927017ee058/mmd_tools/core/material.py#L541-L544)を無効にして、この `mmd_tools`の問題を防ぐことができます。😄
> 
> ```python
>         if hasattr(mat, 'alpha'):
>             mat.alpha = mmd_mat.alpha
>         elif len(mat.diffuse_color) > 3:
>             mat.diffuse_color[3] = mmd_mat.alpha
> ```
> 
> このように変更します
> 
> ```python
>         #if hasattr(mat, 'alpha'):
>         #    mat.alpha = mmd_mat.alpha
>         #elif len(mat.diffuse_color) > 3:
>         #    mat.diffuse_color[3] = mmd_mat.alpha
> ```

上記の修正で対処されたのを確認しました。
オプションとして設定してほしいぐらいです。

ありがとうございました。

**Comment by powroupi** [comment]
>I confirmed that it was dealt with by the above correction.
I want you to set it as an option.

Sorry, I am not going to add an option for that. It may be fixed by Blender or graphic card driver since Blender 2.90 works normally on your system. There would be lots of options if we want to meet everyone's request, and I would not be able to maintain it. :cry:

(Google Translated)
申し訳ありませんが、そのためのオプションを追加するつもりはありません。 Blender 2.90はシステム上で正常に動作するため、Blenderまたはグラフィックカードドライバによって修正される可能性があります。 皆様のご要望にお応えしたいのであれば、選択肢はたくさんあり、メンテナンスはできません。:cry:

**Comment by Bancho29** [comment]
> Sorry, I am not going to add an option for that. It may be fixed by Blender or graphic card driver since Blender 2.90 works normally on your system. There would be lots of options if we want to meet everyone's request, and I would not be able to maintain it. 😢

 I understand.

（日本語版）
> 申し訳ありませんが、そのためのオプションを追加するつもりはありません。 Blender 2.90はシステム上で正常に動作するため、Blenderまたはグラフィックカードドライバによって修正される可能性があります。 皆様のご要望にお応えしたいのであれば、選択肢はたくさんあり、メンテナンスはできません。😢

了解しました。
