### ISSUE TITLE
Can't preview several morphs at once. Using b 2.91, 0.7.1

### ISSUE THREAD

**Issue by Penty2** [powroupi/blender_mmd_tools#318]
I have a model, made for mmd, which have 4 stage bone morph transformation, which apparently requires to activate all 4 related morphs. It would be nice to have that option as well as well as option of partially adjust it in same way as shape keys "value"

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: 

Not sure if I understand it right, looks similar with powroupi#237 . Currently, `mmd_tools` can/will bind all morphs listed in Morph Tools panel, and you can adjust morph's values listed in the panel after binding. But you will need to bind again for newly created items, it's a limitation.

**Comment by Penty2** [comment]
> Not sure if I understand it right
All four morphs was made to be activated one after another, without turning them off. If You trying to see just one morph, model is turning into mess

**Comment by Penty2** [comment]
Thanks, I it helped now
