### ISSUE TITLE
Motion acting weird

### ISSUE THREAD

**Issue by xxeverlee** [powroupi/blender_mmd_tools#319]
MMD tools was working perfectly fine until I updated my PC with the new Windows 10 update. After PC got updated, when I loaded in motions for any sort of model, the motion would be weird and not be the same as it was in MMD. The motions work perfectly fine in MMD, just not blender.
![1](https://user-images.githubusercontent.com/38105807/103358160-eac64b80-4a82-11eb-8589-e6e99840d2d6.png)
![2](https://user-images.githubusercontent.com/38105807/103358165-ed28a580-4a82-11eb-8747-0ba117e798fd.png)

**Comment by nagadomi** [comment]
Make sure that `Scale` option for model import and `Scale` option for motion import are the same.
https://github.com/powroupi/blender_mmd_tools/wiki/Documentation#scale-2

**Comment by xxeverlee** [comment]
> Make sure that `Scale` option for model import and `Scale` option for motion import are the same.
> https://github.com/powroupi/blender_mmd_tools/wiki/Documentation#scale-2

Ah, I'm an idiot. That fixed it, thanks!
