### ISSUE TITLE
Correct textures, but incorrect color? (2.9 blender)

### ISSUE THREAD

**Issue by jay5656** [powroupi/blender_mmd_tools#321]
I'm having issues with textures. They're mapped correctly and show up. But they have a purple tint applied to them? 

https://imgur.com/a/Zy4pvP4

Is this user error or an error with the add on?

**Comment by nagadomi** [comment]
mmd_tools does not include the MMD's default toon textures (toon01.bmp~toon10.bmp).
You can fix it by setting the MMD's `Data` folder to `Preferences > Add-ons > mmd_tools > Shared Toon Texture Folder`.
https://github.com/powroupi/blender_mmd_tools#configuring-addon

**Comment by jay5656** [comment]
> mmd_tools does not include the MMD's default toon textures (toon01.bmp~toon10.bmp).
> You can fix it by setting the MMD's `Data` folder to `Preferences > Add-ons > mmd_tools > Shared Toon Texture Folder`.
> https://github.com/powroupi/blender_mmd_tools#configuring-addon

Oh. So I need mmd installed and then tell the add on where to look? 

I honestly thought I could just download mmd models and just put them in blender without mmd

**Comment by nagadomi** [comment]
It just references the texture images. You do not need to be able to run MMD on your local machine.

I guess that it is not included due to licensing issues. 
Though I personally don't think the author of MMD claims the copyright of toon01.bmp ~ toon10.bmp.

**Comment by jay5656** [comment]
Is there a way where I don't have to use those textures? Does mmd tools come with others built in I could use to fix the problem? 


And I'm still a little confused. Where would I find those files if I don't install mmd?

**Comment by nagadomi** [comment]
>Is there a way where I don't have to use those textures?

If you uncheck `Material Tab > MMD Texture > Use Shared Toon Texture`, the MMD's toon textures will not be used.

>Where would I find those files if I don't install mmd?

1. Downlaod `1.3 MikuMikuDance(DirectX9 Ver)` from https://sites.google.com/view/vpvp/, or https://learnmmd.com/downloads/
2. Unzip it, you will find it in MikuMikuDance_v932/Data.

**Comment by jay5656** [comment]
> > Is there a way where I don't have to use those textures?
> 
> If you uncheck `Material Tab > MMD Texture > Use Shared Toon Texture`, the MMD's toon textures will not be used.
> 

Did this and it's still purple. I guess I have no choice but to download mmd and use the shared texture folder?

**Comment by nagadomi** [comment]
>Did this and it's still purple.

This setting exists for each material. All materials should be unchecked.

**Comment by jay5656** [comment]
This works, thank you for the help. If I find another problem I'll open another issue.
