### ISSUE TITLE
Installs without error but not actually showing up in 2.91

### ISSUE THREAD

**Issue by GeminiSquishGames** [powroupi/blender_mmd_tools#323]
I have the latest download as of January 15, 2021. I have tried both installing the .zip and extracting it to both %appdata%/BlenderFoundataion plugin folders and the plugin folders in the Blender install directory. It says the files are successfully written and there are no errors when installing. No errors at all but it will not show up in the addon view for selection, thus will not show the import/export selections in file menu. I have repeated the task 4 times and tried 2,92 as it is now in beta for testing. Neither show when I have Community and User filters active.

**Comment by lanning1990** [comment]
> I have the latest download as of January 15, 2021. I have tried both installing the .zip and extracting it to both %appdata%/BlenderFoundataion plugin folders and the plugin folders in the Blender install directory. It says the files are successfully written and there are no errors when installing. No errors at all but it will not show up in the addon view for selection, thus will not show the import/export selections in file menu. I have repeated the task 4 times and tried 2,92 as it is now in beta for testing. Neither show when I have Community and User filters active.

Don't install the addon from the zip file, or directly copy the hierarchy folder. Instead, open the hierarchy folder and copy the folder called "mmd_tools" mannually to the appdata.......plugin/addon directory, open the folder and you'll see an "__init__.py" file, that's how blender recognize it.

**Comment by aidanhasaknife** [comment]
I was experiencing this issue too, but your follow-up helped me! Should we close this issue, perhaps pin it?
