### ISSUE TITLE
Stage Motion not working?

### ISSUE THREAD

**Issue by xxeverlee** [powroupi/blender_mmd_tools#326]
I've never put stage motion on a stage before in blender, so I did the same thing I normally do for models and imported the motion onto the stage, but the stage motion isn't working? 
Thanks!! =/

**Comment by nathanvasil** [comment]
Does the motion do anything to the stage when used in MMD?  (No real difference between a .pmx character and a .pmx stage, they're both bones, but the bones are likely to have different names, and animation is dependent on the names of bones.)

**Comment by xxeverlee** [comment]
Sorry for not replying earlier, but it doesn't do anything. I'm going to test it with another stage with another motion and see if it works.

**Comment by xxeverlee** [comment]
Alright, it works with the other stage I had that had motion data. I think it may just be the stage itself or something. Should I send a link to the stage I'm trying to get to work?
(Also sorry I don't use github that much)

**Comment by nathanvasil** [comment]
I think you should check the names (bones and morphs) used by both the stage and the animation.  If they're not the same, then the animation won't do anything.

**Comment by xxeverlee** [comment]
Ah, I think I found something. Would the stage motion not play if the stage had no shape keys? The stage has only 1.

**Comment by nathanvasil** [comment]
It depends on what is contained in the animation.  Again, only bones (and morphs) that the animation refers to will get animated.

**Comment by xxeverlee** [comment]
Ah, alright. Thanks anyways for helping, I think it may have to do with missing bones in the stage
