### ISSUE TITLE
Documentation questions and issues

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#33]
I'm making this as a general purpose thread to ask questions and report issues discovered during in-depth testing for creating decent documentation.

1) Apply and Clean Bone constraints.  I'm having a lot of trouble understanding what this does.  It apparently does something though.

2) Rename bones.  In my testing, enabling or disabling this checkbox on model import has no effect.  Either way, I get a bunch of boxes for my bone names.  Is this not implemented, or am I doing something wrong?

3) Influence of .sph and .spa textures.  This also appears to be non-functional.  I'm not seeing a difference in any fields when changing this value, and I'm not seeing any difference in the rendered view.  Is this working?

4) Log file.  When enabled, where does the log file get written?  I can't find it anywhere.

5) Build and clean rigid bodies.  My interpretation of this is that "build" transforms rigid bodies as used in MMD into a fashion that can be used in Blender, whereas "clean" returns them to their MMD-friendly state, and so built rigids should be used when animating in Blender, whereas clean rigids should be used when exporting.  Is that accurate?

**Comment by powroupi** [comment]
1) It is for applying the settings of move/rotate append. Because of the difference of bone math between MMD and Blender, simply use copy location/rotation in blender will not get correct result with MMD, thus the shadow/dummy bones are used to solve it. Even though, bone issues are not totally solved yet (might never be solved or impossible). :(

2) Go to [Blender User Preferences]->[System]->Enable [International Fonts], will solve the box name issue, you will see the difference. Disable [Rename bones] will give you original japanese names, Enable it will give you japanese names in *.L/*.R form.

3) The value will be assigned to diffuse color factor of texture slot that use .sph and .spa texture. Go to a material which uses sphere textures and go to texture tab, in 3rd slot, you will see the diffuse color factor is assigned to the value you set. You might set shadeless view to see more clear (hit [Shadeless] button in [MMD Shading] panel in 3d view properties, also you can on/off [Sphere Textures] in [MMD Display] panel).

4) Log file will be saved in the same folder with pmx file. The log file name is in the form '*.mmd_tools.import.log' / '*.mmd_tools.export.log' .

5) Yes. If you export a built model, it will return to clean state.

:smile:

**Comment by nathanvasil** [comment]
Thanks for all info.

Regarding sphere influence, my error was that I was changing mult sphere influence and expecting it to affect add sphere influence (I think of both as being sphere maps.  MMD's word choices are kind of unfortunate-- wish they'd used "spm" instead of "sph".)

1) Just out of curiosity, why is it that MMD Tools does not just build rigids and apply bone constraints on import?  And clean on export, if necessary?

2) What is the purpose of the "sort materials" checkbox on the model export dialog?  Exported models appear to respect the material order specified in mmd_utils/material sorter regardless of whether this is checked.

3) Change MMD IK Loop Factor button on properties/object/MMD Model Information is always grayed out for me.  Is this out of date, or is it something that functions only in a very specific context?

Edit: IK loop factor appears with an armature selected.  How does this function?  Does it overwrite IK loop settings?  Does it apply a multiplier to each IK bone?  Are these changes propagated to an export?  Do they affect in-Blender animation?

**Comment by powroupi** [comment]
> ...wish they'd used "spm" instead of "sph"

I guess sph is their first use (first 3 charactors of 'sphere'), and then add support for 'ADD' type of sphere textures (so spa may be 'sphere add'). :smile: 

1) Build rigids may take a lot of time and create lots of temparary objects, and if we just want to check VMD motions, we don't need to build rigids, and thus have better performance. So it is better to build rigids only when you want to render final animations.

2) It will calculate the draw order of materials (sort materials for alpha blending), it should work for static meshes (without vertex morphs). But i rarely use it, it's better to control ourselves.

3) It is enabled only when the active object is a armature. It is used to quick change the IK iterations in blender. Yes, it apply a multiplier to each IK bone, but without changing to an export, the multiplier will be remember (visible in [Custom Properties] panel), so we know original loop values. Increasing IK iterations in blender usually get better animation, but it affects the performance. :)

EDIT:
I forgot to mention that: to view shared toon texture correctly in blender, users need to setup addon preference of mmd_tools. Go to [Blender User Preferences]->[Addons]->[mmd_tools]->[Preferences]->[Shared Toon Texture Folder].

**Comment by nathanvasil** [comment]
Thanks.  https://github.com/powroupi/blender_mmd_tools/wiki/Documentation-Draft is updated.  Almost done :)  

We're getting into stuff that I just learned this morning, in order to understand what I'm writing.  I've never done any animation in Blender previously.  So expect some dumb questions :)

1) Import Motion, Bone Mapping: It seems that you should use PMX on an import for which you didn't enable bone renaming, Renamed Bones when you did.  When should you use the third (Blender) choice?

2) Import Motion, Update Scene Settings: This supposedly tells Blender to use 30 FPS.  It says that it also tells Blender the length of the animation, but I'm not seeing my animation bar change in size (from the default 0-250 frames).  What exactly are all of the effects of enabling Update Scene Settings?  If multiple motions are imported in a scene, does the most recent choice for Update Scene Settings determine the end settings?

3) Properties/Object/MMD Rigidbody, MMD Joint Tools: Am I right in assuming, like similar MMD panels, that changes made here will affect Blender behavior, but changes to these objects elsewhere in Blender won't affect exports?  Will changes here affect rigid bodies after they have been built, or only prior to building them?

4) Properties shelf/MMD Shading: Is it intended that Reset return Viewport Shading to solid?  I notice that GLSL creates a huge jump in ambient lighting, one unlike enabling GLSL in the regular Blender Shading subsection.  Is this intended?

Edit: In Blender 2.77, I don't see any way to select preferences for specific add-ons; User Preferences/Addons only seems to allow me to enable or disable addons, not set any specific information for them.  What am I doing wrong?

**Comment by powroupi** [comment]
1) Yes, `PMX` is the default, you might rarely use others. If you import a model without enabling `Rename Bones` stuff, then the option `Blender` will also work for importing VMD. Similar, `Renamed bones` will work if you enabled `Rename Bones - L / R Suffix` on importing a model. The `Blender` and `Rename Bones` is used when your `mmd_bone.name_j` is broken. More detail:
- PMX: the bone name in VMD file will be mapped to the `mmd_bone.name_j` value
- Blender: the bone name in VMD file will be mapped to the blender's bone name
- Rename Bones: the bone name in VMD file will be renamed to L/R suffix, then be mapped to the blender's bone name (this needs to be updated to support `Use Underscore` and `To English` options)

2) It only update frame range and fps. Frame range is update to suit for all actions, not only the motion you're importing. If you import a motion 'A', 100 frames, the range is updated to 1-100, and then import a motion 'B', 300 frames, the range is updated to 1-300, and then import a motion 'C', 200 frames, the range is (still) updated to 1-300.

3) Changing the values of MMD properties will update corresponding values with blender (for many MMD properties), but changing blender's properties will not update MMD's. And only MMD properties affect exports.
You still can change some parameters after they have been built, most parameters are taken from blender's physics. But some parameters should not be changed to prevent confusion, for detail:
- Rigid bodies: Rigid Type / Target Bone / Collision Group / Collision Group Mask / Transforms
- Joints: Object1 / Object2 / Transforms

4) Yes, the behaviors are not changed. (The same as @sugiany's master) `GLSL` button creates a `Hemi` light which is hidden, but you should be able to see it in the outliner.

EDIT) You should be able to expand the panel to see detailed information of an addon by hitting the triangle (left side) of the addon panel. :smile:

**Comment by nathanvasil** [comment]
Thanks for all answers!

Draft of completed documentation is at https://github.com/powroupi/blender_mmd_tools/wiki/Documentation-Draft .

I would appreciate if you, or anyone else, could take a look for anything missing, or any obvious errors.  I have tried to be as complete as possible, but there's so much I don't know that it would be easy for me to miss something, or write something not quite accurate.

If you have any corrections or additions, please feel free to make them.  I abandon the copyright on this text, so it's now public domain, and you can do anything with it that you would like.

If you lack confidence with English, but feel that something should be added or changed, please say so. I don't mind rewording your changes, if that's what you'd like.

Feel free to attach this to mmd_tools at any time.

**Comment by powroupi** [comment]
Okay, thank you so much for your help. :+1: 

Maybe we can make some visual improvements, like header/large text, bold text, etc. :smile: 

And if you have any suggestion about UI texts/descriptions of this addon, please let me know, or make a pull request for me if you know how to use git. Thank you. :smile:

**Comment by nathanvasil** [comment]
I didn't do any formatting, because I wasn't sure in what file format you'd like to distribute it (your last was just .txt, where I don't believe there's any formatting possible).  Feel free to do any formatting you'd like.  If you'd like for me to format for a particular type of file, just let me know.

I don't know how to use git.  Was there some text that you'd like me to look at?

**Comment by powroupi** [comment]
Yes, formatting is possible, it is a [markdown style](https://guides.github.com/features/mastering-markdown/) and we can easily edit it on GitHub (there will also have some informations on the toolbar when we edit the wiki pages). :smile: 

> Was there some text that you'd like me to look at?

Yes, i think you might be able to have some suggestions about the UI texts/hover texts/descriptions of this addon in blender. :)

**Comment by nathanvasil** [comment]
Sure, if you just want it edited for wiki, rather than distribution, I can do that.  Give me a few days, I'm in the midst of a few other projects.

Happy to take a look at mouse-over text and offer suggestions.  Might as well keep this issue open, I'll just offer it here.  Again, give me a few days though.

**Comment by powroupi** [comment]
Great, thank you, and there is no time limit, do this when you have free time. :smile:

**Comment by ptrthomas** [comment]
Thanks @nathanvasil I'll be happy to review, help with formatting and even upload the odd image or two, will do over the weekend.

**Comment by nathanvasil** [comment]
Thanks @ptrthomas , that'd be awesome!

**Comment by nathanvasil** [comment]
@powroupi 

Looked over interface.  I don't think there are any large problems, and it might not be worth your time to change anything.  Notes are too long for a comment, available at https://github.com/powroupi/blender_mmd_tools/wiki/interface-notes

**Comment by powroupi** [comment]
@nathanvasil 
Thanks for your suggestions, i'll make an update based on it after confirming some Q&A. :smile: 

> some morphs have an 'i' icon (information?)

The 'i' icon only means the morph item is not yet added to Display Pane.

> would drop Material morphs affecting all materials (index -1) are given an index with an empty name; would rename this to "All Materials" Material morphs affecting all materials are provided an 'i' icon

Sorry, i'm not sure about this. Do you mean display "All Materials" instead of empty name, and use an 'i' icon instead of a material icon?

> properties/Modifiers mmd_bone_order_override:

It's not possible to add hover text for this, `mmd_bone_order_override` is just a user defined name of the modifier. You can rename it to other name so that the exporter will not use that mesh's vertex groups to define the bone order.

> Base Texture Folder: Change mouseover text to, "Alternate path for shared textures", if I understand the purpose correctly

It is an information to the exporter to determine the texture's relative path when `Copy Textures` is enabled. For example, if base texture folder is `C:\MyTextures\`, and you use a texture `C:\MyTextures\toons\myToon.bmp`, then when you export the model to a folder `C:\Test\`, the texture `myToon.bmp` will be copied to `C:\Test\toons\myToon.bmp`, other textures will be copied to default folder `C:\Test\textures\`. (so i'm not sure how to call this...)

**Comment by nathanvasil** [comment]
"The 'i' icon only means the morph item is not yet added to Display Pane."

Okay, thanks.  Would be nice if there was some way to indicate that in UI, but I'll modify the wiki documentation to give an indication.

"Sorry, i'm not sure about this. Do you mean display "All Materials" instead of empty name, and use an 'i' icon instead of a material icon?"

Sorry, I didn't use proper punctuation.  First: Display "All Materials" instead of empty name.  Second: To the right of the 'i' icon that already exists below (below 'Material' field, above 'Offset Type' field), there is a line reading, "This offset affects to all materials".  Change that line to, "This offset affects all materials".

I think talking about relative directories with regards to Base Texture Folder is confusing.  The function of this folder is a place to store textures shared between models, right?  Then I would just use, "Path for textures shared between models".  I think that will give the gist, and if people use it, they'll see what it does, and perhaps be pleasantly surprised that it stores relative paths properly.

**Comment by powroupi** [comment]
> First: Display "All Materials" instead of empty name. Second: To the right of the 'i' icon that already exists below...

Ok, i got it. :smile: 

> The function of this folder is a place to store textures shared between models, right? Then I would just use, "Path for textures shared between models". 

Ok, i'll use "Path for textures shared between models" as mouseover text. :smile:

**Comment by powroupi** [comment]
Okay, i've updated my branch, you might check it and keep report suggestions and issues when you found some. Thank you. :smile: 

Notes:
-  MMD Rigid Body:
  - **mass / restitution / friction / linear&rotational damping** are blender's physics parameters, so hover text can not be changed.
  - i'm not sure about the difference between **Physics** and **Physics + Bone**, and the physics of built model in blender may more similar to **Physics**, but may not be the same.
-  Japanese / English name:
  - some reference attributes are reference to Japanese name, so showing both for being easier to assign those attributes.
  - Japanese / English name of **MMD Bone / MMD Material / MMD Rigid Body / MMD Joint** are not synced to their blender's name (may add a operator to do that in the future).

**Comment by nathanvasil** [comment]
As far as I can see, it looks good.

I've formatted the wiki documentation (and changed the page name/url, seeing as it's no longer a draft), which is available at https://github.com/powroupi/blender_mmd_tools/wiki/Documentation .  Anyone and everyone should feel free to make any changes they want.

It may need updating in the future, but I think that it's done for now, so I'll close this issue.  Thanks for your help!

**Comment by powroupi** [comment]
Looks great, thank you very much. :smile:
