### ISSUE TITLE
Camera angle is missing with with 2.93/3.0

### ISSUE THREAD

**Issue by leucome** [powroupi/blender_mmd_tools#343]
There is no MMD camera angle input field when used with blender 2.93 and 3.0 . So the the MMD angle is not transferred to the Blender focal length.

**Comment by powroupi** [comment]
Update your mmd_tools addon. Because the properties of MMD camera were not registered correctly before the fix powroupi#338.
https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip
