### ISSUE TITLE
motion vmds not doing anything

### ISSUE THREAD

**Issue by invisyarcticfox** [powroupi/blender_mmd_tools#344]
so i got this addon earlier today and it's been working absolutely fine, apart from there's this one file which when imported does nothing. i don't know if this is on the addon's side or the file's side but another .vmd file works with no problems so I don't really know. 

the file that works is a camera movement file while the other (that doesn't work) i assume is an armature movement file. don't really know what's going on.

**Comment by powroupi** [comment]
- If you want to import a VMD to a MMD model in Blender, select the root empty object(s) of the MMD model(s) and then import the VMD file. (select only armature object will only import bone motion, select only mesh object will only import shapekey motion)
- If you want to import a VMD which contains camera motion, add a new camera object and then import the VMD file.
- If you want to import a VMD which contains light/lamp motion of the MMD's default light, add a new sun light object and then import the VMD file.

That's it.

**Comment by Hogarth-MMD** [comment]
The instructions given by @powroupi should work. If not, the bone names in the .vmd file probably don't match the bone names of the model.

To see the bone names in a .vmd file, you can use this free utility:
VMDConverterGraphical (converts VMD files to CSV text files and CSV text files to VMD files)
https://bowlroll.net/file/13705

To list the bone names of a model in Blender, select the armature object and type this line of code into the Blender python console, then press Enter:

bpy.context.active_object.data.bones.keys()

Also you can see the bone names of an MMD model in PMD/PMX editor.

**Comment by invisyarcticfox** [comment]
what if the model i have isn't mmd? I'm assuming it won't work then since it's not mmd and I'm trying to import a vmd.

**Comment by Hogarth-MMD** [comment]
If you can succeed to import a .vmd animation onto a model which is not an MMD model, this event will be new information for everyone,  and you will be the first person who has succeeded in this accomplishment.
