### ISSUE TITLE
Blender 2.93 compatibility

### ISSUE THREAD

**Issue by SolMMD** [powroupi/blender_mmd_tools#348]
Traceback error when importing, exporting pmx file
![Capture](https://user-images.githubusercontent.com/85269441/120581307-71d77100-c3df-11eb-8c66-1bd3d0f49561.PNG)

**Comment by powroupi** [comment]
I've updated `mmd_tools`, please update your `mmd_tools` addon and try again.
https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip

If you don't see this error again after using latest `mmd_tools`, you can close this issue then. Thank you. :smile:

**Comment by SolMMD** [comment]
It works! Thank you so much ^^
