### ISSUE TITLE
how fix?

### ISSUE THREAD

**Issue by BossZe** [powroupi/blender_mmd_tools#349]
![Screenshot (424)](https://user-images.githubusercontent.com/72904963/120960406-f7fc0a80-c785-11eb-9882-9041f4bb4f23.png)

**Comment by powroupi** [comment]
Well, I am curious how this error happened. :thinking: 
Please go to Blender's [Python Console] window (hotkey [Shift]+F4) and paste the result of the following commands:
```
>>> import mmd_tools
>>> mmd_tools.__file__
>>> len(mmd_tools.__bl_classes)
>>> import os
>>> [os.path.join(os.path.basename(r),n) for r,d,f in os.walk(os.path.dirname(mmd_tools.__file__)) for n in f if str(n).lower().endswith('py')]
>>> 
```
Or copy the commands and paste them in Blender's [Python Console] at once:
```
import mmd_tools
mmd_tools.__file__
len(mmd_tools.__bl_classes)
import os
[os.path.join(os.path.basename(r),n) for r,d,f in os.walk(os.path.dirname(mmd_tools.__file__)) for n in f if str(n).lower().endswith('py')]

```

**Comment by shankarsivarajan** [comment]
I had the same problem after upgrading to Blender 2.93. Uninstall the addon, delete the installed mmd_tools folder (probably ~\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_tools), and reinstall the latest version, NOT the release 0.7.0.

**Comment by broken-gage** [comment]
> I had the same problem after upgrading to Blender 2.93. Uninstall the addon, delete the installed mmd_tools folder (probably ~\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_tools), and reinstall the latest version, NOT the release 0.7.0.

I got the same error. What do you mean by not the 0.7.0? Is there any newer version after 0.7.0?

**Comment by shankarsivarajan** [comment]
Download the current "dev_test" branch as .zip (Code > Download ZIP), extract it, zip the mmd_tools folder, and install that.

**Comment by powroupi** [comment]
For people who have issues when installing `mmd_tools`, please see issue powroupi#98 (or powroupi#91, powroupi#92). Sorry, I don't see any other possibility that cause the installation error. :cry:

**Comment by nagadomi** [comment]
I think the best way to avoid installation problems is to create an installable addon zip file.

If it is acceptable to make major changes to the repository, use `git mv` to change the directory hierarchy, making the `mmd_tools` directory the top-level directory. You can create a temporary repository or branch to test it.

Alternatively, one could use https://download-directory.github.io/ or something similar to have it download the `mmd_tools` subdirectory. If you have some experience in web programming, you can fork it and create a dedicated download website for mmd_tools.

Although it will take time period to get rid of the old mmd_tools installed environment.

**Comment by shankarsivarajan** [comment]
It would be far simpler to leave the repo as is and just include the installable .zip (i.e., just the mmd_tools folder zipped) with the releases.

**Comment by nagadomi** [comment]
I am guessing it is not done because it takes a lot of work to deploy a small commit.

Aside from that, an installable zip file can be created with the gitarchive command.
```
git archive --prefix mmd_tools/ -o ./mmd_tools.zip HEAD:mmd_tools
```
Also, releases can be created from the command line using the [Github CLI](https://cli.github.com/).
```
gh release create <tag> [<files>...]
```
Document: https://cli.github.com/manual/gh_release_create

**Comment by Githubdude15** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/85956711/122093117-017f1580-ce0b-11eb-8ab8-b3274adafc17.png)
![Screenshot (2)](https://user-images.githubusercontent.com/85956711/122093126-03e16f80-ce0b-11eb-8c6c-69eb6d3039ac.png)

new Version 0.7.2 works for me. 0.7.1 does not work.

**Comment by SonicVegeta** [comment]
![Blender Preferences 2021-08-12 12_29_35 PM](https://user-images.githubusercontent.com/88847586/129233941-5173433e-b380-4497-91fd-599e7d0fcb29.png)
what about this then?

**Comment by powroupi** [comment]
@SonicVegeta, please see issue powroupi#253.

**Comment by BossZe** [comment]
Thanks everyone for helping 
is now fixed 

Im try to Closed comments :)

**Comment by boss23150** [comment]
Thanks everyone for helping

Is now fixed im try to closed the comments
