### ISSUE TITLE
Cant load MMD Model

### ISSUE THREAD

**Issue by TheGremanCharizard** [powroupi/blender_mmd_tools#351]
Hey everyone.
So after the 2.93 Version of Blender I cant Load any MMD Modls into Blender.
When I try it I always gat that Massage:
![Blender 20 06 2021 20_28_27](https://user-images.githubusercontent.com/86265925/122826034-fa607780-d2e2-11eb-848b-cacfbc9bb78a.png)
Can some say to me if this is just a bug or something else?
I would really appreciative that.

**Comment by nagadomi** [comment]
That error has already been fixed in #348 .
You just need to update mmd_tools to the latest version.

**Comment by TheGremanCharizard** [comment]
Oh Hey Thanks for the Advice.
Sorry for that. I was thinking I already have the New's version of. (0.7.1)
I already update it to the newest version know it is on 0.7.2.
Sorry again for that trouble. Pleas don't mind.
Also I just want to say Thanks for that Great Addon!
I really appreciative your Hard work you put in to it!
Keep up that great work!
