### ISSUE TITLE
bone chain endings pointing straight up after model import

### ISSUE THREAD

**Issue by bennyd87708** [powroupi/blender_mmd_tools#355]
I'm having an issue where many bone chain endings (leafs?) in the armature import are pointing straight up when they shouldn't be. Apologies if I am simply missing an import setting for auto orient bones or ignore leafs or something like that, I'm not very experienced. I've tried using Blender 2.79b, 2.83, and 2.93. Here is a screenshot of what it looks like on the model's hands (it happens elsewhere too but this is the most visible location).
![bbc3a0bdf57738d9b71dee50a451a12e](https://user-images.githubusercontent.com/6503310/123742743-11faab80-d861-11eb-893f-00557cb77d37.jpg)
Also I'm using all out Ahri from [this mmd download on deviantart](https://www.deviantart.com/jerememez/art/MMD-K-DA-ALLOUT-MODELS-DOWNLOAD-BADDEST-UPDATE-860001994) if anyone ends up wanting to try it themselves.

**Comment by nagadomi** [comment]
Those finger bones are tip bones (zero length bone). Tip bone does not have length and direction.
Blender can't display a bone with zero length, so a simple bone is displayed instead.
I think this is the issue on the model side.

**Comment by bennyd87708** [comment]
Ah I understand. I guess that means there isn't any fix besides manually orienting everything. Thank you for the insight!
