### ISSUE TITLE
Attempting to change the order in the mesh sorter creates an error

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#36]
Exact text of error is

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.77\scripts\addons\mmd_tools\operators\misc.py", line 182, in execute
    prev_mesh = rig.findMeshByIndex(current_idx - 1)
  File "C:\Program Files\Blender Foundation\Blender\2.77\scripts\addons\mmd_tools\core\model.py", line 408, in findMeshByIndex
    if i < 0:
UnboundLocalError: local variable 'i' referenced before assignment

location: <unknown location>:-1

To reproduce:

Import a .pmx and separate by materials.  Change to mmd_utils tab.  Select a mesh in the mesh sorter subsection.  Hit the up or down arrows.  This seems easily reproducible throughout models, so I'm not including an example file, but let me know if you need one.

**Comment by powroupi** [comment]
Oh, sorry, it is my fault on commit bd28157, i'll fix that soon. :smile:

**Comment by powroupi** [comment]
Well, this issue should be fixed now, and you can close it. Thank you. :smile:

**Comment by nathanvasil** [comment]
Verified, thanks.
