### ISSUE TITLE
AMD Visual Issue

### ISSUE THREAD

**Issue by KFaath** [powroupi/blender_mmd_tools#363]
I had this problem on an earlier pc and solved it by rolling back the drivers but I'm hoping for a better fix this time.
Blender 2.9 and latest mmd_tools installed, pmx files look like this
![Screenshot 2021-08-29 174510](https://user-images.githubusercontent.com/88812377/131242851-30dd031f-8ce2-4347-9cc7-043073b7adda.png)
then after moving the camera it gets worse
![Screenshot 2021-08-29 174524](https://user-images.githubusercontent.com/88812377/131242863-718c52b3-a86a-49ca-8176-5a2b633dc051.png)

Running latest AMD Drivers, any ideas on a fix?

**Comment by net2cn** [comment]
This is probably the same as #325 and #317.
It might be a blender bug.
