### ISSUE TITLE
Not working for Blender 3.0

### ISSUE THREAD

**Issue by jeffnghongda** [powroupi/blender_mmd_tools#377]
The plugin is not supported for blender 3.0, are there plans to update this to be compatible to B3.0?

**Comment by baizhi958216** [comment]
put ```mmd_tools``` floder to ```%AppData%\Blender Foundation\Blender\3.0\scripts\addons```

**Comment by baizhi958216** [comment]
> The plugin is not supported for blender 3.0, are there plans to update this to be compatible to B3.0?

put ```mmd_tools``` floder to ```%AppData%\Blender Foundation\Blender\3.0\scripts\addons```

**Comment by powroupi** [comment]
It should work using latest `mmd_tools`. You can try my fork https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip
or @UuuNyaa's fork https://github.com/UuuNyaa/blender_mmd_tools/releases. :smile:
