### ISSUE TITLE
Morph translation

### ISSUE THREAD

**Issue by StrangerGithuber** [powroupi/blender_mmd_tools#41]
Hello
First of all, thank you your updates. You save my life. :)
Can you add a function which help to translate Morph japanese names to english?
"Rename bones to english" very handy so I though Morph translate also will be good.

(I wanted to add this in "Pull requests" but its appears on another developer site so I write here in Issues. I hope its appear here not there.)

**Comment by ptrthomas** [comment]
I think the "other developer" you are referring to is me ^_^

In fact I want to translate the material names also (which is useful especially when you export to other apps like Unreal Engine).  I was planning to do this so let me look at morph names also.

**Comment by ptrthomas** [comment]
@LeaderSoul oh I see it now, you made a pull request on the original project by @sugiany .  I am not the dev here - it is @powroupi - but I was involved in the english translation code.

**Comment by powroupi** [comment]
@LeaderSoul If you didn't intend to make the pull request sugiany#55, you might need to close it. (I guess you just wanted to make a feature request) :)

About "Morph translate", currently i don't have any good idea to implement it, and it's a little complex to integrate to "Morph Tools", sorry. :cry: Maybe @ptrthomas or other developers could help this, and i might try to implement it as well once i got any good idea. Thank you. :smile:

**Comment by ptrthomas** [comment]
@powroupi I was looking at the code - and yes, it seems complex.  I was thinking if we just fill the morph_name_e - would that help users who just want a translation.  Or maybe, we just need a tooltip to show the translated name.  Or something similar.

**Comment by powroupi** [comment]
> @ptrthomas  I was thinking if we just fill the morph_name_e - would that help users who just want a translation.

Yeah, it is much easier to do and maybe just add a import option or operator, say "Fill English Names", and then fill all `.name_e` stuff if the string is empty. :) But i think we still need a tool (or a rule) to update corresponding blender's name properties (shape key names, material names, etc.). :thinking:

**Comment by lordscales91** [comment]
I don't how much the code changed since the last time I checked, but I think we could also add a property to `VertexMorph` to store the reference to the shape key (`sk_name` for example). That way the names of the shape keys can be in English, which is probably what @LeaderSoul wants. (Of course this will require more changes in other parts of the code that reference the shape keys)

**Comment by StrangerGithuber** [comment]
Specifically:
Can you add a new option in import part which is helps translate automatically the morphs name?
