### ISSUE TITLE
Separate stage models

### ISSUE THREAD

**Issue by StrangerGithuber** [powroupi/blender_mmd_tools#44]
Hello
First I want apologize because I can't start new request in "Pull request" because its redirect to sugiany's side when I click to "New pull request" button. (I know,  I am very beginner :P )

If it's ok, then I write here my request.
So my request is all stage objects/models will export separate automatically. 
For example: I import the stage then in export or somewhere else I can click to a checkbox which is "Export each models separately" and then the plugin/blender will create different fbx file (if someone will export in fbx). First fbx will be a house, second chair, third table, etc...

It sounds big and difficult request, but hopefully can be created. :)

**Comment by nagadomi** [comment]
>I can't start new request in "Pull request" because its redirect to sugiany's side 

You can choose the `base fork`.
![6bf3a5b972817bd4c11c182a7d0ba508](https://cloud.githubusercontent.com/assets/287255/20606348/abde1eea-b2b3-11e6-83de-ff1265dff22e.png)

**Comment by StrangerGithuber** [comment]
Thank you. I created this request in Pull request. :)

**Comment by powroupi** [comment]
Hi, @LeaderSoul , This addon can export a model in pmx file format only, sorry. :cry: 
Do you want to export multiple MMD models at once, or want to export a MMD model in separate models?

**Comment by StrangerGithuber** [comment]
Hmm, I did before that I imported MMD models with this addon in blender and exported to fbx.
Yeah, if it is possible export MMD model in separate models.

E.g: Import MMD models all at once. Which is a house with window, wall, chair, table, flower, etc... and export window, wall, chair, table, flower, etc with one click.

Now I can import a stage, but when I import then the stage is a whole model, doesn't separate those different objects as I mentioned above. So when I export then also the stage one model which is not good if I want use in the game.

I found a solution, but not good. If I separate those objects in PMX Editor and save those objects in different pmx files then I can export in different fbx files.
BUT if the stage is very big then this procedure take a lot of time. So I thought it will be good if it is possible with this addon only with one click I can separate those objects in different fbx file.

**Comment by powroupi** [comment]
Okay, i think it's possible (not too hard) to import multiple *.pmx/*.pmd files at once, and also possible to export multiple MMD models at once.

But i'm not sure how to do to export a MMD model in separate models. :thinking: Do you want to export each mesh object of a MMD model which contains multiple mesh objects to individual ones?

**Comment by StrangerGithuber** [comment]
Yeah, if it is possible. :)

**Comment by powroupi** [comment]
Okay, i guess i understand your requirements, i'll try it. :smile:
