### ISSUE TITLE
Bone size too small

### ISSUE THREAD

**Issue by StrangerGithuber** [powroupi/blender_mmd_tools#45]
Hello
When I exported from Blender and imported to Unreal Engine then I get this message:

Warning The bone size is too small to create Physics Asset 'TestModel_PhysicsAsset' from Skeletal Mesh 'TestModel'. You will have to create physics asset manually.

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: 

I just google searched `"Warning The bone size is too small to create Physics Asset"`. I guess you can try changing the scale from 0.2 to 20 when you import a MMD model. :)

**Comment by StrangerGithuber** [comment]
I will try this when I compiled the Unreal Engine 4.13 to linux because before I had 4.14 version. Today I will try as you mentioned above and I will report you if it works or not.

**Comment by StrangerGithuber** [comment]
Hello
Yeah, it works now. :) I suggest add a checkbox or other option in import that "Fit to Unreal Engine". 
For example: There is a checkbox with this text "Fit to Unreal Engine" and then the addon will import the MMD Model. 

I suggest only if someone else also will use MMD models and in this case someone else will not ask you the same as me. :)

**Comment by powroupi** [comment]
The scale value i suggested above is just a guess value (multiply 100 from google search, it's a workaround for now), and i'm not sure the math behind it. And it might be an issue of fbx exporter, so it may not be necessary to change the scale if the issue get fixed. :)
