### ISSUE TITLE
scaling confusion in mmd_tools

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#62]
When an MMD model is imported into Blender using mmd_tools, by default it is scaled to 0.2 of its original size. Why is this done? The likely answer is that in MMD, each grid square is 5X5 units, while by default each Blender grid square is 1X1 unit.

Problem: Scaling confusion exists in mmd_tools.

The default scale for VMD (both import and export) and for VPD (both import and export) is 0.2. Now if someone imports a pose or animation with scale 0.2 and then exports it with scale 0.2, then by a straightforward mathematical calculation, someone should expect that the final result will be 1/25 of the size of the original size. This is a weird, confusing flaw of mmd_tools. And when an MMD model is imported, the default scale is 0.2 but when it is exported mmd_tools does not give the user even a clue of what the export scale is. More scaling confusion!

In fact, it is completely unnecessary to scale MMD models, poses or animations to 0.2 when importing them into Blender. Instead of doing that, it is possible to scale the Blender grid. I wrote this python code (below) to do exactly that. If someone runs this python script from the Blender text editor and then imports an MMD model with a scale of 1.0, it will look the same in Blender's camera view as it looks in MMD's camera view or model view when you import an MMD model into MMD.

**Comment by Hogarth-MMD** [comment]
```python
# Scales the Blender grid, thereby making it unnecessary to scale MMD models 

import bpy

for o in bpy.context.scene.objects:
	if o.data == bpy.data.cameras[0]:
		camera = o
		bpy.context.scene.objects.active = camera
		bpy.ops.mmd_tools.convert_to_mmd_camera() 
# moves the camera to the world origin(0,0,0), x rotation 90 degrees, y rotation 0 degrees, z rotation 0 degrees
# creates an empty object at the world origin(0,0,0), x,y,z rotations = (0,0,0) , empty object is made parent of the camera

camera.parent.location[2] = 10 #MMD y (height) 10, Blender z (height) 10
camera.location[1] = -45 # = MMD camera distance
camera.parent.mmd_camera.angle = 0.523599 #(camera lens viewing angle, 0.523599 radians = 30 degrees)


screens = ['Animation', 'Scripting', 'UV Editing', 'Default']

for screen in screens:
	for area in bpy.data.screens[screen].areas:
		if area.type == 'VIEW_3D':
			area.spaces[0].grid_lines = 20
			area.spaces[0].grid_scale = 5
			area.spaces[0].region_3d.view_perspective = 'CAMERA'
			# Possible options are [‘PERSP’, ‘ORTHO’, ‘CAMERA’]
```

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: I guess many people also have the same question. But sorry for my english, I may not be able to explain well. :cry: 

Simply put, the data (model, motion, pose) will be multiplied by the scale on importing, and divided by the scale on exporting. By the way, there is not a scale option when export a model, because the scale is stored in the root object (**MMD Model Information** panel).

And do not be troubled about the grids, increasing/scaling the grid does not help anything, just need to consider the data. Maybe it is better to use scale 1.0 as default, but the gravity of physics in blender will need to be adjusted. I'm not sure exact value to match MMD physics, maybe **-49.05 (= -9.81 * 5)**. :confused: 

So, you could change default scale as you like, and I think the scale option is necessary when you want to import/export motions/poses for different size models. :smile:

**Comment by Hogarth-MMD** [comment]
"the gravity of physics in blender will need to be adjusted. I'm not sure exact value to match MMD physics, maybe -49.05 (= -9.81 * 5)"

I do not understand this at all. The gravity influences mass, not volume.

**Comment by Hogarth-MMD** [comment]
"Simply put, the data (model, motion, pose) will be multiplied by the scale on importing, and divided by the scale on exporting."

Are you saying to  me that you have no intention to correct this error? Scaling is and should always be a multiplying operation.

**Comment by Hogarth-MMD** [comment]
"By the way, there is not a scale option when export a model, because the scale is stored in the root object (MMD Model Information panel)." 

This is very unhelpful and inadequate if someone wants to convert a model to MMD from other software, or someone does not know about this aspect of MMD tools.

**Comment by Hogarth-MMD** [comment]
"But sorry for my english, I may not be able to explain well. 😢"

@powroupi  I applaud you and thank you for your excellent Engliish.  Your English is much better than the English of sugiany or ousttrue. This is very helpful for the development of mmd_tools. 😄

**Comment by powroupi** [comment]
@Hogarth-MMD  Thank you, I'm glad that my poor english could help. :smile: So, would it be better if I make following changes:
 1. Each import/export function (model/motion/pose) have a scale option, default 1.0, always be a multiplying operation.
 2. Remove the scale property of root object

(The gravity value will let users to try by themselves.) In my experience, the physics looks different if you import a model with different scale. :confused:

**Comment by Hogarth-MMD** [comment]
"1. import/export function (model/motion/pose) have a scale option, default 1.0, always be a multiplying operation."

Yes, I am strongly in favor of this. My script above allows this to happen and also configures the camera and grid, so that a model which has been imported with a scale of 1.0 will appear in Blender the same as it appears in MMD (in 4 different Blender screen layouts).

**Comment by Hogarth-MMD** [comment]
At the present time, I have a very low level of expertise with the MMD tools source code, Maybe later I can remedy this, but not immediately. In the meantime, the best that I can do is make standalone scripts, and then I need another person to add that to the mmd_tools source code.

So, for us to co-operate, it would be helpful if you can clarify to me your attitude (in this issue and other issues). You can tell me for example if 
1) you think that my idea is bad and it should not be added to mmd_tools.
2) or if you think my idea is okay but I must do all the work and send it to you as a pull request.
3) or if you are willing to modify my idea and my python script and add it to mmd_tools yourself.

**Comment by Hogarth-MMD** [comment]
" In my experience, the physics looks different if you import a model with different scale. "

Okay, the physics issue is important, so we need to test this.

**Comment by Hogarth-MMD** [comment]
@powroupi, compared to my knowledge of Japanese, you are an English language genius. 😄

**Comment by lordscales91** [comment]
Hey guys! It's been a long time. I know I haven't contributed to this addon in a long time but I would like to share my opinion about this issue. Basically the discussion is about scaling the model vs scaling the grid. From a technical perspective scaling the model is better because you don't rely on Blender's internals (In other words: you don't touch anything on Blender, just build model). If you don't scale the model, scaling the grid may no be enough, as powroupi said it seems that there are some problems regarding the physics. Also, we need to ensure that this "grid scaling" is kept. What happens if you split the 3D View? Will the scaling be lost?

Lastly, there is something that I don't understand

"Scaling is and should always be a multiplying operation."
@Hogarth-MMD What do you mean with this? I'm not a math expert but the division is the opposite operation to multiplication, so it should work fine. Actually, it works fine, I have used the addon with different models and the scale looks good on the exported version.

**Comment by powroupi** [comment]
Okay, I've made the changes to keep consistent with other addons, and I agree this way is better. :smile:

You could change import scale to **0.2** on importing, export scale to **5.0** on exporting, and everything should be as usual. It is not a big problem for me to get used to it. :)

**Comment by Hogarth-MMD** [comment]
Thank you @powroupi  , I was just looking at the commit which you made and I can see that this demanded more time from you than I realized. I appreciate very much your generosity in giving your time to this excellent mmd_tools add-on and this is an excellent service to the MMD community by the respected mmd_tools sensai @powroupi . (You can tell me whether or not this is the incorrect Japanese "honorific" way for me to address you. :smiley: )

**Comment by powroupi** [comment]
You're welcome. :smile:  (Actually, it's not too hard. I just need to fight my laziness. :sweat:) BTW, you can close this issue now if you don't find any further issues or bugs, thank you. :)

>You can tell me whether or not this is the incorrect Japanese "honorific" way for me to address you.

My japanese is bad as well, sorry. :cry: Do you mean "mmd_tools sensai" ?  Maybe @nagadomi can tell you. :)

**Comment by lordscales91** [comment]
@Hogarth-MMD @powroupi I've never heard about the "sensai" honorific, probably you wanted to say "sensei". It's the honorific used to refer to teachers and people with a lot of knowledge in a certain field. (Definitely powroupi has a lot of knowledge in the software development field).

By the way I feel a bit ignored here. Nobody read my previous comment? Here is another suggestion: make the default scaling a preference of the addon.

**Comment by Hogarth-MMD** [comment]
@powroupi I looked at your bug fix, thank you very much, and you have my approval to close this issue, if you want. I did not see any physics scaling issue. And you are also giving people an option to save their own import and export preferences. When a model is imported the user is only seeing the feet of the model, so ideally it would be nice if that flaw were remedied also.
If your English is bad, and your Japanese is also bad, I am curious to know what is your first language?  Previously I just assumed that your first language is Japanese.
I also see that now the armature is not hidden by default and I completely agree that this is correct.

**Comment by powroupi** [comment]
@lordscales91 
>I've never heard about the "sensai" honorific, probably you wanted to say "sensei"....

Thank you for the explanation. Cool, is that what you mean, @Hogarth-MMD ? ...but I'm not that good actually, so you don't have to address me in that way. :laughing: 

>Here is another suggestion: make the default scaling a preference of the addon.

I don't think we need that addon preference, I guess the import/export options will save to your .blend. :)

@Hogarth-MMD 
>When a model is imported the user is only seeing the feet of the model, so ideally it would be nice if that flaw were remedied also.

You could hit "Home" button on keyboard (to view all) after import a model. :smile:
