### ISSUE TITLE
Advanced Morph Types

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#64]
Presumably at some point in time, mmd_tools will have full support for advanced morph types (material morphs, UV morphs, bone pose morphs, group morphs). Drool. :-) So I thought that I would share what I have figured out about this subject so far. This data for advanced morph types is stored on an 'EMPTY' object which is parent of a character's mesh object and armature object. I loaded a model into Blender with mmd_tools which has all of these types of morphs, and here is some data that I found via the Blender scripting console:
```python
>>> bpy.context.active_object.mmd_root.uv_morphs[0]['data'][0]['offset'].to_list()
[-0.08337914943695068, -0.11126798391342163, 0.0, 0.0]

>>> bpy.context.active_object.mmd_root.uv_morphs[0]['data'][0]['index']
4376

>>> bpy.context.active_object.mmd_root.material_morphs[0]['data'][0].to_dict()
{'diffuse_color': [0.0, 0.0, 0.0, 0.0], 'sphere_texture_factor': [0.0, 0.0, 0.0, 20.0], 
'specular_color': [0.0, 0.0, 0.0], 'offset_type': 1, 'related_mesh': 'ByakurenWith Straight Hair', 
'shininess': 0.0, 'material_id': 0, 'toon_texture_factor': [0.0, 0.0, 0.0, 0.0], 
'ambient_color': [0.0, 0.0, 0.0], 'texture_factor': [0.0, 0.0, 0.0, 0.0], 
'edge_weight': 0.0, 'edge_color': [0.0, 0.0, 0.0, 0.0]}


>>> bpy.context.active_object.mmd_root.bone_morphs[0].data[0].bone
'胸調整.L'

>>> bpy.context.active_object.mmd_root.bone_morphs[0].data[0].location
Vector((0.0, 0.0, 0.0))

>>> bpy.context.active_object.mmd_root.bone_morphs[0].data[0].rotation
Quaternion((0.9940563440322876, 0.1088668555021286, -2.4513144335561177e-13, 9.518605459390983e-09))

>>> bpy.context.active_object.mmd_root.group_morphs[0].data[0].keys()
['name', 'morph_type', 'factor']
```

**Comment by Hogarth-MMD** [comment]
I am assuming that drivers and custom properties (with slider controls) would be needed to implement advanced morph types in Blender. But in Blender, when a property is controlled by a driver and a custom property slider control, that property cannot be edited, or keyframe animated. The driver kind of takes over control in a very possessive and exclusive way. So it seems like that would be a problem with implementing advanced morph types in Blender.

**Comment by Hogarth-MMD** [comment]
```python
>>> bpy.context.active_object.mmd_root.uv_morphs[0]['data'][0]['index']
4376
```
I posted this mmd_tools example data above. Please clarify to me what kind of 'index' this is.
Is this a vertex index OR a vertex index of faces?
vertex index: for example an object has 100 vertices, so it has 100 vertex indexes.
vertex index of faces: for example an object has 100 triangle faces, so it has 300 vertex indexes of faces.

**Comment by powroupi** [comment]
@Hogarth-MMD It is vertex index. (see [properties/morph.py](https://github.com/powroupi/blender_mmd_tools/blob/fc617e6c555cae5842b9b6a216bef8884b131318/mmd_tools/properties/morph.py#L329-L334)) :smiley:

**Comment by Hogarth-MMD** [comment]
Thanks! Blender uses vertexes of faces for UVs.

**Comment by powroupi** [comment]
Okay, I'd like to close it for now, you can reopen it if you have new related questions. :)
