### ISSUE TITLE
UV morph indices lost on separate by materials

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#65]
Test model for recreation at http://www.mediafire.com/file/qo3y8rakchp1bb8/UVmorphIssueDemo.pmx

To recreate: verify model has working UV morphs ("red" and "yellow", morphs 59 and 60); import to Blender; separate by materials; export.  All actions accessed via buttons on toolshelf.  Check exported .pmx; while the UV morphs remain, all indices are gone, so the UV morphs no longer do anything.

Note that this model is unusual in that it has UV morphs affecting vertices from multiple materials.  Works in MMD, but PMXE doesn't like you doing that on UV morph creation, just something that happened along the way, basically.

Current workaround should be to preserve vertex order and save/load UV morphs from .csv in PMXE,.

Could this be related to cleaning shapekeys on separation?  Don't see a dialogue for that anymore, so wasn't sure how to test further.

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile:

Currently the UV morph indices are not synchronized yet, so adding/merging/removing vertices to your mesh will potentially lost UV morphs, and so does separate mesh.:cry:

A workaround in blender is that you can manually store UV morph to mesh object's UVn one by one via previewing UV morph (`With Animation` disabled) and rename `__uv.*` to other name (change prefix `__uv.`), and add prefix `__uv.`, Edit/Apply back to corresponding UV morph after editing your mesh. But there is a limitation of maximum 8 UV maps (7 additional UV maps). :cry: A better workaround would just like you said. :)

>Could this be related to cleaning shapekeys on separation?

No, it is not related. :) Clean shapekeys is default now. If you don't want to clean shapekeys, after selecting a mesh object, go to blender python console window and type the following command:
```python
>>> bpy.ops.mmd_tools.separate_by_materials(clean_shape_keys=False)
```
And if you want to clean shapekeys, after selecting mesh object(s), hit keyboard space bar to search `Clean Shape Keys`.

**Comment by powroupi** [comment]
This issue should be solved in latest `mmd_tools`. (see #131) :yum:
