### ISSUE TITLE
importing .x files into Blender

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#66]
The bad news is that Blender has no .x importer, but the good news is that @powroupi is going to program one for us next week? Right? Yay, @powroupi !

Okay, just joking around a little. :smile: In fact Blender does have a .x importer, but it is not good enough to come included with Blender, so you need to download it from here:

https://github.com/littleneo/directX_blender
https://github.com/littleneo/directX_blender/archive/master.zip
https://github.com/littleneo/directX_blender/issues

When I tried to import a .x file, I got this error message in the Blender system console:
```
    img = bel.image.new(path+'/'+filename)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_directx_bel\bel\image.py", line 44, in new
    img.use_premultiply = premul
AttributeError: 'Image' object has no attribute 'use_premultiply'
```
Apparently .use_premultiply is not a possible image attribute in Blender 2.78, but I found a quick and simple bug fix for this issue. I just commented out these 4 lines in image.py and then this .x importer worked fine for me :smile: :

	Line 44:     # img.use_premultiply = premul
	Line 163:    # if type(img) != type(None) :
	Line 164:         # img.use_premultiply = True
	Line 238:             # img.use_premultiply = True

**Comment by powroupi** [comment]
Well, I won't do that from scratch, so I may fork that repository and make some improvements if I'm interested in.  :fearful:

 :exclamation: `image.use_premultiply=True` has been changed to
```python
image.alpha_mode='PREMUL' # default is 'STRAIGHT'
```
