### ISSUE TITLE
Question about the version of Blender

### ISSUE THREAD

**Issue by Rebrite** [powroupi/blender_mmd_tools#67]
Hi, thank you so much for sharing this amazing 'MMD_Tools'!
Well, I have donwloaded the latest files of 'MMD_Tools', however I have no idea about the version of Blender that I should install.
Looking forward to your reply! THX!

**Comment by nathanvasil** [comment]
I'm using it with Blender 2.78c currently, which I understand to be the most recent.  If you're just getting started with Blender, there's no reason to avoid the newest version.

**Comment by Rebrite** [comment]
Thank you Nathanvasil!
I have just installed the Blender 2.78c, and followed those steps. However, here comes a issue, I imported a model into Blender, it's work fine, but the scale of the imported model is very very huge. 
So, is it right or something that I ignored?
@nathanvasil

**Comment by nathanvasil** [comment]
Nope, you're fine.  It will export the correct size.  Easy enough to rescale it if you want to make it work with a different scale for other objects in Blender.

**Comment by Rebrite** [comment]
Okay. I got it. Thank you so much~ @nathanvasil

**Comment by Rebrite** [comment]
@nathanvasil Well, I can rescale the model size, but I can not rescale the size of Joints and Bones and Rigidbodies. 
Can you tell me How to do with this? THX!

**Comment by powroupi** [comment]
Hello, @SakuraKurumi , There are several ways to scale the model: :smile: 
1. Change the scale value of import option from **1.0** to **0.2** (for example). [recommend]
2. Scale the root object, change object's scale values or unlock scales of transform locks.

**Comment by Rebrite** [comment]
Thanks for your advice. @powroupi
If I import 2 different size of models, and I wanna take some part from one of them, should I delete the Joints & Bones & Rigidbodies of the taken one?

**Comment by Rebrite** [comment]
And How to change the scale of Model & Joints & Bones & Rigidbodies after imported into the Blender?

**Comment by powroupi** [comment]
If you want to scale a object, simply RMB select a object, hot key [s] to scale, LMB to confirm (RMB to cancel), or just modify object's scale values manually. If you want to scale whole structure down, you might try changing pivot point to 3D cursor, then scale the objects. :smile: Some references: [Basic Transformations](https://docs.blender.org/manual/en/dev/editors/3dview/object/editing/transform/basics.html#scale), [Pivot Point](https://docs.blender.org/manual/en/dev/editors/3dview/object/editing/transform/control/pivot_point/index.html), [3D Cursor](https://docs.blender.org/manual/en/dev/editors/3dview/3d_cursor.html)

If you want to take some part of a MMD model, you might remove those unwanted Joints & Bones & Rigidbodies of the taken one, it depends on your requirements. :)

**Comment by Rebrite** [comment]
(๑>؂<๑）Okay, understood! Thanks for your kindly help!
