### ISSUE TITLE
translation of colors japanese to english

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#70]
Big Japanese Color Translation List
https://sta.sh/0oc40p05k4s

I made a big Japanese to English translation dictionary for the names of colors for mmd_tools, both .csv and .py formats. You can download it from the link above. I tried to upload these 2 files to Github, but so far that is a major time-wasting headache and I haven't succeeded with it. But uploading them to my deviantart sta.sh took about 2 seconds, so there they are. I hope that @powroupi will add these translations to mmd_tools. If everything goes according to plan, I hope that I will be uploading more translations some time soon.

**Comment by powroupi** [comment]
I'm not sure which way is better. Maybe it is better to add a link to wiki page instead of adding a big dictionary to mmd_tools. @ptrthomas's spreadsheet link can be added to wiki page as well, so people can find it more easily :smile:

**Comment by Hogarth-MMD** [comment]
The mmd_tools translation dictionary is now going through a period of rapid growth. When this dictionary has reached a nice, large size, presumably this growth will decelerate. Maybe there will be no new additions to the dictionary for 2 months. At that time, you can either announce that the dictionary is final, or you can accept pull requests for small additions to this dictionary. mmd_tools should definitely have a good, large dictionary because this is very convenient and beneficial for the users of mmd_tools.

**Comment by Hogarth-MMD** [comment]
This issue can be closed now.
