### ISSUE TITLE
Normalized weights exporting unnormalized

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#71]
Here's a file containing a .blend and .pmx.  Sorry, those .blends are getting pretty big.  http://www.mediafire.com/file/16z7hbxdm00wl1d/unnormal.zip

This blend is a pmx model with the vertex order and edge weight vertex groups removed.  I have cleaned all vertex groups (keeping at least a single group), limited the total groups per vertex to 4 groups, and normalized all (with no locked groups).

However, when I export, the weights are unnormalized.  Check the .pmx included.  At least, that's what PMXE valdiation is telling me.

I would expect that part of this issue may have to do with BDEF4, or with BDEF4 vertices with significant weights to only 3 bones.  I have a lot of BDEF4 on my model.

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: 

I think the weights are normalized on export, it might be precision issue, I'll check it again anyway. :)

**Comment by powroupi** [comment]
Okay, it is fixed. The initial bone index needs to be 0 instead of -1 to pass the validation. Thank you. :smile:

**Comment by nathanvasil** [comment]
Thanks, appreciate it.  Was seeing some weird weights creep in after normalizing in PMXE (and need to normalize to use PMXE to export transformed/posed models).
