### ISSUE TITLE
Exported MMD-Blender models includes debug meshes messing the model

### ISSUE THREAD

**Issue by hydexon** [powroupi/blender_mmd_tools#72]
When you're exporting (in my case, an FBX) to Unreal Engine 4 from Blender MMD using the standard fbx exporters, the mmd into blender looks fine, but under in Unreal looks like this:
![image](https://user-images.githubusercontent.com/3113186/29480876-01628a98-8439-11e7-93bf-144f6dd6b98b.png)
as i thought they are debug meshes to show the joints and bodies of the MMD model.actually i don't know if the PMX editor or the Blender MMD tools plugins are responsible.

There's some way to remove it when you exporting to FBX or another format?, i've looked though Blender and View3D (An Win10 mesh viewer) doesn't show them.

**Comment by powroupi** [comment]
Thank you for reporting this isuue. :smile: 

You can toggle visibility of rigid bodies & joints in blender. There is a `MMD Display` panel in 3d view's properties region (go to 3d view menu/header, [View]->[Propoerties]).

If you don't want those physics objects, unselect `Physics` of import option (there are `Mesh`, `Armature`, `Physics`, `Display`, `Morphs`) when importing a model.

You can also delete them in blender Outliner window. In outliner, RMB click on `joints` / `rigidbodies` under MMD Root object (shows [Outliner Object Operation] menu), hit **[Delete Hierarchy]**.

**Comment by powroupi** [comment]
Okay, I'd like to close it for now, you can reopen it if you have new related questions. :)
