### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#74]
Hey, this isn't really an issue!  Isn't that cool?

I wanted to show you all something.  Check out https://www.youtube.com/watch?v=zJeQVgksucA .  This person discovered MMD about a month ago.  Today they're learning modelling and exporting models and textures from Blender.  The quality of their work isn't what's amazing.  Not yet.  What's amazing is the pace with which they're advancing.

When I started trying to figure out MMD and Blender-- using the sugiany branch-- it was enormously frustrating.  In addition to the frustration of trying to learn MMD, Blender, and 3D modelling in general (as well as a few other things), I had to figure out how to get models out of MMD Tools.  If you remember, this wasn't a pleasant process.  It required both pre- and post-prep and involved a lot of trial and error just figuring out what would work and what wouldn't.  I can't imagine trying anything fancy with Blender in that environment.

Today, MMD Tools is very nearly painless.  Painless enough that people can follow a tutorial and start learning how to make 3D models for MMD (or how to use MMD models in Blender).  In my short time with MMD, I have seen the number of people using Blender explode.  The hard work of everyone here, but especially of powroupi, is the reason for that.

Most of those people are going to make a selfie that's a little cooler than they could make with PMXE.  That's pretty cool, all on its own, that you made that possible.  But some of those people are going to start with MMD and Blender and go on to become experts in animation, modelling, rigging, programming.  That's really cool.  Those people are going to be making cool stuff for us to look at for the rest of our lives.  Stuff for the rest of the world to look at, too.

I know that it couldn't have been easy getting all this done.  I know that maintaining it isn't easy.  Just wanted to let you all know how appreciated it is.  It's easy to forget that there are a lot of people out there getting a lot of use out of MMD Tools.  Thanks.

**Comment by Hogarth-MMD** [comment]
The wonderful thing about MMD is that it sends to people the freedom to create their own entertainment, and to be part of a community, instead just being a mindless zombie in front of a television. This is a beautiful gift of Japanese people to the world. 😄

**Comment by powroupi** [comment]
Yea, it's cool and great. :smile: Thanks for all developers of making Blender and MMD stuff tools, and thanks for all people who found issues. :kissing_heart:

**Comment by ptrthomas** [comment]
big thanks to @powroupi and all other developers ! as always, here is my shameless plug: https://www.youtube.com/watch?v=K4-LqJFy7JU - powered by blender_mmd_tools

What I personally find amazing is that I do not use windows for my workflow at all. Everything is done on an Apple Mac, something that the original developers of MMD would have never imagined. 

OSS is awesome.
