### ISSUE TITLE
mmd_tools translation dictionary 1.0

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#76]
My mmd_tools translation dictionary now has its own Github repository here:
https://github.com/Hogarth-MMD/mmd_tools_translation

(863 tokens translated)

Direct download:
https://github.com/Hogarth-MMD/mmd_tools_translation/archive/master.zip

Thanks to everyone who helped with this project!

**Comment by powroupi** [comment]
I found a few flaws (sorry, i don't know japanese): :smiley: 

- suggest remove ["0"](https://github.com/Hogarth-MMD/mmd_tools_translation/blob/d8762221b013fd304eb122f6f49f3769d3e36d5d/translations.csv#L598)

- suggest ["＋" "－"](https://github.com/Hogarth-MMD/mmd_tools_translation/blob/d8762221b013fd304eb122f6f49f3769d3e36d5d/translations.csv#L797-L798) map to `"+" "-"`

**Comment by Hogarth-MMD** [comment]
:smile: :smile:

**Comment by powroupi** [comment]
You might check [translations.csv#L597](https://github.com/Hogarth-MMD/mmd_tools_translation/blob/910672b07e71bb1d5d41beff3ddcf1a85d8524a6/translations.csv#L597), [translations.csv#L796-L797](https://github.com/Hogarth-MMD/mmd_tools_translation/blob/910672b07e71bb1d5d41beff3ddcf1a85d8524a6/translations.csv#L796-L797), there might be some mistakes, thank you. :smile:

**Comment by Hogarth-MMD** [comment]
Thank you @powroupi . I have corrected those 3 errors now.

**Comment by Hogarth-MMD** [comment]
@powroupi wrote:

" Hello, I've made some changes for custom csv dictionaries, you might try it. :smile:

@Hogarth-MMD, you may need to update your tutorial, major changes:

Change Translate button label to Translation.
Now file name does not have to be translations.csv, and can be located to custom folder. You can change custom folder via mmd_tools addon preferences.
The dropdown list will list all *.csv files in the custom folder (sub folders are not included) and *.csv blender texts. "

**Comment by Hogarth-MMD** [comment]
Hello @powroupi ! I may not have time to update my instructions every time you make a change to mmd_tools translation. Please be sure that whatever changes you make are backwards compatible with my instructions to avoid being inconsiderate of other people.
All of the changes which you made are backwards compatible with my instructions, are they not? Except for changing the button label to Translation?

**Comment by powroupi** [comment]
Okay, don't worry, the only difference is the dictionary dropdown list which use internal [jp_to_en_tuples](https://github.com/powroupi/blender_mmd_tools/blob/4ca8888f4f7f6542af5dfd3aa1fa727e0e27c366/mmd_tools/translations.py#L27) by default now, so users will need to change it to `translations.csv` or other csv files/texts to use custom csv dictionary. :smile:

**Comment by Hogarth-MMD** [comment]
@powroupi , My translation is dictionary is definitely not finished yet. Later I want to add more vocabulary to it. But I have temporarily paused working on it. I think that you should add it to mmd_tools or you should add a link to it in the mmd_tools readme file. My reason for this is just to be considerate of other people. Someone might decide to make his own translation dictionary because he doesn't know that someone else has already made a translation dictionary. He will waste a large amount of time and then he will be a very unhappy person when he learns that he has wasted time working on something which has already been done by another person.

**Comment by powroupi** [comment]
@Hogarth-MMD, yeah, the links are already added to [wiki page](https://github.com/powroupi/blender_mmd_tools/wiki/Translations). (not many people know that though ^^|||) :smile:

**Comment by Hogarth-MMD** [comment]
半漁人
Can someone please tell me the correct translation for this? This is the name of Pluto's lizard-man, frog-man, turtle-man character. The online translators are translating this as Half Fisherman, which I don't think is the correct translation.

**Comment by nathanvasil** [comment]
>半漁人

It's a name of a mythical creature.  It's really more like "half-fish half-man", from what I can see, but you might consider "merman" instead.

See https://translate.google.com/translate?hl=en&sl=ja&u=https://ja.wikipedia.org/wiki/%25E5%258D%258A%25E9%25AD%259A%25E4%25BA%25BA&prev=search

**Comment by Hogarth-MMD** [comment]
Thanks @nathanvasil ! That helps. I wonder if he is a video game character?

**Comment by nathanvasil** [comment]
Older than video games, but I wouldn't be surprised if he's featured in video games as well.  Like, say, a minotaur.  Rooted in old mythology, popular thing to add to modern entertainment.

**Comment by Hogarth-MMD** [comment]
Touhou Project Wiki:

"A half-fish person!?
I had no idea there was anything
besides fairies living around this dead lake."

https://en.touhouwiki.net/wiki/Double_Dealing_Character/Story/Sakuya_A%27s_Scenario
:smile:

**Comment by Hogarth-MMD** [comment]
https://en.touhouwiki.net/wiki/Mermaid

https://en.wikipedia.org/wiki/Ningyo
Ningyo (人魚, "human fish", often translated as "mermaid") is a fish-like creature from Japanese folklore.

:smile:

**Comment by Hogarth-MMD** [comment]
@powroupi , I thought that you were agreeing with me that the translation dictionary link should be added into the readme file, but this link has not been added into the readme file. This is inconvenient and inconsiderate for other people.

**Comment by powroupi** [comment]
@Hogarth-MMD Okay, I will add it into the readme file, I have to find a place to add. :blush:

**Comment by powroupi** [comment]
@Hogarth-MMD Feel free to edit [wiki/Translations](https://github.com/powroupi/blender_mmd_tools/wiki/Translations) page if you have any updates. I'd like to close this issue. :)
