### ISSUE TITLE
Is vertex order sorting working?

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#79]
I've had a few issues lately where I've wanted to use properly sorted vertices.  One is regarding the creation of vertex morphs, the other, saving and copying a UV morph from .csv so I didn't have to recreate it.  Both have given me issues that suggest that vertex order isn't working.

I'm importing with either Clean enabled or disabled (doesn't mater), not creating any new vertices, not destroying the "vertex order" vertex group, and exporting with "custom" vertex sorting.

With the vertex morph issues, I was trying to load a Blender edited version of the model as a vertex morph in PMXE, which made the model explode, as if the wrong vertices were being affected.  With the UV morph issues, I can verify that the UV morph was loaded properly, although it doesn't appear to be affecting any vertices it used to affect....  (There are a lot of materials in this model, some of which are transparent, some of which don't use textures, so I can't easily see what's being affected.)

Is there another explanation for this?  Is vertex order functional?  Am I doing something wrong?  I can provide files for reproducing it if you want.

**Comment by powroupi** [comment]
Yes, vertex order is working, but sometimes it may not work as expected. Only if the vertex count of exported pmx equals to the vertex count of original pmx, the csv of original pmx can be applied to exported pmx. And yes, I'd need the sample files for reproducing it. :smile: 

When exporting a model (vertices: [0, 1, 2, 3] faces:[ (0,1,2), (1,2,3) ]), sometimes some vertices will be ripped (depends on custom normal and uv), the exported pmx may looks like (vertices: [0, 1, 2a, 2b, 3] faces:[ (0,1,2a), (1,2b,3) ]) if the vertex 2 has different normal or uv on these 2 faces so that the csv of original model would not work on exported pmx.

Since the vertex indices of UV morphs are not synchronized in blender, I'd recommend creating UV morphs at last step or when the vertex count does not be changed. :smile: 

[EDIT] addUVn and modifiers also affect vertex count of exported pmx. :)

**Comment by nathanvasil** [comment]
Okay, I've put together a few files to reproduce.  http://www.mediafire.com/file/k2vo7wah7p2ravl/vertexorderstudy.zip has original.pmx, a blend file imported with clean disabled and a simple transformation applied, importedmodified.pmx which is the blend exported with custom vertex sorting, with the UV morph then loaded from CSV, and then originalNewVMorph.pmx, which is the original file, with the modified export loaded as a vertex morph via PMXE.

Processing of the blend file: placed skeleton into rest position; disabled autosmooth; turned on proportional editing at default radius and translated the tip of her nose -2 in Blender's Y axis.

UV morphs didn't get destroyed and are getting mapped properly (ie, the vertices are in the right order for that material) so I'm not including anything regarding that.  The vertex morph, however, is crazy.  It looks like a vertex order issue, but again, I'm not sure.  (Some of my earlier issues may have been due to forgetting to turn off autosmooth, which then generated additional vertices in the export.)

**Comment by powroupi** [comment]
It is weird, vertex order is working :confused: , I guess you forgot to export with **Custom** vertex sorting, the vertex order of `importedmodified.pmx` is not correct.

The `Join as Shapes` menu function of Shape Keys panel is similar to PMXE, you can also test it only in blender.

My test is (only in blender):
1. Open `importedmodified.blend`, export to `modified.pmx` with **Custom** vertex sorting
2. Open new empty scene, Import `original.pmx`, `modified.pmx`, `importedmodified.pmx` (import `Mesh` parts only)
3. Move root objects to separate these 3 models, then select objects `Importedmodified_mesh`, `Modified_mesh`, finally `Original_mesh`
4. `Join as Shapes` (menu function of Shape Keys panel, or search from spacebar in 3d view)
5. Two shape keys (`Importedmodified_mesh` and `Modified_mesh`) will be added to `Original_mesh`. `Modified_mesh` is correct, but `Importedmodified_mesh` is incorrect.

Ps. you can also do some crazy changes at step 1, the vertex order should work as well. :)

**Comment by nathanvasil** [comment]
Oh, now I feel dumb :)  You're right, I must have screwed that up.  Sorry for wasting your time.  (First I was screwing up because of autosmooth, then once I realized that, I didn't double check exporting with custom sort.)

Thanks for info about join as shapes.  One of the reasons I wanted to do this was to use an existing shapekey as the start of a new shapekey, without losing the old shapekey, and I can see how I can do that with join as shapes.

**Comment by powroupi** [comment]
You're welcome. :smile: By the way, you can add/edit shapekey in blender, see [Relative Shape Keys](https://docs.blender.org/manual/en/dev/animation/shape_keys/workflow.html#relative-shape-keys). And `Join as Shapes` and `New Shape From Mix` in [Shape Keys Panel](https://docs.blender.org/manual/en/dev/animation/shape_keys/shape_keys_panel.html#shape-keys-panel) specials are very useful. :smile:
