### ISSUE TITLE
[QUESTION] What are shadow and dummy bones?

### ISSUE THREAD

**Issue by lordscales91** [powroupi/blender_mmd_tools#8]
Hi, remember the person that I mentioned in #6 ? He is creating his first MMD model using this addon and is having trouble figuring out how to create a proper IK constraint to be exported. Sneaking through the code I found out that there are some special bones, those bones are not just hidden but moved to a different layer. Smart play ha ha! But, why do you hide those bones so much? What are they used for?

We really need to create an updated documentation, it will be helpful for both developers and users. And by the way, my friend is learning Japanese so he may help us to translate the updated documentation from English

**Comment by powroupi** [comment]
The way to create IK constraint is basically the same with blender, but you need to add a child bone to your IK bone if it does not have any child bone, that's it!
- For example: If you have a chain bone `root->b1->b2`, and you add a control bone `b_ik`, and you want to add a IK constraint to bone `b2` and assign subtarget to bone `b_ik`. In this case, you need to add a bone `b3` which is parented to bone `b2` (so the chain looks like `root->b1->b2->b3`) if you want to export the armature without errors.

Those special bones (mmd shadow bone) are generally ignored, and transparent to user. (it could be improved if we have any better idea)
- The bones created by `mmd_tools.core.bone.FnBone.apply_additional_transformation` are for fixing bone roll/direction issue, which may not be necessary if the source bone and the target bone are well aligned.
- The bones created by `mmd_tools.core.model.Model.create_ik_constraint` are for fixing bone position error as the function's comments said.

Hope this helps. :smile:

**Comment by lordscales91** [comment]
So. Creating an IK constraint doesn't have nothing special except for the child bone. But my friend used an imported armature from another model so this shouldn't be the case. In fact, the model exports fine, but the legs don't flex properly it's like they broke. Probably it's a problem of vertex weights or topology.

Thanks for your information, I will try to make some tests on my own with a simple model. I will also make some unit tests for the addon.
