### ISSUE TITLE
mmd_tools helper add-on

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#84]
From top to bottom:

MMD View button - setup of camera, grid and background color

Convert MMD Camera to Blender Camera button

MMD background Color Picker - Selects a color for the world background. A background text color is automatically chosen to contrast with the background color.

MMD Lamp button - setup of Lamp (first lamp in the scene is used)

MMD Create Toon Material Nodes button - Adds node editor material nodes to the active mesh object for the rendering of Toon Textures in Blender

Toon modifier blend type dropdown menu
Toon modifier color picker
Modify Toon button - modifies the color of shadows of the active object

English or Japanese names of bone morph slider controls dropdown menu
MMD create bone morph slider controls button - (on the active armature object), the slider controls will be found under Custom Properties under the Armature Data tab of the Properties Window
Disable all morph slider controls button - disables all drivers of the active object
Enable all morph slider controls button - enable all drivers of the active object
Reset all morph slider controls to zero button - for the active object

**Comment by Hogarth-MMD** [comment]
mmd_tools helper add-on download link:
https://sta.sh/01n3b5matlih

Praise and constructive criticism are both welcome.

**Comment by Hogarth-MMD** [comment]
I just fixed a bug and  the bug fixed version can be downloaded from this link:
https://sta.sh/01yd1kau9eft

When a material has no diffuse texture, the material was being rendered with dark, ugly shadows, but now that bug is corrected.

**Comment by powroupi** [comment]
Close this since there is a newer version (see #128 ). :smile:
