### ISSUE TITLE
1 MMD model = 3 Blender objects

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#85]
This is an issue which happens if I am writing Python code:
The root/empty object is the active object and I want my script to find the mesh object or the armature object.
The mesh object is the active object and I want my script to find the root object or the armature object.
The armature object is the active object and I want my script to find the mesh object or the root object.

What is the easiest and best way to do that?

**Comment by powroupi** [comment]
Here is the sample: :smile: 
```python
import bpy
from mmd_tools.core.model import Model
root = Model.findRoot(bpy.context.active_object)
if root is None:
    print('Please select a MMD model')
else:
    rig = Model(root)
    armature = rig.armature()
    meshes = list(rig.meshes())
    print(armature, meshes)
```

**Comment by Hogarth-MMD** [comment]
``` python
import bpy

def findRoot(obj):
	if obj:
		if obj.mmd_type == 'ROOT':
			return obj
		return findRoot(obj.parent)
	return None

def armature(root):
	for i in filter(lambda x: x.type == 'ARMATURE', root.children):
		arm = i
		break
	return arm

def __allObjects(obj):
	r = []
	for i in obj.children:
		r.append(i)
		r += __allObjects(i)
	return r

def allObjects(obj, root):
	if obj is None:
		obj = root
	return [obj] + __allObjects(obj)

def meshes(root):
	arm = armature(root)
	if arm is None:
		return []
	return filter(lambda x: x.type == 'MESH' and x.mmd_type == 'NONE', allObjects(arm, root))


root = findRoot(bpy.context.active_object)
if root is None:
	print('Please select an MMD model')
else:
	armature = armature(root)
	meshes_list = list(meshes(root))
	print("root = ", root)
	print('armature = ', armature)
	print('meshes_list = ', meshes_list)
	print('\n')

# Traceback (most recent call last):
  # File "\model.py", line 41, in <module>
  # File "\model.py", line 29, in meshes
# TypeError: 'Object' object is not callable
# Error: Python script fail, look in the console for now...
```

**Comment by Hogarth-MMD** [comment]
Hello @powroupi ! Above is the python code for my own model.py file. I thought that I could do this, no problem, but apparently I am making some kind of idiot error. Will you please be so kind as to help me correct this idiot error?

**Comment by Hogarth-MMD** [comment]
Okay, armature is the name of a variable, and armature is also the name of a function, so this seems to be just a simple idiot error, easily corrected.

**Comment by Hogarth-MMD** [comment]
Hello @powroupi ! Thank you for this excellent help. You  can see the result of this excellent help in the model.py file of mmd_tools helper add-on 2.0. I apologize for not thanking you for this excellent help @ much earlier. I thought that I would wait and thank you after I successfully used this in my scripts, and this took more time than I expected.
