### ISSUE TITLE
Cannot handle truncated pmx files

### ISSUE THREAD

**Issue by ghost** [powroupi/blender_mmd_tools#86]
Some pmx files are apparently truncated and missing some bytes at the end of the file, which causes the code for reading joint rotation springs to fail with `struct.error: unpack requires a string argument of length ##`

Both MMD and PMX Editor can open these files however (and PMX Editor seems to assume zeros for the end of the file)

**Comment by powroupi** [comment]
Thank you for reporting this issue, I'll try to fix it, and it would be appreciate if you can provide the pmx sample file for reproducing this issue. :smile:

**Comment by powroupi** [comment]
Okay, I have made the changes, you might test it. :)

**Comment by ghost** [comment]
Yep, this fixes the issues, thank you!
