### ISSUE TITLE
Reloading breaks mmd_tools

### ISSUE THREAD

**Issue by Darkblader24** [powroupi/blender_mmd_tools#88]
When I hit reload (F8) mmd_tools disappears from the tab list and it gives the following error:

```
Exception in module register(): 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\mmd_tools\\__init__.py'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 350, in enable
    mod.register()
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\mmd_tools\__init__.py", line 93, in register
    properties.register()
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\mmd_tools\properties\__init__.py", line 50, in register
    setattr(typ, attr, prop)
ValueError: bpy_struct "Object" registration error: mmd_joint could not register
```

**Comment by powroupi** [comment]
Thank you for reporting this issue, could you try [this fork](https://github.com/SAM-tak/blender_mmd_tools/tree/dev_test) by @SAM-tak which may solve this issue. (it is in PR #87) :smile: 

I don't have this issue, so I'm not sure how this happens. I always restart Blender instead of reloading (F8) mmd_tools. Also there is no error when I hit reload (F8). :)

**Comment by Darkblader24** [comment]
Hey, the issue is fixed in that fork, thanks! I'm using an unmodified version of your fork of mmd_tools and everyone I know had the same reload issue.

**Comment by powroupi** [comment]
Okay, I can confirm this issue on blender 2.79 (blender-2.79-windows64). There seems no error on previous blender versions (tested blender-2.78c-windows64 & blender-2.76b-windows64). Not sure whether blender will fix it or not, at least we know how to fix it, thanks @SAM-tak. :sweat_smile:

**Comment by Darkblader24** [comment]
Oh, that's interesting. Will you accept his pull request or should I use his fork until Blender fixes that?

**Comment by powroupi** [comment]
Well, I prefer to wait for Blender's next release. I'll merge his commits if Blender's next release still has this issue. :smile: 

Actually mmd_tools currently not fully support for reloading (F8) even if merge his commits which only prevents this registration error. :)

**Comment by Darkblader24** [comment]
It's expected in 2018 so that could take a while. But that's fine by me, so thank you for your quick answers :)

**Comment by powroupi** [comment]
Okay, I think this registration error is fixed now in my `dev_test` branch, you might test it. You can close this issue if it works fine in your environment. Thank you. :smile:

**Comment by Darkblader24** [comment]
It works, thanks!
