### ISSUE TITLE
Not showing

### ISSUE THREAD

**Issue by KittyMOD-Support** [powroupi/blender_mmd_tools#91]
The recent version of mmd_tools is no showing up in blender add-ons. How do I fix this issue?

**Comment by powroupi** [comment]
To install `mmd_tools` to Blender:

1. Extract the zip file you downloaded, copy the **mmd_tools** folder (not blender_mmd_tools-dev_test or something else) to [Blender folder][Blender version]\scripts\addons, (as a result, blender-2.79-windows64\2.79\scripts\addons\mmd_tools\ for example).
2. Enable `mmd_tools` in Blender from the Add-ons tab of the User Preferences dialog, `mmd_tools` should be in `Categories` "Object". If you are using search box, make sure `Supported Level` "Community" and `Categories` "All" are selected, you can also try [Refresh] button.

If you want to use [Install from File] button to install `mmd_tools`:

- Extract the zip file you downloaded, zip the **mmd_tools** folder, then install `mmd_tools.zip` you created using [Install from File] button. This way `mmd_tools` will be installed to Blender's user config folder of your system which is not inside your Blender.exe folder, so it is not easy to find.

Either way should work fine I think, but first method (copy `mmd_tools` folder) is recommended. :sunglasses:

**Comment by KittyMOD-Support** [comment]
I actually realized what I was doing wrong I was putting the whole folder in including the readme license and changelog. Thanks for the help though!

**Comment by powroupi** [comment]
Good to hear that. :smile: Actually, it is not too hard to install a addon, and you can just delete `mmd_tools` folder to remove the addon. :)
