### ISSUE TITLE
Not showing up in Addons

### ISSUE THREAD

**Issue by s7even7** [powroupi/blender_mmd_tools#92]
I've tried everything from the other user that posted this issue, I've tried installing it as file from in blender and I've tried extracting it and copying it to the addon folder. Neither of these make the addon show up in the addon tab.

What am I doing wrong here? Is there a particular version of blender this will only work on? I'm currently on 2.79

**Comment by powroupi** [comment]
Did you follow the guide in [isssue 91](https://github.com/powroupi/blender_mmd_tools/issues/91#issuecomment-354595292) to install `mmd_tools`? If you are using addon search box, make sure `Supported Level` "Community" and `Categories` "All" are selected, you can also try [Refresh] button.

`mmd_tools` should work on Blender 2.71 or newer versions.

If it still don't work, please post a screenshot of your blender addon folder `2.79\scripts\addons\mmd_tools\` and your `mmd` search result of Add-ons tab of Blender User Preferences dialog. Thank you. :)

**Comment by s7even7** [comment]
Ok so after a couple hours of scratching my head I rebooted my PC and now it shows up in Blender. Not sure why I had to reboot after placing the mmd folder into the addon folder but hey its working now!

**Comment by Hogarth-MMD** [comment]
The Blender manual page about installing an add-on:
https://docs.blender.org/manual/en/dev/preferences/addons.html
