### ISSUE TITLE
About physical operations

### ISSUE THREAD

**Issue by Mainlst** [powroupi/blender_mmd_tools#95]
MMD model's  Physical operations can't function well.
It can be functioned,But don't moved enough.It went through.
What should I do?

environment 
windows10 64bit  blender 2.79
mmd_tools 0.45 0.6.0
by Japanese  person

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: I'm not sure if I understand your issue, you may attach some screenshots to show your issues.

You can try to adjust physics settings. Under `Properties`->`Scene` tab, there are `Gravity`, `Rigid Body World`, `Rigid Body Cache` panels:
- Change [Gravity](https://docs.blender.org/manual/en/dev/physics/gravity.html) from `-9.81` to `-98.1`, or import a MMD model with scale `0.1`.
- Increase the numbers of `Steps Per Second` and `Solver Iterations` in [Rigid Body World](https://docs.blender.org/manual/en/dev/physics/rigid_body/world.html) panel.
- Bake physics simulation in [Rigid Body Cache](https://docs.blender.org/manual/en/dev/physics/rigid_body/world.html#rigid-body-cache) panel. Change `Start/End` as needed.

Also, make sure `Collision Group Mask` of MMD rigidbody objects in `MMD Rigid Body` panel (under `Properties`->`Object`) are configured as desired.

**Comment by Mainlst** [comment]
This issue was solved.It was fps's issue.I increase fps,through dissappreared.(>_<) Thanke you so much.
But I had other issues.I MMD model scale lower,MMD model's motion broke.(center born?)
And ecent version's first model size is four times bigger than past one.

![11](https://user-images.githubusercontent.com/35127783/34615254-99d42da2-f277-11e7-88d7-aaaeefc4e5df.png)

**Comment by powroupi** [comment]
>MMD model scale lower,MMD model's motion broke

Okay, it is a simple issue. When importing a VMD to a MMD model, you need to set VMD scale the same as imported MMD model. For example, import a MMD model with scale 0.2, then import a VMD with scale 0.2, etc. :smile: 

>And ecent version's first model size is four times bigger than past one.

Old version of `mmd_tools` import a MMD model with scale **0.2** by default, current new version of `mmd_tools` import a MMD model with scale **1.0** by default, so change the scale as you like. :)

**Comment by Mainlst** [comment]
oh,I'm sorry^^; it was solved.but I set operator,it It will return to preset.
I want to it Held.

And I found additional issue.I push Convert Materials For Cycles at blender render,blender had downed.
When I read objects, material's colors in material mode changed pink every time.I push its button,it will be fixed.However sometimes blender will down.I couldn't find its clear conditions.There are both pattern.

And can I export camera motion?I couldn't push export button when choose camera.
![12](https://user-images.githubusercontent.com/35127783/34637781-93d36d12-f300-11e7-8681-025bc68f08c5.png)

**Comment by powroupi** [comment]
>I set operator,it It will return to preset. I want to it Held.

Do you mean import settings? You can use `+` button of `Operator Presets` to add a preset, or you can edit default values in [mmd_tools/operators/fileio.py](https://github.com/powroupi/blender_mmd_tools/blob/fe3a6334db5e8cc092fe9002cb09e98e90569424/mmd_tools/operators/fileio.py#L92) (search key word "Scaling factor"), change the line from "default=**1.0**," to "default=**0.2**,".

>I push Convert Materials For Cycles at blender render,blender had downed.

Blender crashes sometimes, see issue #56.

>material's colors in material mode changed pink every time.

Most models use shared/default toon texture of MikuMikuDance. You need to configure the addon preferences of `mmd_tools` ([File]->[User Preferences...]->[Addons]->[mmd_tools] _expand_ ->[Preferences]->`Shared Toon Texture Folder`, set to `[Your MikuMikuDance folder]\Data\`, save settings then import your MMD model).

Other pink issues is because the textures can not be found. Check the textures and configure them manually.

>can I export camera motion?

Yes, you can. Select the camera, hit `Convert` botton in [Properties]->[Object]->[MMD Camera Tools] panel. Enable `Bake Animation` if the camera has animations, then export VMD.

**Comment by Mainlst** [comment]
I can't export camera motion when I hit bake animation.
but I hit it,another camera was made.original one can't be pushed.another one can be  pushed,but its exported VMD file don't correct.camera's position is too near.motion is correct.
![13](https://user-images.githubusercontent.com/35127783/34647961-e7f5e78e-f3d3-11e7-85df-9460b49931ea.png)
![14](https://user-images.githubusercontent.com/35127783/34647966-fe961d60-f3d3-11e7-9569-da4a4c84a1c7.png)

**Comment by powroupi** [comment]
>another camera was made.original one can't be pushed.another one can be pushed

Yeah, a new MMD camera will be created and original camera will not be changed if `Bake Animation` is enabled. Next time, you can convert a camera to MMD camera before making new camera animation for MMD, this way may be easier. :smile: 

When you export camera motion, there is also a `Scale` option, change scale value to **5.0** if imported model's scale is **0.2**. The formula is `import_scale * export_scale = 1.0`.

**Comment by Mainlst** [comment]
OK.Finally I seem MMD camera has so many key frames.Have there issues?

**Comment by powroupi** [comment]
Yes, `Bake Animation` creates many key frames, so it is only used for converting an existing camera animation. You can clean some key frames in Graphic Editor, but it is not easy. :cry:

So, next time, remember to convert a camera to MMD camera before making new camera animation for MMD, and make key frames on MMD camera properties instead. (select converted camera, go to [Properties]->[Object]->[MMD Camera Toons] panel)

**Comment by Mainlst** [comment]
Thank you so very much.Recent issues are all solved!
I will make an effort to create high quality works ^^

**Comment by powroupi** [comment]
You're welcome. Have fun. :smile:
