### ISSUE TITLE
Wont appear! Please help!

### ISSUE THREAD

**Issue by Okanako** [powroupi/blender_mmd_tools#98]
nvm

**Comment by powroupi** [comment]
Please see similar issues: #91, #92. Thank you. :sunglasses: 

[Edit] You may also try **unblock your downloaded zip file** before extracting it. :)
https://support.microsoft.com/en-us/topic/block-suspicious-macros-in-office-on-windows-10-s-60785abc-d8b8-4b80-8f5d-67ddbee213e9
https://answers.microsoft.com/en-us/windows/forum/windows_7-security/clicking-on-unblock-for-a-files-security/9a6f5cfb-d0f8-4f50-9328-8aa2cad3a352
